// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { Credits_CreditType } from "../../../../../../../gen/exa/google/internal/cloud/code/v1internal/credits_pb.js";

export interface CreditsInput {
  creditType?: Credits_CreditType;
  creditAmount?: bigint;
  minimumCreditAmountForUsage?: bigint;
}
