// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

export interface V1internalUserSettingsInput {
  telemetryEnabled?: boolean;
  userDataCollectionForceDisabled?: boolean;
  marketingEmailsEnabled?: boolean;
}
