// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { APIProvider, Model, ModelProvider, PromptTemplaterType, ToolFormatterType } from "../../../../../../../gen/exa/codeium_common_pb/codeium_common_pb.js";
import { TimestampInput } from "../../../../../../google/protobuf/timestamp_pb.js";

export interface DeprecatedModelReroutingInfoInput {
  newModelId?: string;
  oldModelEnum?: Model;
  newModelEnum?: Model;
}

export interface FetchAvailableModelsResponse_DeprecatedModelIdsEntryInput {
  key?: string;
  value?: DeprecatedModelReroutingInfoInput;
}

export interface FetchAvailableModelsResponse_ModelsEntryInput {
  key?: string;
  value?: ModelDetailsInput;
}

export interface FetchAvailableModelsResponseInput {
  models?: FetchAvailableModelsResponse_ModelsEntryInput[];
  defaultAgentModelId?: string;
  agentModelSorts?: ModelSortInput[];
  commandModelIds?: string[];
  tabModelIds?: string[];
  imageGenerationModelIds?: string[];
  mqueryModelIds?: string[];
  webSearchModelIds?: string[];
  commitMessageModelIds?: string[];
  deprecatedModelIds?: FetchAvailableModelsResponse_DeprecatedModelIdsEntryInput[];
  audioTranscriptionModelIds?: string[];
  battleModeModelSorts?: ModelSortInput[];
}

export interface ModelDetails_SupportedMimeTypesEntryInput {
  key?: string;
  value?: boolean;
}

export interface ModelDetailsInput {
  displayName?: string;
  supportsImages?: boolean;
  supportsThinking?: boolean;
  thinkingBudget?: number;
  minThinkingBudget?: number;
  recommended?: boolean;
  maxTokens?: number;
  maxOutputTokens?: number;
  tokenizerType?: string;
  quotaInfo?: V1internalQuotaInfoInput;
  betaWarningMessage?: string;
  beta?: boolean;
  disabled?: boolean;
  description?: string;
  model?: Model;
  apiProvider?: APIProvider;
  modelProvider?: ModelProvider;
  supportsCumulativeContext?: boolean;
  tabJumpPrintLineRange?: boolean;
  supportsEstimateTokenCounter?: boolean;
  isInternal?: boolean;
  addCursorToFindReplaceTarget?: boolean;
  promptTemplaterType?: PromptTemplaterType;
  toolFormatterType?: ToolFormatterType;
  supportsRawThinking?: boolean;
  supportsVideo?: boolean;
  supportsPdf?: boolean;
  requiresLeadInGeneration?: boolean;
  tagTitle?: string;
  tagDescription?: string;
  requiresNoXmlToolExamples?: boolean;
  supportedMimeTypes?: ModelDetails_SupportedMimeTypesEntryInput[];
  requiresImageOutputOutsideFunctionResponses?: boolean;
  preview?: boolean;
  thinkingLevel?: number;
  toolResponseKey?: string;
  modelExperiments?: ModelExperimentsInput;
}

export interface ModelExperiments_ExperimentsEntryInput {
  key?: string;
  value?: V1internalExperimentValueInput;
}

export interface ModelExperimentsInput {
  experiments?: ModelExperiments_ExperimentsEntryInput[];
}

export interface ModelGroupInput {
  displayName?: string;
  modelIds?: string[];
}

export interface ModelSortInput {
  displayName?: string;
  groups?: ModelGroupInput[];
}

export interface V1internalExperimentValueInput {
  boolValue?: boolean;
  floatValue?: number;
  intValue?: bigint;
  stringValue?: string;
}

export interface V1internalQuotaInfoInput {
  remainingFraction?: number;
  resetTime?: TimestampInput;
}
