// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { IneligibleTier_IneligibleTierReasonCodes, ReleaseChannel_ChannelType, UserTier_UpgradeType } from "../../../../../../../gen/exa/google/internal/cloud/code/v1internal/onboarding_pb.js";
import { RpcStatusInput } from "../../../../../../google/rpc/status_pb.js";
import { CreditsInput } from "./credits_pb.js";

export interface IneligibleTierInput {
  reasonCode?: IneligibleTier_IneligibleTierReasonCodes;
  reasonMessage?: string;
  tierId?: string;
  tierName?: string;
  validationErrorMessage?: string;
  validationUrlLinkText?: string;
  validationUrl?: string;
  validationLearnMoreLinkText?: string;
  validationLearnMoreUrl?: string;
}

export interface LoadCodeAssistResponseInput {
  currentTier?: UserTierInput;
  allowedTiers?: UserTierInput[];
  cloudaicompanionProject?: string;
  projectValidationError?: RpcStatusInput;
  ineligibleTiers?: IneligibleTierInput[];
  gcpManaged?: boolean;
  manageSubscriptionUri?: string;
  releaseChannel?: ReleaseChannelInput;
  upgradeSubscriptionUri?: string;
  g1Tier?: string;
  paidTier?: UserTierInput;
}

export interface ReleaseChannelInput {
  type?: ReleaseChannel_ChannelType;
  name?: string;
  description?: string;
}

export interface UserTier_PrivacyNoticeInput {
  showNotice?: boolean;
  noticeText?: string;
  minorNotice?: boolean;
}

export interface UserTierInput {
  id?: string;
  name?: string;
  description?: string;
  userDefinedCloudaicompanionProject?: boolean;
  privacyNotice?: UserTier_PrivacyNoticeInput;
  isDefault?: boolean;
  upgradeSubscriptionUri?: string;
  upgradeSubscriptionText?: string;
  upgradeButtonText?: string;
  clientExperienceTag?: string;
  upgradeSubscriptionType?: UserTier_UpgradeType;
  usesGcpTos?: boolean;
  availableCredits?: CreditsInput[];
}
