// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { AnyInput } from "../protobuf/any_pb.js";

export interface RpcStatusInput {
  code?: number;
  message?: string;
  details?: AnyInput[];
}
