// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { TimestampInput } from "../../google/protobuf/timestamp_pb.js";

export interface TimeRangeInput {
  start?: TimestampInput;
  end?: TimestampInput;
}
