// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { APIProvider, AgentBrowserTools, AnnotationsConfig, ArtifactApprovalStatus, ArtifactReviewMode, ArtifactType, AutoContinueOnMaxGeneratorInvocations, AutocompleteSpeed, BrowserJsExecutionPolicy, CascadeCommandsAutoExecution, CascadeInputAutocomplete, CascadeNUXIcon, CascadeNUXLocation, CascadeNUXTrigger, CascadeRunExtensionCode, CascadeRunExtensionCodeAutoRun, CascadeWebSearchTool, CodeContextType, ContextSnippetType, ConversationalPlannerMode, DeploymentProvider, DetectAndUseProxy, DocumentType, EventType, ExperimentKey, ExperimentSource, IndexChoice, Language, MarkdownNodeType, Model, ModelAlias, ModelPricingType, ModelProvider, ModelStatus, ModelType, Permission, PlanMode, PlanningMode, PromptAnnotationKind, PromptTemplaterType, RememberLastModelSelection, ScmProvider, StatusLevel, TabEnabled, TabToJump, TeamsFeatures, TeamsTier, TerminalShellCommandSource, TerminalShellCommandStatus, ThemePreference, ThirdPartyWebSearchProvider, ToolFormatterType, TransactionStatus, UserFeatures, UserTeamStatus, WorkingDirectoryStatus } from "../../../gen/exa/codeium_common_pb/codeium_common_pb.js";
import { TimestampInput } from "../../google/protobuf/timestamp_pb.js";
import { UserTierInput } from "../google/internal/cloud/code/v1internal/onboarding_pb.js";

export interface AllowedModelConfigInput {
  modelOrAlias?: ModelOrAliasInput;
  creditMultiplier?: number;
}

export interface AntigravityDeploymentInput {
  antigravityDeploymentId?: string;
  authUid?: string;
  deploymentProvider?: DeploymentProvider;
  providerDeploymentId?: string;
  antigravityProjectId?: string;
  projectId?: string;
  projectName?: string;
  workspacePath?: string;
  createdAt?: TimestampInput;
  updatedAt?: TimestampInput;
  domain?: string;
  subdomainName?: string;
  providerTeamId?: string;
  expiresAt?: TimestampInput;
  deploymentUrl?: string;
  claimedAt?: TimestampInput;
  deprovisionedAt?: TimestampInput;
  buildStatusUrl?: string;
  projectUrl?: string;
}

export interface ArtifactCommentInput {
  artifactUri?: string;
  comment?: string;
  approvalStatus?: ArtifactApprovalStatus;
  fullFile?: ArtifactFullFileTargetInput;
  selections?: ArtifactSelectionTargetInput;
}

export interface ArtifactFullFileTargetInput {
  image?: ImageDataInput;
  media?: MediaInput;
}

export interface ArtifactImageSelectionInput {
  croppedImage?: ImageDataInput;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  croppedMedia?: MediaInput;
}

export interface ArtifactMetadataInput {
  artifactType?: ArtifactType;
  summary?: string;
  createdAt?: TimestampInput;
  updatedAt?: TimestampInput;
  version?: bigint;
  requestFeedback?: boolean;
}

export interface ArtifactSelectionInput {
  textSelection?: TextSelectionInput;
  imageSelection?: ArtifactImageSelectionInput;
}

export interface ArtifactSelectionTargetInput {
  selections?: ArtifactSelectionInput[];
}

export interface BlobrefInput {
  blobId?: string;
}

export interface BrowserCodeBlockScopeItemInput {
  url?: string;
  title?: string;
  codeContent?: string;
  language?: Language;
  contextText?: string;
  pageId?: string;
}

export interface BrowserPageMetadataInput {
  url?: string;
  pageId?: string;
  pageTitle?: string;
  viewportWidth?: number;
  viewportHeight?: number;
  pageHeight?: number;
  faviconUrl?: string;
  devicePixelRatio?: number;
  lastVisitedTime?: TimestampInput;
}

export interface BrowserPageScopeItemInput {
  url?: string;
  title?: string;
  visibleTextContent?: string;
  pageId?: string;
}

export interface BrowserStateSnapshotInput {
  timestamp?: TimestampInput;
  userActivePageId?: string;
  pages?: BrowserPageMetadataInput[];
}

export interface BrowserTextScopeItemInput {
  url?: string;
  visibleText?: string;
  pageId?: string;
}

export interface CascadeModelConfigDataInput {
  clientModelConfigs?: ClientModelConfigInput[];
  clientModelSorts?: ClientModelSortInput[];
  defaultOverrideModelConfig?: DefaultOverrideModelConfigInput;
}

export interface CascadeNUXConfigInput {
  uid?: number;
  location?: CascadeNUXLocation;
  trigger?: CascadeNUXTrigger;
  analyticsEventName?: string;
  learnMoreUrl?: string;
  priority?: number;
  icon?: CascadeNUXIcon;
  requiresIdleCascade?: boolean;
  title?: string;
  body?: string;
  imageUrl?: string;
  videoUrl?: string;
}

export interface CciWithSubrangeInput {
  cci?: CodeContextItemInput;
  subrange?: ContextSubrangeInput;
}

export interface ChatStatsByModelEntryInput {
  modelId?: Model;
  chatStats?: ChatStatsInput;
}

export interface ChatStatsInput {
  chatsSent?: bigint;
  chatsReceived?: bigint;
  chatsAccepted?: bigint;
  chatsInsertedAtCursor?: bigint;
  chatsApplied?: bigint;
  chatLocUsed?: bigint;
  chatCodeBlocksUsed?: bigint;
  functionExplainCount?: bigint;
  functionDocstringCount?: bigint;
  functionRefactorCount?: bigint;
  codeBlockExplainCount?: bigint;
  codeBlockRefactorCount?: bigint;
  problemExplainCount?: bigint;
  functionUnitTestsCount?: bigint;
  activeDeveloperDays?: number;
}

export interface ChatToolCallInput {
  id?: string;
  name?: string;
  argumentsJson?: string;
  invalidJsonStr?: string;
  invalidJsonErr?: string;
  thoughtSignature?: string;
  thinkingSignature?: Uint8Array;
  originalArgumentsJson?: string;
}

export interface CitationInput {
  startIndex?: number;
  endIndex?: number;
  uri?: string;
  title?: string;
  license?: string;
}

export interface ClientModelConfig_SupportedMimeTypesEntryInput {
  key?: string;
  value?: boolean;
}

export interface ClientModelConfigInput {
  label?: string;
  modelOrAlias?: ModelOrAliasInput;
  creditMultiplier?: number;
  pricingType?: ModelPricingType;
  disabled?: boolean;
  supportsImages?: boolean;
  supportsLegacy?: boolean;
  isPremium?: boolean;
  betaWarningMessage?: string;
  isBeta?: boolean;
  provider?: ModelProvider;
  isRecommended?: boolean;
  allowedTiers?: TeamsTier[];
  description?: string;
  quotaInfo?: QuotaInfoInput;
  tagTitle?: string;
  tagDescription?: string;
  supportedMimeTypes?: ClientModelConfig_SupportedMimeTypesEntryInput[];
}

export interface ClientModelGroupInput {
  groupName?: string;
  modelLabels?: string[];
}

export interface ClientModelSortInput {
  name?: string;
  groups?: ClientModelGroupInput[];
}

export interface CodeContextItem_SnippetByTypeEntryInput {
  key?: string;
  value?: SnippetWithWordCountInput;
}

export interface CodeContextItemInput {
  absolutePathMigrateMeToUri?: string;
  absoluteUri?: string;
  workspacePaths?: WorkspacePathInput[];
  nodeName?: string;
  nodeLineage?: string[];
  startLine?: number;
  startCol?: number;
  endLine?: number;
  endCol?: number;
  contextType?: CodeContextType;
  language?: Language;
  snippetByType?: CodeContextItem_SnippetByTypeEntryInput[];
  repoInfo?: GitRepoInfoInput;
  fileContentHash?: Uint8Array;
}

export interface CodeDiagnosticInput {
  range?: RangeInput;
  message?: string;
  severity?: string;
  source?: string;
  uri?: string;
  id?: string;
  language?: Language;
  score?: bigint;
}

export interface CompletionByDateEntryInput {
  timestamp?: TimestampInput;
  completionStatistics?: CompletionStatisticsInput;
}

export interface CompletionByLanguageEntryInput {
  language?: Language;
  completionStatistics?: CompletionStatisticsInput;
}

export interface CompletionConfigurationInput {
  numCompletions?: bigint;
  maxTokens?: bigint;
  maxNewlines?: bigint;
  minLogProbability?: number;
  temperature?: number;
  firstTemperature?: number;
  topK?: bigint;
  topP?: number;
  stopPatterns?: string[];
  seed?: bigint;
  fimEotProbThreshold?: number;
  useFimEotThreshold?: boolean;
  doNotScoreStopTokens?: boolean;
  sqrtLenNormalizedLogProbScore?: boolean;
  lastMessageIsPartial?: boolean;
  returnLogprob?: boolean;
  disableParallelToolCalls?: boolean;
}

export interface CompletionStatisticsInput {
  numAcceptances?: number;
  numRejections?: number;
  numLinesAccepted?: number;
  numBytesAccepted?: number;
  numUsers?: number;
  activeDeveloperDays?: number;
  activeDeveloperHours?: number;
}

export interface ConsoleLogLineInput {
  timestampStr?: string;
  type?: string;
  output?: string;
  location?: string;
}

export interface ConsoleLogScopeItemInput {
  lines?: ConsoleLogLineInput[];
  serverAddress?: string;
}

export interface ContextScopeItemInput {
  file?: PathScopeItemInput;
  directory?: PathScopeItemInput;
  repository?: RepositoryScopeItemInput;
  codeContext?: CodeContextItemInput;
  cciWithSubrange?: CciWithSubrangeInput;
  repositoryPath?: RepositoryPathScopeItemInput;
  slack?: KnowledgeBaseScopeItemInput;
  github?: KnowledgeBaseScopeItemInput;
  fileLineRange?: FileLineRangeInput;
  textBlock?: TextBlockInput;
  jira?: KnowledgeBaseScopeItemInput;
  googleDrive?: KnowledgeBaseScopeItemInput;
  consoleLog?: ConsoleLogScopeItemInput;
  domElement?: DOMElementScopeItemInput;
  recipe?: RecipeScopeItemInput;
  knowledge?: KnowledgeBaseScopeItemInput;
  rule?: RuleScopeItemInput;
  mcpResource?: McpResourceItemInput;
  browserPage?: BrowserPageScopeItemInput;
  browserCodeBlock?: BrowserCodeBlockScopeItemInput;
  browserText?: BrowserTextScopeItemInput;
  conversation?: ConversationScopeItemInput;
  userActivity?: UserActivityScopeItemInput;
  terminal?: TerminalScopeItemInput;
  mcpPrompt?: McpPromptScopeItemInput;
}

export interface ContextSubrangeInput {
  snippetType?: ContextSnippetType;
  startOffset?: bigint;
  endOffset?: bigint;
}

export interface ConversationScopeItemInput {
  id?: string;
  title?: string;
  lastModifiedTime?: TimestampInput;
}

export interface DefaultOverrideModelConfigInput {
  modelOrAlias?: ModelOrAliasInput;
  versionId?: string;
}

export interface DeployTargetInput {
  deploymentProvider?: DeploymentProvider;
  isSandbox?: boolean;
  providerTeamId?: string;
  providerTeamSlug?: string;
  domain?: string;
}

export interface DiffCommentInfoInput {
  originalSelection?: TextSelectionInput;
  modifiedSelection?: TextSelectionInput;
  comment?: string;
}

export interface DocumentInput {
  absolutePathMigrateMeToUri?: string;
  absoluteUri?: string;
  relativePathMigrateMeToWorkspaceUri?: string;
  workspaceUri?: string;
  text?: string;
  editorLanguage?: string;
  language?: Language;
  cursorOffset?: bigint;
  cursorPosition?: DocumentPositionInput;
  lineEnding?: string;
  visibleRange?: RangeInput;
  isCutoffStart?: boolean;
  isCutoffEnd?: boolean;
  linesCutoffStart?: number;
  linesCutoffEnd?: number;
  timestamp?: TimestampInput;
  isDirty?: boolean;
  isSynthetic?: boolean;
}

export interface DocumentLinesElementInput {
  documentQuery?: DocumentQueryInput;
  overlappedCodeContextItems?: CodeContextItemInput[];
  firstElementSuffixOverlap?: number;
  lastElementPrefixOverlap?: number;
}

export interface DocumentOutlineElementInput {
  codeContextItem?: CodeContextItemInput;
  documentLinesElement?: DocumentLinesElementInput;
  text?: string;
}

export interface DocumentOutlineInput {
  elements?: DocumentOutlineElementInput[];
  startIndex?: bigint;
}

export interface DocumentPositionInput {
  row?: bigint;
  col?: bigint;
}

export interface DocumentQueryInput {
  text?: string;
  cursorOffset?: number;
  startLine?: number;
  endLine?: number;
  useCharacterPosition?: boolean;
}

export interface DOMElementScopeItemInput {
  tagName?: string;
  outerHtml?: string;
  id?: string;
  reactComponentName?: string;
  fileLineRange?: FileLineRangeInput;
}

export interface DOMNode_ElementNode_AttributesEntryInput {
  key?: string;
  value?: string;
}

export interface DOMNode_ElementNodeInput {
  tagName?: string;
  xpath?: string;
  children?: string[];
  attributes?: DOMNode_ElementNode_AttributesEntryInput[];
  isInteractive?: boolean;
  isTopElement?: boolean;
  highlightIndex?: number;
  centralX?: number;
  centralY?: number;
}

export interface DOMNode_TextNodeInput {
  text?: string;
}

export interface DOMNodeInput {
  isVisible?: boolean;
  element?: DOMNode_ElementNodeInput;
  text?: DOMNode_TextNodeInput;
}

export interface DOMTree_MapEntryInput {
  key?: string;
  value?: DOMNodeInput;
}

export interface DOMTreeInput {
  rootId?: string;
  map?: DOMTree_MapEntryInput[];
}

export interface ErrorTraceInput {
  errorId?: string;
  timestampUnixMs?: bigint;
  stacktrace?: string;
  recovered?: boolean;
  fullStderr?: string;
  ideName?: string;
  ideVersion?: string;
  os?: string;
  isDev?: boolean;
}

export interface EventInput {
  eventType?: EventType;
  eventJson?: string;
  timestampUnixMs?: bigint;
}

export interface ExperimentConfigInput {
  experiments?: ExperimentWithVariantInput[];
  forceEnableExperiments?: ExperimentKey[];
  forceDisableExperiments?: ExperimentKey[];
  forceEnableExperimentsWithVariants?: ExperimentWithVariantInput[];
  forceEnableExperimentStrings?: string[];
  forceDisableExperimentStrings?: string[];
  devMode?: boolean;
}

export interface ExperimentWithVariantInput {
  key?: ExperimentKey;
  keyString?: string;
  disabled?: boolean;
  source?: ExperimentSource;
  string?: string;
  json?: string;
  csv?: string;
}

export interface FileCommentInfoInput {
  comment?: string;
  selection?: TextSelectionInput;
}

export interface FileCommentInput {
  fileUri?: string;
  fileCommentInfos?: FileCommentInfoInput[];
}

export interface FileDiffCommentInput {
  fileUri?: string;
  diffCommentInfos?: DiffCommentInfoInput[];
}

export interface FileLineRangeInput {
  absoluteUri?: string;
  startLine?: number;
  endLine?: number;
}

export interface GitRepoInfoInput {
  name?: string;
  owner?: string;
  repoName?: string;
  commit?: string;
  versionAlias?: string;
  scmProvider?: ScmProvider;
  baseGitUrl?: string;
}

export interface GuidelineInput {
  items?: GuidelineItemInput[];
}

export interface GuidelineItemInput {
  guideline?: string;
}

export interface ImageDataInput {
  base64Data?: string;
  mimeType?: string;
  caption?: string;
  uri?: string;
}

export interface KnowledgeBaseChunkInput {
  position?: number;
  text?: string;
  markdownChunk?: MarkdownChunkInput;
}

export interface KnowledgeBaseGroupInput {
  description?: string;
  item?: KnowledgeBaseItemWithMetadataInput;
  children?: KnowledgeBaseGroupInput[];
}

export interface KnowledgeBaseItemInput {
  documentId?: string;
  url?: string;
  title?: string;
  timestamp?: TimestampInput;
  chunks?: KnowledgeBaseChunkInput[];
  summary?: string;
  domTree?: DOMTreeInput;
  image?: ImageDataInput;
  media?: MediaInput;
  text?: string;
}

export interface KnowledgeBaseItemWithMetadataInput {
  knowledgeBaseItem?: KnowledgeBaseItemInput;
  score?: number;
  indexName?: string;
  documentSourceName?: string;
}

export interface KnowledgeBaseScopeItemInput {
  documentId?: string;
  index?: IndexChoice;
  documentType?: DocumentType;
  displayName?: string;
  description?: string;
  displaySource?: string;
  url?: string;
}

export interface LanguageServerDiagnosticsInput {
  logs?: string[];
}

export interface LspReferenceInput {
  uri?: string;
  range?: RangeInput;
  snippet?: string;
}

export interface MarkdownChunk_MarkdownHeaderInput {
  type?: MarkdownNodeType;
  text?: string;
}

export interface MarkdownChunkInput {
  headers?: MarkdownChunk_MarkdownHeaderInput[];
  text?: string;
}

export interface McpCommandTemplate_EnvEntryInput {
  key?: string;
  value?: string;
}

export interface McpCommandTemplateInput {
  command?: string;
  args?: string[];
  env?: McpCommandTemplate_EnvEntryInput[];
}

export interface McpCommandVariableInput {
  name?: string;
  title?: string;
  description?: string;
  link?: string;
}

export interface McpLocalServer_EnvEntryInput {
  key?: string;
  value?: string;
}

export interface McpLocalServerInput {
  command?: string;
  args?: string[];
  env?: McpLocalServer_EnvEntryInput[];
}

export interface McpPromptArgumentInput {
  name?: string;
  description?: string;
  required?: boolean;
}

export interface McpPromptMessageInput {
  role?: string;
  text?: string;
  media?: MediaInput;
  resource?: McpResourceContentInput;
}

export interface McpPromptScopeItem_ArgumentValuesEntryInput {
  key?: string;
  value?: string;
}

export interface McpPromptScopeItemInput {
  serverName?: string;
  name?: string;
  description?: string;
  arguments?: McpPromptArgumentInput[];
  argumentValues?: McpPromptScopeItem_ArgumentValuesEntryInput[];
  messages?: McpPromptMessageInput[];
}

export interface McpRemoteServer_HeadersEntryInput {
  key?: string;
  value?: string;
}

export interface McpRemoteServerInput {
  type?: string;
  url?: string;
  headers?: McpRemoteServer_HeadersEntryInput[];
}

export interface McpResourceContentInput {
  uri?: string;
  text?: TextDataInput;
  image?: ImageDataInput;
  mediaContent?: MediaInput;
}

export interface McpResourceItemInput {
  uri?: string;
  name?: string;
  description?: string;
  mimeType?: string;
  serverName?: string;
}

export interface McpServerCommandInput {
  template?: McpCommandTemplateInput;
  variables?: McpCommandVariableInput[];
}

export interface McpServerConfigInput {
  serverId?: string;
  local?: McpLocalServerInput;
  remote?: McpRemoteServerInput;
}

export interface McpServerTemplate_CommandsEntryInput {
  key?: string;
  value?: McpServerCommandInput;
}

export interface McpServerTemplateInput {
  title?: string;
  id?: string;
  link?: string;
  description?: string;
  commands?: McpServerTemplate_CommandsEntryInput[];
}

export interface MediaInput {
  mimeType?: string;
  description?: string;
  uri?: string;
  thumbnail?: Uint8Array;
  durationSeconds?: number;
  inlineData?: Uint8Array;
  blobref?: BlobrefInput;
}

export interface MetricsRecord_DetailsEntryInput {
  key?: string;
  value?: string;
}

export interface MetricsRecordInput {
  name?: string;
  value?: number;
  details?: MetricsRecord_DetailsEntryInput[];
  error?: string;
  trajectoryId?: string;
  lowerBetter?: boolean;
  isBool?: boolean;
}

export interface ModelFeatures_SupportedMimeTypesEntryInput {
  key?: string;
  value?: boolean;
}

export interface ModelFeaturesInput {
  supportsContextTokens?: boolean;
  requiresInstructTags?: boolean;
  requiresFimContext?: boolean;
  requiresContextSnippetPrefix?: boolean;
  requiresContextRelevanceTags?: boolean;
  requiresLlama3Tokens?: boolean;
  zeroShotCapable?: boolean;
  requiresAutocompleteAsCommand?: boolean;
  supportsCursorAwareSupercomplete?: boolean;
  supportsImages?: boolean;
  supportsPdf?: boolean;
  supportsVideo?: boolean;
  supportedMimeTypes?: ModelFeatures_SupportedMimeTypesEntryInput[];
  supportsToolCalls?: boolean;
  doesNotSupportToolChoice?: boolean;
  supportsCumulativeContext?: boolean;
  tabJumpPrintLineRange?: boolean;
  supportsThinking?: boolean;
  supportsAdaptiveThinking?: boolean;
  supportsRawThinking?: boolean;
  supportsEstimateTokenCounter?: boolean;
  addCursorToFindReplaceTarget?: boolean;
  supportsTabJumpUseWholeDocument?: boolean;
  supportsModelInfoOverride?: boolean;
  requiresLeadInGeneration?: boolean;
  requiresNoXmlToolExamples?: boolean;
}

export interface ModelInfoInput {
  modelId?: Model;
  isInternal?: boolean;
  modelType?: ModelType;
  maxTokens?: number;
  tokenizerType?: string;
  modelFeatures?: ModelFeaturesInput;
  apiProvider?: APIProvider;
  modelName?: string;
  supportsContext?: boolean;
  embedDim?: number;
  baseUrl?: string;
  chatModelName?: string;
  maxOutputTokens?: number;
  promptTemplaterType?: PromptTemplaterType;
  toolFormatterType?: ToolFormatterType;
  thinkingBudget?: number;
  minThinkingBudget?: number;
  useCcpaForEval?: boolean;
  thinkingLevel?: number;
  displayName?: string;
  toolResponseKey?: string;
}

export interface ModelOrAliasInput {
  model?: Model;
  alias?: ModelAlias;
}

export interface ModelStatusInfoInput {
  model?: Model;
  message?: string;
  status?: ModelStatus;
}

export interface ModelUsageStats_ResponseHeaderEntryInput {
  key?: string;
  value?: string;
}

export interface ModelUsageStatsInput {
  model?: Model;
  inputTokens?: bigint;
  outputTokens?: bigint;
  thinkingOutputTokens?: bigint;
  responseOutputTokens?: bigint;
  cacheReadTokens?: bigint;
  apiProvider?: APIProvider;
  messageId?: string;
  responseHeader?: ModelUsageStats_ResponseHeaderEntryInput[];
  responseId?: string;
  providerAssignedMessageId?: string;
  cacheWriteTokens?: bigint;
}

export interface MQueryConfigInput {
  shouldBatchCcis?: boolean;
  maxTokensPerSubrange?: bigint;
  numParserWorkers?: bigint;
  numWorkersPerDistributedScorer?: bigint;
  verbose?: boolean;
  ignoreExtensions?: string[];
  ignoreDirectoryStubs?: string[];
  minTokenSpaceForContext?: number;
  maxTargetFiles?: number;
  topCciCount?: number;
}

export interface PathScopeItem_WorkspaceRelativePathsMigrateMeToWorkspaceUrisEntryInput {
  key?: string;
  value?: string;
}

export interface PathScopeItem_WorkspaceUrisToRelativePathsEntryInput {
  key?: string;
  value?: string;
}

export interface PathScopeItemInput {
  absolutePathMigrateMeToUri?: string;
  absoluteUri?: string;
  workspaceRelativePathsMigrateMeToWorkspaceUris?: PathScopeItem_WorkspaceRelativePathsMigrateMeToWorkspaceUrisEntryInput[];
  workspaceUrisToRelativePaths?: PathScopeItem_WorkspaceUrisToRelativePathsEntryInput[];
  numFiles?: number;
  numBytes?: bigint;
}

export interface PermissionGrantsConfigInput {
  allow?: string[];
  deny?: string[];
  ask?: string[];
}

export interface PlanInfo_DefaultTeamFeaturesEntryInput {
  key?: number;
  value?: TeamsFeaturesMetadataInput;
}

export interface PlanInfoInput {
  teamsTier?: TeamsTier;
  planName?: string;
  hasAutocompleteFastMode?: boolean;
  allowStickyPremiumModels?: boolean;
  hasForgeAccess?: boolean;
  disableCodeSnippetTelemetry?: boolean;
  allowPremiumCommandModels?: boolean;
  hasTabToJump?: boolean;
  maxNumPremiumChatMessages?: bigint;
  maxNumChatInputTokens?: bigint;
  maxCustomChatInstructionCharacters?: bigint;
  maxNumPinnedContextItems?: bigint;
  maxLocalIndexSize?: bigint;
  maxUnclaimedSites?: number;
  monthlyPromptCredits?: number;
  monthlyFlowCredits?: number;
  monthlyFlexCreditPurchaseAmount?: number;
  isTeams?: boolean;
  isEnterprise?: boolean;
  canBuyMoreCredits?: boolean;
  cascadeWebSearchEnabled?: boolean;
  canCustomizeAppIcon?: boolean;
  cascadeCanAutoRunCommands?: boolean;
  canGenerateCommitMessages?: boolean;
  knowledgeBaseEnabled?: boolean;
  cascadeAllowedModelsConfig?: AllowedModelConfigInput[];
  defaultTeamConfig?: TeamConfigInput;
  canShareConversations?: boolean;
  canAllowCascadeInBackground?: boolean;
  defaultTeamFeatures?: PlanInfo_DefaultTeamFeaturesEntryInput[];
  browserEnabled?: boolean;
}

export interface PlanStatusInput {
  planInfo?: PlanInfoInput;
  planStart?: TimestampInput;
  planEnd?: TimestampInput;
  availablePromptCredits?: number;
  availableFlowCredits?: number;
  availableFlexCredits?: number;
  usedFlexCredits?: number;
  usedFlowCredits?: number;
  usedPromptCredits?: number;
  topUpStatus?: TopUpStatusInput;
}

export interface Point2Input {
  x?: number;
  y?: number;
}

export interface PromptAnnotationRangeInput {
  kind?: PromptAnnotationKind;
  byteOffsetStart?: bigint;
  byteOffsetEnd?: bigint;
  suffix?: string;
}

export interface PromptStageLatencyInput {
  name?: string;
  latencyMs?: bigint;
}

export interface QuotaInfoInput {
  remainingFraction?: number;
  resetTime?: TimestampInput;
}

export interface RangeInput {
  startOffset?: bigint;
  endOffset?: bigint;
  startPosition?: DocumentPositionInput;
  endPosition?: DocumentPositionInput;
}

export interface RecipeScopeItemInput {
  recipeId?: string;
  title?: string;
  description?: string;
  systemPrompt?: string;
  uri?: string;
}

export interface RecitationInput {
  citation?: CitationInput;
  content?: string;
}

export interface RecitationMetadataInput {
  recitations?: RecitationInput[];
}

export interface RepositoryInput {
  computedName?: string;
  gitOriginUrl?: string;
  gitUpstreamUrl?: string;
  reportedName?: string;
  modelName?: string;
  submoduleUrl?: string;
  submodulePath?: string;
}

export interface RepositoryPathScopeItemInput {
  repoInfo?: GitRepoInfoInput;
  relativePath?: string;
  isDir?: boolean;
}

export interface RepositoryScopeItemInput {
  repoInfo?: GitRepoInfoInput;
}

export interface RuleScopeItemInput {
  rulePath?: string;
  ruleName?: string;
  description?: string;
}

export interface SnippetWithWordCount_WordCountBySplitterEntryInput {
  key?: string;
  value?: WordCountInput;
}

export interface SnippetWithWordCountInput {
  snippet?: string;
  wordCountBySplitter?: SnippetWithWordCount_WordCountBySplitterEntryInput[];
}

export interface StatusInput {
  level?: StatusLevel;
  message?: string;
}

export interface TeamConfigInput {
  teamId?: string;
  userPromptCreditCap?: number;
  userFlowCreditCap?: number;
  autoProvisionCascadeSeat?: boolean;
  allowMcpServers?: boolean;
  allowAutoRunCommands?: boolean;
  maxUnclaimedSites?: number;
  allowAppDeployments?: boolean;
  allowSandboxAppDeployments?: boolean;
  allowTeamsAppDeployments?: boolean;
  maxNewSitesPerDay?: number;
  allowGithubReviews?: boolean;
  allowGithubDescriptionEdits?: boolean;
  pullRequestReviewGuidelines?: string;
  pullRequestDescriptionGuidelines?: string;
  disableToolCalls?: boolean;
  allowIndividualLevelAnalytics?: boolean;
  allowConversationSharing?: boolean;
  pullRequestReviewRateLimit?: number;
  allowAttribution?: boolean;
  allowedMcpServers?: McpServerConfigInput[];
  allowGithubAutoReviews?: boolean;
  allowBrowserExperimentalFeatures?: boolean;
  disableToolCallExecutionOutsideWorkspace?: boolean;
}

export interface TeamOrganizationalControlsInput {
  teamId?: string;
  cascadeModelLabels?: string[];
  commandModelLabels?: string[];
  createdAt?: TimestampInput;
  updatedAt?: TimestampInput;
  extensionModelLabels?: string[];
}

export interface TeamsFeaturesMetadataInput {
  isActive?: boolean;
  stripeSubscriptionId?: string;
  hasAccess?: boolean;
}

export interface TerminalScopeItemInput {
  processId?: string;
  name?: string;
  lastCommand?: string;
  selectionContent?: string;
}

export interface TerminalShellCommandInput {
  id?: string;
  shellPid?: number;
  commandLine?: string;
  cwd?: string;
  output?: Uint8Array;
  exitCode?: number;
  startTime?: TimestampInput;
  endTime?: TimestampInput;
  lastUpdatedTime?: TimestampInput;
  status?: TerminalShellCommandStatus;
  source?: TerminalShellCommandSource;
}

export interface TextBlockInput {
  content?: string;
  fileLineRange?: FileLineRangeInput;
  label?: string;
}

export interface TextDataInput {
  text?: string;
  mimeType?: string;
}

export interface TextOrScopeItemInput {
  text?: string;
  item?: ContextScopeItemInput;
}

export interface TextSelectionInput {
  content?: string;
  startLine?: number;
  endLine?: number;
}

export interface ThirdPartyWebSearchConfigInput {
  provider?: ThirdPartyWebSearchProvider;
}

export interface TopUpStatusInput {
  topUpTransactionStatus?: TransactionStatus;
  topUpEnabled?: boolean;
  monthlyTopUpAmount?: number;
  topUpSpent?: number;
  topUpIncrement?: number;
  topUpCriteriaMet?: boolean;
}

export interface UnleashContext_PropertiesEntryInput {
  key?: string;
  value?: string;
}

export interface UnleashContextInput {
  userId?: string;
  sessionId?: string;
  properties?: UnleashContext_PropertiesEntryInput[];
}

export interface UserActivityScopeItemInput {
  id?: string;
  branch?: string;
  current?: boolean;
}

export interface UserSettings_CustomModelsEntryInput {
  key?: string;
  value?: ModelInfoInput;
}

export interface UserSettingsInput {
  openMostRecentChatConversation?: boolean;
  lastSelectedModel?: Model;
  themePreference?: ThemePreference;
  rememberLastModelSelection?: RememberLastModelSelection;
  autocompleteSpeed?: AutocompleteSpeed;
  lastSelectedModelName?: string;
  lastSelectedCascadeModel?: Model;
  lastSelectedCascadeModelOrAlias?: ModelOrAliasInput;
  cascadePlannerMode?: ConversationalPlannerMode;
  lastModelOverride?: Model;
  lastModelDefaultOverrideVersionId?: string;
  cascadeAllowedCommands?: string[];
  cascadeDeniedCommands?: string[];
  cascadeWebSearchDisabled?: boolean;
  tabEnabled?: TabEnabled;
  disableSelectionPopup?: boolean;
  disableExplainProblemInlayHint?: boolean;
  disableInlayHintShortcuts?: boolean;
  disableOpenCascadeOnReload?: boolean;
  disableAutoOpenEditedFiles?: boolean;
  disableTabToJump?: boolean;
  cascadeAutoExecutionPolicy?: CascadeCommandsAutoExecution;
  lastSelectedCascadeId?: string;
  explainAndFixInCurrentConversation?: boolean;
  allowCascadeAccessGitignoreFiles?: boolean;
  allowAgentAccessNonWorkspaceFiles?: boolean;
  disableCascadeAutoFixLints?: boolean;
  detectAndUseProxy?: DetectAndUseProxy;
  disableTabToImport?: boolean;
  useClipboardForCompletions?: boolean;
  disableHighlightAfterAccept?: boolean;
  disableAutoGenerateMemories?: boolean;
  enableSoundsForSpecialEvents?: boolean;
  enableTabSounds?: boolean;
  allowCascadeInBackground?: boolean;
  tabToJump?: TabToJump;
  cascadeWebSearch?: CascadeWebSearchTool;
  enableTerminalCompletion?: boolean;
  isSnoozed?: boolean;
  disableCascadeInBackground?: boolean;
  customWorkspace?: string[];
  globalPlanModePreference?: PlanMode;
  cachedCascadeModelConfigs?: ClientModelConfigInput[];
  cachedCascadeModelSorts?: ClientModelSortInput[];
  cascadeRunExtensionCode?: CascadeRunExtensionCode;
  cascadeRunExtensionCodeAutoRun?: CascadeRunExtensionCodeAutoRun;
  cascadeInputAutocomplete?: CascadeInputAutocomplete;
  autoContinueOnMaxGeneratorInvocations?: AutoContinueOnMaxGeneratorInvocations;
  recentlyUsedCascadeModels?: string[];
  annotationsConfig?: AnnotationsConfig;
  relativeWorkingDirPaths?: string[];
  customModels?: UserSettings_CustomModelsEntryInput[];
  disableCodeSnippetTelemetry?: boolean;
  planningMode?: PlanningMode;
  agentBrowserTools?: AgentBrowserTools;
  artifactReviewMode?: ArtifactReviewMode;
  allowTabAccessGitignoreFiles?: boolean;
  browserChromePath?: string;
  browserUserProfilePath?: string;
  browserCdpPort?: number;
  demoModeEnabled?: boolean;
  browserJsExecutionPolicy?: BrowserJsExecutionPolicy;
  secureModeEnabled?: boolean;
}

export interface UserStatusInput {
  pro?: boolean;
  disableTelemetry?: boolean;
  name?: string;
  ignoreChatTelemetrySetting?: boolean;
  teamId?: string;
  teamStatus?: UserTeamStatus;
  email?: string;
  userFeatures?: UserFeatures[];
  teamsFeatures?: TeamsFeatures[];
  permissions?: Permission[];
  planInfo?: PlanInfoInput;
  planStatus?: PlanStatusInput;
  hasUsedAntigravity?: boolean;
  userUsedPromptCredits?: bigint;
  userUsedFlowCredits?: bigint;
  hasFingerprintSet?: boolean;
  teamConfig?: TeamConfigInput;
  cascadeModelConfigData?: CascadeModelConfigDataInput;
  acceptedLatestTermsOfService?: boolean;
  g1Tier?: string;
  userTier?: UserTierInput;
  userDataCollectionForceDisabled?: boolean;
  profilePictureUrl?: string;
}

export interface ViewportInput {
  x?: number;
  y?: number;
  width?: number;
  height?: number;
}

export interface WebDocsOptionInput {
  label?: string;
  synonyms?: string[];
  isFeatured?: boolean;
  docsUrl?: string;
  docsSearchDomain?: string;
}

export interface WordCount_WordCountMapEntryInput {
  key?: string;
  value?: bigint;
}

export interface WordCountInput {
  wordCountMap?: WordCount_WordCountMapEntryInput[];
}

export interface WorkingDirectoryInfoInput {
  absoluteUri?: string;
  relativePath?: string;
  status?: WorkingDirectoryStatus;
  error?: string;
}

export interface WorkspacePathInput {
  workspaceMigrateMeToUri?: string;
  workspaceUri?: string;
  relativePath?: string;
}
