// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { ChatClientRequestStreamClientType } from "../../../gen/exa/chat_client_server_pb/chat_client_server_pb.js";
import { ChatFeedbackType } from "../../../gen/exa/chat_pb/chat_pb.js";
import { CodeContextType, ContextScopeType, Language, Model, ProviderSource, RefreshCustomizationType, ScmType } from "../../../gen/exa/codeium_common_pb/codeium_common_pb.js";
import { AcknowledgementType, CascadeRunStatus, CodeAcknowledgementScope, CortexTrajectorySource, CortexTrajectoryType, TrajectoryShareStatus } from "../../../gen/exa/cortex_pb/cortex_pb.js";
import { ClientTrajectoryVerbosity as jetski_cortex_pbClientTrajectoryVerbosity } from "../../../gen/exa/jetski_cortex_pb/jetski_cortex_pb.js";
import { AgentMessageOrigin, ClientTrajectoryVerbosity, CodeRevertActionType, CustomizationFileType, CustomizationPathsOperation, FileType, ForkTarget, IdeAction, SidecarAction } from "../../../gen/exa/language_server_pb/language_server_pb.js";
import { TimestampInput } from "../../google/protobuf/timestamp_pb.js";
import { CascadePluginTemplateInput } from "../cascade_plugins_pb/cascade_plugins_pb.js";
import { ChatExperimentStatusInput } from "../chat_pb/chat_pb.js";
import { CodeChangeWithContextInput } from "../code_edit/code_edit_pb/code_edit_pb.js";
import { ArtifactCommentInput, BrowserPageMetadataInput, CascadeNUXConfigInput, ChatStatsByModelEntryInput, ClientModelConfigInput, ClientModelSortInput, CodeDiagnosticInput, CompletionByDateEntryInput, CompletionByLanguageEntryInput, CompletionStatisticsInput, ConsoleLogScopeItemInput, ContextScopeItemInput, DefaultOverrideModelConfigInput, DocumentInput, ErrorTraceInput, EventInput, ExperimentConfigInput, FileCommentInput, FileDiffCommentInput, GitRepoInfoInput, ImageDataInput, LanguageServerDiagnosticsInput, McpPromptMessageInput, McpResourceItemInput, McpServerTemplateInput, MediaInput, ModelStatusInfoInput, PathScopeItemInput, PlanInfoInput, PromptStageLatencyInput, StatusInput, TeamOrganizationalControlsInput, TextOrScopeItemInput, UnleashContextInput, UserSettingsInput, UserStatusInput, WebDocsOptionInput, WorkingDirectoryInfoInput } from "../codeium_common_pb/codeium_common_pb.js";
import { ActionResultEditInput, AgentCustomizationInput, AgentScriptCommandSpecInput, AgentScriptItemInput, ArtifactSnapshotInput, CascadeConfigInput, CascadeUserInteractionInput, CortexMemoryInput, CortexStepGeneratorMetadataInput, CortexStepPlannerResponseInput, CustomAgentSpecInput, GrepSearchResultInput, ImplicitTrajectoryDescriptionInput, McpPromptSpecInput, McpServerSpecInput, McpServerStateInput, PluginItemInput, SidecarEventInput, SidecarEventPayloadInput, SidecarStatusInfoInput, SourceMetadataInput, TokenBreakdownInput, UserStepSnapshotInput, WorkflowSpecInput } from "../cortex_pb/cortex_pb.js";
import { UnifiedDiffInput } from "../diff_action_pb/diff_action_pb.js";
import { StepInput, TrajectoryInput } from "../gemini_coder/proto/trajectory_pb.js";
import { V1internalUserSettingsInput } from "../google/internal/cloud/code/v1internal/jetski_service_pb.js";
import { FetchAvailableModelsResponseInput } from "../google/internal/cloud/code/v1internal/model_configs_pb.js";
import { LoadCodeAssistResponseInput } from "../google/internal/cloud/code/v1internal/onboarding_pb.js";
import { StateInput } from "../jetbox_state_pb/jetbox_state_pb.js";
import { BaseTrajectoryIdentifierInput, CascadeTrajectorySummaryInput, ConversationAnnotationsInput, ImplicitTrajectoryInput } from "../jetski_cortex_pb/jetski_cortex_pb.js";

export interface AcceptTermsOfServiceRequestInput {
  version?: string;
}

export interface AcceptTermsOfServiceResponseInput {
}

export interface AcknowledgeCascadeCodeEditRequestInput {
  cascadeId?: string;
  absoluteUri?: string[];
  contents?: string[];
  accept?: boolean;
}

export interface AcknowledgeCascadeCodeEditResponseInput {
}

export interface AcknowledgeCodeActionStepRequestInput {
  cascadeId?: string;
  accept?: boolean;
  writtenFeedback?: string;
  acknowledgementScope?: CodeAcknowledgementScope;
  codeAcknowledgementRequestInfos?: CodeAcknowledgementRequestInfoInput[];
}

export interface AcknowledgeCodeActionStepResponseInput {
}

export interface AddToBrowserWhitelistRequestInput {
  hostname?: string;
  hostnames?: string[];
}

export interface AddToBrowserWhitelistResponseInput {
}

export interface AddTrackedWorkspaceRequestInput {
  workspace?: string;
  doNotWatchFiles?: boolean;
  isPassiveWorkspace?: boolean;
}

export interface AddTrackedWorkspaceResponseInput {
}

export interface AgentInstanceInput {
  name?: string;
  logFilePath?: string;
  latestTrajectoryId?: string;
  latestCascadeId?: string;
  lastStepUpdatedAt?: TimestampInput;
  description?: string;
}

export interface AgentTeamTaskInput {
  id?: string;
  isCompleted?: boolean;
  taskFileUri?: string;
}

export interface BranchInfoInput {
  name?: string;
  isCurrentBranch?: boolean;
}

export interface BrowserValidateCascadeOrCancelOverlayRequestInput {
  cascadeId?: string;
}

export interface BrowserValidateCascadeOrCancelOverlayResponseInput {
}

export interface CancelCascadeInvocationRequestInput {
  cascadeId?: string;
  killBackgroundTasks?: boolean;
  notifyParent?: boolean;
}

export interface CancelCascadeInvocationResponseInput {
}

export interface CancelCascadeStepsRequestInput {
  cascadeId?: string;
  stepIndices?: number[];
}

export interface CancelCascadeStepsResponseInput {
}

export interface CaptureConsoleLogsRequestInput {
  pageId?: string;
}

export interface CaptureConsoleLogsResponseInput {
  consoleLogs?: ConsoleLogScopeItemInput;
}

export interface CaptureScreenshotRequestInput {
  pageId?: string;
}

export interface CaptureScreenshotResponseInput {
  screenshot?: ImageDataInput;
  mediaScreenshot?: MediaInput;
}

export interface CheckoutSummaryInput {
  filesChanged?: number;
  additions?: number;
  deletions?: number;
}

export interface CheckoutWorktreeRequestInput {
  worktreeDirUri?: string;
  targetWorkspaceUri?: string;
  deleteWorktreeAfterCheckout?: boolean;
}

export interface CheckoutWorktreeResponseInput {
  success?: boolean;
  errorMessage?: string;
  summary?: CheckoutSummaryInput;
  diffPatch?: string;
}

export interface CodeAcknowledgementRequestInfoInput {
  uriPath?: string;
  stepIndices?: number[];
  preCodeActionsState?: string;
  postCodeActionsState?: string;
}

export interface CodeEditRevertPreviewInput {
  fileUri?: string;
  diff?: UnifiedDiffInput;
  actionType?: CodeRevertActionType;
}

export interface CodeFrequencyRecordInput {
  numCommits?: number;
  linesAdded?: number;
  linesDeleted?: number;
  recordStartTime?: TimestampInput;
  recordEndTime?: TimestampInput;
}

export interface CommitMessageDataInput {
  repoRoot?: string;
  commitMessageSummary?: string;
  commitMessageDescription?: string;
  changedFilesMigrateMeToUri?: string[];
  changedFileUris?: string[];
}

export interface CompleteMcpOAuthRequestInput {
  serverName?: string;
  authorizationCode?: string;
}

export interface CompleteMcpOAuthResponseInput {
}

export interface ConversationSearchResultInput {
  cascadeId?: string;
  title?: string;
  workspaceName?: string;
  snippet?: string;
  lastModifiedTime?: TimestampInput;
  needsAttention?: boolean;
  titleMatchRanges?: StringMatchRangeInput[];
  snippetMatchRanges?: StringMatchRangeInput[];
}

export interface ConvertTrajectoryToMarkdownRequestInput {
  trajectory?: TrajectoryInput;
  conversationId?: string;
}

export interface ConvertTrajectoryToMarkdownResponseInput {
  markdown?: string;
}

export interface CopyBuiltinWorkflowToWorkspaceRequestInput {
  workflow?: WorkflowSpecInput;
}

export interface CopyBuiltinWorkflowToWorkspaceResponseInput {
  workflow?: WorkflowSpecInput;
}

export interface CreateCitcWorkspaceRequestInput {
  items?: TextOrScopeItemInput[];
  media?: MediaInput[];
  cloneCurrentWorkspace?: boolean;
  sourceWorkspaceUri?: string;
}

export interface CreateCitcWorkspaceResponseInput {
  workspaceDirUri?: string;
  workspaceName?: string;
}

export interface CreateCustomizationFileRequestInput {
  fileType?: CustomizationFileType;
  fileName?: string;
  workspaceUri?: string;
}

export interface CreateCustomizationFileResponseInput {
  filePath?: string;
}

export interface CreateReplayWorkspaceRequestInput {
  trajectoryId?: string;
  stepIndex?: number;
  workspaceName?: string;
  targetUser?: string;
}

export interface CreateReplayWorkspaceResponseInput {
}

export interface CreateTrajectoryShareRequestInput {
  shareStatus?: TrajectoryShareStatus;
  cascadeId?: string;
}

export interface CreateTrajectoryShareResponseInput {
  url?: string;
}

export interface CreateWorktreeRequestInput {
  repoPath?: string;
  baseBranchName?: string;
  planInfo?: PlanInfoInput;
  items?: TextOrScopeItemInput[];
  images?: ImageDataInput[];
  media?: MediaInput[];
  worktreeName?: string;
}

export interface CreateWorktreeResponseInput {
  worktreeDirUri?: string;
  worktreeName?: string;
}

export interface CustomizationPathsListInput {
  paths?: string[];
}

export interface DeleteCascadeMemoryRequestInput {
  memoryId?: string;
}

export interface DeleteCascadeMemoryResponseInput {
}

export interface DeleteCascadeTrajectoryRequestInput {
  cascadeId?: string;
}

export interface DeleteCascadeTrajectoryResponseInput {
}

export interface DeleteFileOrDirectoryRequestInput {
  uri?: string;
}

export interface DeleteFileOrDirectoryResponseInput {
}

export interface DeleteMediaArtifactRequestInput {
  uri?: string;
}

export interface DeleteMediaArtifactResponseInput {
  success?: boolean;
  errorMessage?: string;
}

export interface DeleteQueuedUserInputStepRequestInput {
  cascadeId?: string;
  stepIndex?: number;
}

export interface DeleteQueuedUserInputStepResponseInput {
}

export interface DeleteWorktreeRequestInput {
  worktreeDirUri?: string;
  repoUri?: string;
}

export interface DeleteWorktreeResponseInput {
  success?: boolean;
  errorMessage?: string;
}

export interface DisconnectMcpOAuthRequestInput {
  serverName?: string;
}

export interface DisconnectMcpOAuthResponseInput {
}

export interface DumpFlightRecorderRequestInput {
  traceFilePath?: string;
}

export interface DumpFlightRecorderResponseInput {
}

export interface DumpPprofRequestInput {
  heapFilePath?: string;
  goroutineFilePath?: string;
  mutexFilePath?: string;
}

export interface DumpPprofResponseInput {
}

export interface EndAudioSessionRequestInput {
  sessionId?: string;
}

export interface EndAudioSessionResponseInput {
}

export interface EndBattleModeRequestInput {
  winnerConversationId?: string;
}

export interface EndBattleModeResponseInput {
  mainConversationId?: string;
}

export interface ExitRequestInput {
}

export interface ExitResponseInput {
}

export interface FetchUserInfoRequestInput {
}

export interface FetchUserInfoResponseInput {
  userSettings?: V1internalUserSettingsInput;
}

export interface FocusUserPageRequestInput {
  pageId?: string;
}

export interface FocusUserPageResponseInput {
}

export interface ForceBackgroundResearchRefreshRequestInput {
  mainlineTrajectoryId?: string;
  blocking?: boolean;
  fullRefresh?: boolean;
}

export interface ForceBackgroundResearchRefreshResponseInput {
}

export interface ForceStopCascadeTreeRequestInput {
  conversationId?: string;
}

export interface ForceStopCascadeTreeResponseInput {
  stoppedConversationIds?: string[];
}

export interface ForkConversationRequestInput {
  sourceCascadeId?: string;
  forkAtStepIndex?: number;
  targetForkWorkspace?: ForkTarget;
  sourceWorkspaceUris?: string[];
  items?: TextOrScopeItemInput[];
  media?: MediaInput[];
  agentScriptOverride?: AgentScriptItemInput;
}

export interface ForkConversationResponseInput {
  newCascadeId?: string;
  newWorkspaceUri?: string;
  newWorkspaceName?: string;
  forkedAtStepIndex?: number;
}

export interface GenerateCommitMessageRequestInput {
  planInfo?: PlanInfoInput;
  repoRoot?: string;
}

export interface GenerateCommitMessageResponseInput {
  commitMessage?: CommitMessageDataInput;
}

export interface GenerateSkillInstallationCLRequestInput {
  skillPaths?: string[];
  ldap?: string;
}

export interface GenerateSkillInstallationCLResponseInput {
  clNumber?: bigint;
  clUrl?: string;
}

export interface GetAgentScriptsRequestInput {
  workspaceUris?: string[];
}

export interface GetAgentScriptsResponseInput {
  agentScripts?: AgentScriptItemInput[];
  agentCustomizations?: AgentCustomizationInput[];
}

export interface GetAgentTeamMetadataRequestInput {
  projectDirUri?: string;
}

export interface GetAgentTeamMetadataResponseInput {
  agents?: AgentInstanceInput[];
  tasks?: AgentTeamTaskInput[];
}

export interface GetAllBrowserWhitelistedUrlsRequestInput {
}

export interface GetAllBrowserWhitelistedUrlsResponseInput {
  whitelistedUrls?: string[];
}

export interface GetAllCascadeTrajectoriesRequestInput {
  excludeSubtrajectories?: boolean;
}

export interface GetAllCascadeTrajectoriesResponse_TrajectorySummariesEntryInput {
  key?: string;
  value?: CascadeTrajectorySummaryInput;
}

export interface GetAllCascadeTrajectoriesResponseInput {
  trajectorySummaries?: GetAllCascadeTrajectoriesResponse_TrajectorySummariesEntryInput[];
}

export interface GetAllCustomAgentConfigsRequestInput {
}

export interface GetAllCustomAgentConfigsResponse_ConfigMapEntryInput {
  key?: string;
  value?: string;
}

export interface GetAllCustomAgentConfigsResponseInput {
  configMap?: GetAllCustomAgentConfigsResponse_ConfigMapEntryInput[];
}

export interface GetAllPluginsRequestInput {
  workspaceUris?: string[];
}

export interface GetAllPluginsResponseInput {
  plugins?: PluginInput[];
}

export interface GetAllRulesRequestInput {
  workspaceUris?: string[];
}

export interface GetAllRulesResponseInput {
  memories?: CortexMemoryInput[];
}

export interface GetAllSkillsRequestInput {
  workspaceUris?: string[];
}

export interface GetAllSkillsResponseInput {
  skills?: WorkflowSpecInput[];
}

export interface GetAllWorkflowsRequestInput {
  workspaceUris?: string[];
}

export interface GetAllWorkflowsResponseInput {
  workflows?: WorkflowSpecInput[];
}

export interface GetArtifactSnapshotsRequestInput {
  cascadeId?: string;
}

export interface GetArtifactSnapshotsResponseInput {
  artifactSnapshots?: ArtifactSnapshotInput[];
}

export interface GetAvailableCascadePluginsRequestInput {
  os?: string;
  searchQuery?: string;
}

export interface GetAvailableCascadePluginsResponseInput {
  plugins?: CascadePluginTemplateInput[];
}

export interface GetAvailableModelsRequestInput {
  forceRefresh?: boolean;
}

export interface GetAvailableModelsResponseInput {
  response?: FetchAvailableModelsResponseInput;
}

export interface GetBrowserOpenConversationRequestInput {
}

export interface GetBrowserOpenConversationResponseInput {
  cascadeId?: string;
}

export interface GetBrowserWhitelistFilePathRequestInput {
}

export interface GetBrowserWhitelistFilePathResponseInput {
  path?: string;
}

export interface GetCascadeMemoriesRequestInput {
}

export interface GetCascadeMemoriesResponseInput {
  memories?: CortexMemoryInput[];
}

export interface GetCascadeModelConfigDataRequestInput {
}

export interface GetCascadeModelConfigsRequestInput {
  filter?: boolean;
}

export interface GetCascadeModelConfigsResponseInput {
  clientModelConfigs?: ClientModelConfigInput[];
  clientModelSorts?: ClientModelSortInput[];
  defaultOverrideModelConfig?: DefaultOverrideModelConfigInput;
}

export interface GetCascadeNuxesRequestInput {
}

export interface GetCascadeNuxesResponseInput {
  nuxes?: CascadeNUXConfigInput[];
}

export interface GetCascadePluginByIdRequestInput {
  os?: string;
  pluginId?: string;
}

export interface GetCascadePluginByIdResponseInput {
  plugin?: CascadePluginTemplateInput;
}

export interface GetCascadeTrajectoryGeneratorMetadataRequestInput {
  cascadeId?: string;
  generatorMetadataOffset?: number;
  includeMessages?: boolean;
}

export interface GetCascadeTrajectoryGeneratorMetadataResponseInput {
  generatorMetadata?: CortexStepGeneratorMetadataInput[];
}

export interface GetCascadeTrajectoryRequestInput {
  cascadeId?: string;
  verbosity?: jetski_cortex_pbClientTrajectoryVerbosity;
  trajectoryVerbosity?: jetski_cortex_pbClientTrajectoryVerbosity;
}

export interface GetCascadeTrajectoryResponseInput {
  trajectory?: TrajectoryInput;
  status?: CascadeRunStatus;
  numTotalSteps?: number;
  numTotalGeneratorMetadata?: number;
}

export interface GetCascadeTrajectoryStepsRequestInput {
  cascadeId?: string;
  stepOffset?: number;
  verbosity?: jetski_cortex_pbClientTrajectoryVerbosity;
  trajectoryVerbosity?: jetski_cortex_pbClientTrajectoryVerbosity;
}

export interface GetCascadeTrajectoryStepsResponseInput {
  steps?: StepInput[];
}

export interface GetChangelogRequestInput {
  version?: string;
}

export interface GetChangelogResponseInput {
  path?: string;
}

export interface GetCodeFrequencyForRepoRequestInput {
  repoUri?: string;
  branch?: string;
  minutesPerBucket?: number;
}

export interface GetCodeFrequencyForRepoResponseInput {
  codeFrequency?: CodeFrequencyRecordInput[];
}

export interface GetCodeValidationStatesRequestInput {
  cascadeId?: string;
}

export interface GetCodeValidationStatesResponseInput {
  states?: ValidationStateInput[];
}

export interface GetCommandModelConfigsRequestInput {
}

export interface GetCommandModelConfigsResponseInput {
  clientModelConfigs?: ClientModelConfigInput[];
}

export interface GetDebugDiagnosticsRequestInput {
}

export interface GetDebugDiagnosticsResponseInput {
  languageServerDiagnostics?: LanguageServerDiagnosticsInput;
}

export interface GetLoadCodeAssistRequestInput {
  forceRefresh?: boolean;
}

export interface GetLoadCodeAssistResponseInput {
  response?: LoadCodeAssistResponseInput;
}

export interface GetMatchingContextScopeItemsRequestInput {
  allowedTypes?: ContextScopeType[];
  allowedContextTypes?: CodeContextType[];
  query?: string;
  fuzzyMatch?: boolean;
  maxItems?: number;
  caseInsensitive?: boolean;
  repoFilter?: string;
  cancelToken?: bigint;
}

export interface GetMatchingContextScopeItemsResponseInput {
  items?: ContextScopeItemInput[];
}

export interface GetMcpPromptRequest_ArgumentsEntryInput {
  key?: string;
  value?: string;
}

export interface GetMcpPromptRequestInput {
  serverName?: string;
  name?: string;
  arguments?: GetMcpPromptRequest_ArgumentsEntryInput[];
}

export interface GetMcpPromptResponseInput {
  description?: string;
  messages?: McpPromptMessageInput[];
}

export interface GetMcpServerStatesRequestInput {
}

export interface GetMcpServerStatesResponseInput {
  states?: McpServerStateInput[];
  isLoading?: boolean;
}

export interface GetMcpServerTemplatesRequestInput {
}

export interface GetMcpServerTemplatesResponseInput {
  templates?: McpServerTemplateInput[];
}

export interface GetModelResponseRequestInput {
  prompt?: string;
  model?: Model;
}

export interface GetModelResponseResponseInput {
  response?: string;
}

export interface GetModelStatusesRequestInput {
}

export interface GetModelStatusesResponseInput {
  modelStatusInfos?: ModelStatusInfoInput[];
}

export interface GetPatchAndCodeChangeRequestInput {
  intent?: string;
  baseStateRepoInfo?: GitRepoInfoInput;
  repoPath?: string;
}

export interface GetPatchAndCodeChangeResponseInput {
  patchString?: string;
  codeChangeWithContext?: CodeChangeWithContextInput;
}

export interface GetProfileDataRequestInput {
  apiKey?: string;
}

export interface GetProfileDataResponseInput {
  profilePictureUrl?: string;
}

export interface GetRepoInfosRequestInput {
  repoUris?: string[];
}

export interface GetRepoInfosResponseInput {
  repos?: RepoInfoInput[];
}

export interface GetRevertPreviewRequestInput {
  cascadeId?: string;
  stepIndex?: number;
  overrideConfig?: CascadeConfigInput;
}

export interface GetRevertPreviewResponseInput {
  codeEditPreviews?: CodeEditRevertPreviewInput[];
}

export interface GetRevisionArtifactRequestInput {
  repoPathUri?: string;
  baseCommit?: string;
}

export interface GetRevisionArtifactResponseInput {
  stats?: PatchStatsInput;
  patch?: string;
}

export interface GetSidecarEventsRequestInput {
  sidecarId?: string;
}

export interface GetSidecarEventsResponseInput {
  events?: SidecarEventInput[];
}

export interface GetSidecarsRequestInput {
}

export interface GetSidecarsResponseInput {
  sidecars?: SidecarStatusInfoInput[];
}

export interface GetSkillMarketplaceLinkRequestInput {
  skillPath?: string;
}

export interface GetSkillMarketplaceLinkResponseInput {
  marketplaceUrl?: string;
}

export interface GetStaticExperimentStatusRequestInput {
}

export interface GetStaticExperimentStatusResponseInput {
  status?: ChatExperimentStatusInput[];
}

export interface GetStatusRequestInput {
}

export interface GetStatusResponseInput {
  status?: StatusInput;
}

export interface GetTeamOrganizationalControlsRequestInput {
}

export interface GetTeamOrganizationalControlsResponseInput {
  controls?: TeamOrganizationalControlsInput;
}

export interface GetTermsOfServiceRequestInput {
}

export interface GetTermsOfServiceResponseInput {
  termsOfServiceText?: string;
  version?: string;
}

export interface GetTokenBaseRequestInput {
  cascadeConfig?: CascadeConfigInput;
  workspaceUris?: string[];
}

export interface GetTokenBaseResponseInput {
  customizationTokenBase?: TokenBreakdownInput;
  remainingBudget?: number;
  customizationBudget?: number;
  tokenBase?: TokenBreakdownInput;
  maxTokenBase?: number;
}

export interface GetTranscriptionRequestInput {
  audioData?: Uint8Array;
}

export interface GetTranscriptionResponseInput {
  transcribedText?: string;
}

export interface GetUnleashDataRequest_PropertiesEntryInput {
  key?: string;
  value?: string;
}

export interface GetUnleashDataRequestInput {
  properties?: GetUnleashDataRequest_PropertiesEntryInput[];
}

export interface GetUnleashDataResponseInput {
  context?: UnleashContextInput;
  experimentConfig?: ExperimentConfigInput;
}

export interface GetUserAnalyticsSummaryRequestInput {
  timeZone?: string;
  startTimestamp?: TimestampInput;
  endTimestamp?: TimestampInput;
}

export interface GetUserAnalyticsSummaryResponseInput {
  completionStatistics?: CompletionStatisticsInput;
  completionsByDay?: CompletionByDateEntryInput[];
  completionsByLanguage?: CompletionByLanguageEntryInput[];
  chatsByModel?: ChatStatsByModelEntryInput[];
}

export interface GetUserMemoriesRequestInput {
}

export interface GetUserMemoriesResponseInput {
  memories?: CortexMemoryInput[];
}

export interface GetUserSettingsRequestInput {
}

export interface GetUserSettingsResponseInput {
  userSettings?: UserSettingsInput;
}

export interface GetUserStatusRequestInput {
}

export interface GetUserStatusResponseInput {
  userStatus?: UserStatusInput;
  planInfo?: PlanInfoInput;
}

export interface GetUserTrajectoryDebugRequestInput {
  includeAllTrajectories?: boolean;
}

export interface GetUserTrajectoryDebugResponseInput {
  mainline?: ImplicitTrajectoryInput[];
  granular?: TrajectoryInput;
  supercomplete?: SupercompletePromptTrajectoryInput;
}

export interface GetUserTrajectoryDescriptionsRequestInput {
}

export interface GetUserTrajectoryDescriptionsResponseInput {
  trajectories?: ImplicitTrajectoryDescriptionInput[];
}

export interface GetUserTrajectoryRequestInput {
  trajectoryId?: string;
}

export interface GetUserTrajectoryResponseInput {
  trajectory?: TrajectoryInput;
}

export interface GetWebDocsOptionsRequestInput {
}

export interface GetWebDocsOptionsResponseInput {
  options?: WebDocsOptionInput[];
}

export interface GetWorkingDirectoriesRequestInput {
}

export interface GetWorkingDirectoriesResponseInput {
  directories?: WorkingDirectoryInfoInput[];
}

export interface GetWorkspaceEditStateRequestInput {
}

export interface GetWorkspaceEditStateResponseInput {
  workspaceEdits?: WorkspaceEditStateInput[];
}

export interface GetWorkspaceInfosRequestInput {
}

export interface GetWorkspaceInfosResponseInput {
  homeDirPath?: string;
  workspaceInfos?: WorkspaceInfoInput[];
  homeDirUri?: string;
}

export interface GetWorktreeDiffRequestInput {
  worktreeDirUri?: string;
  targetWorkspaceUri?: string;
}

export interface GetWorktreeDiffResponseInput {
  diffPatch?: string;
  summary?: CheckoutSummaryInput;
}

export interface HandleCascadeUserInteractionRequestInput {
  cascadeId?: string;
  interaction?: CascadeUserInteractionInput;
}

export interface HandleCascadeUserInteractionResponseInput {
}

export interface HandleScreenRecordingRequestInput {
  cascadeId?: string;
}

export interface HandleScreenRecordingResponseInput {
  videoData?: Uint8Array;
}

export interface HeartbeatRequestInput {
  previousErrorTraces?: ErrorTraceInput[];
  experimentConfig?: ExperimentConfigInput;
}

export interface HeartbeatResponseInput {
  lastExtensionHeartbeat?: TimestampInput;
}

export interface ImportFromCursorRequestInput {
  sourcePath?: string;
}

export interface ImportFromCursorResponseInput {
  copiedFiles?: string[];
  duplicateFiles?: string[];
  problemFiles?: string[];
}

export interface InitializeCascadePanelStateRequestInput {
  userStatus?: UserStatusInput;
}

export interface InitializeCascadePanelStateResponseInput {
}

export interface InstallCascadePluginRequestInput {
  pluginId?: string;
}

export interface InstallCascadePluginResponseInput {
  installationCount?: bigint;
}

export interface JetboxDeleteSummaryRequestInput {
  cascadeId?: string;
}

export interface JetboxDeleteSummaryResponseInput {
}

export interface JetboxGetLatestVersionRequestInput {
}

export interface JetboxGetLatestVersionResponseInput {
  latestVersion?: string;
}

export interface JetboxWriteStateRequestInput {
  state?: StateInput;
}

export interface JetboxWriteStateResponseInput {
}

export interface JetboxWriteSummaryRequestInput {
  cascadeId?: string;
  summary?: CascadeTrajectorySummaryInput;
}

export interface JetboxWriteSummaryResponseInput {
}

export interface LatencyInfoInput {
  clientLatencyMs?: bigint;
  promptLatencyMs?: bigint;
  promptStageLatencies?: PromptStageLatencyInput[];
  debounceLatencyMs?: bigint;
  rpcLatencyMs?: bigint;
  networkLatencyMs?: bigint;
}

export interface ListCustomizationPathsByFileRequestInput {
  type?: RefreshCustomizationType;
  isGlobal?: boolean;
}

export interface ListCustomizationPathsByFileResponse_PathsFilesEntryInput {
  key?: string;
  value?: CustomizationPathsListInput;
}

export interface ListCustomizationPathsByFileResponseInput {
  pathsFiles?: ListCustomizationPathsByFileResponse_PathsFilesEntryInput[];
}

export interface ListMcpPromptsRequestInput {
}

export interface ListMcpPromptsResponseInput {
  prompts?: McpPromptSpecInput[];
}

export interface ListMcpResourcesRequestInput {
  serverName?: string;
  query?: string;
}

export interface ListMcpResourcesResponseInput {
  resources?: McpResourceItemInput[];
}

export interface ListPagesRequestInput {
}

export interface ListPagesResponseInput {
  pages?: BrowserPageMetadataInput[];
}

export interface LoadReplayConversationRequestInput {
  workspaceName?: string;
  user?: string;
  cascadeId?: string;
}

export interface LoadReplayConversationResponseInput {
}

export interface LoadTrajectoryRequestInput {
  cascadeId?: string;
}

export interface LoadTrajectoryResponseInput {
}

export interface ManageSidecarRequestInput {
  sidecarId?: string;
  action?: SidecarAction;
}

export interface ManageSidecarResponseInput {
}

export interface MigrateApiKeyRequestInput {
  apiKey?: string;
}

export interface MigrateApiKeyResponseInput {
  sessionToken?: string;
}

export interface OpenUrlRequestInput {
  url?: string;
}

export interface OpenUrlResponseInput {
}

export interface PatchStatsInput {
  numFilesChanged?: number;
  numLineAdditions?: number;
  numLineDeletions?: number;
}

export interface PluginInput {
  name?: string;
  path?: string;
  isGlobal?: boolean;
  skills?: WorkflowSpecInput[];
  agents?: AgentCustomizationInput[];
  mcpServers?: McpServerSpecInput[];
}

export interface ProvideCompletionFeedbackRequestInput {
  isAccepted?: boolean;
  feedbackDelayMs?: bigint;
  completionId?: string;
  promptId?: string;
  latencyInfo?: LatencyInfoInput;
  source?: ProviderSource;
  document?: DocumentInput;
  viewColumnsOpen?: bigint;
  isIntentionalReject?: boolean;
  isPartial?: boolean;
  midstreamAutocompleteText?: string;
  hasActiveVimExtension?: boolean;
  traceId?: string;
  acceptedLines?: bigint;
  removedLines?: bigint;
  experimentConfig?: ExperimentConfigInput;
}

export interface ProvideCompletionFeedbackResponseInput {
}

export interface ReadDirEntryInput {
  uri?: string;
  fileType?: FileType;
}

export interface ReadDirRequestInput {
  uri?: string;
}

export interface ReadDirResponseInput {
  entries?: ReadDirEntryInput[];
}

export interface ReadFileRequestInput {
  uri?: string;
}

export interface ReadFileResponseInput {
  content?: Uint8Array;
  language?: Language;
}

export interface ReconnectExtensionServerRequestInput {
  extensionServerPort?: number;
  extensionServerCsrfToken?: string;
}

export interface ReconnectExtensionServerResponseInput {
}

export interface RecordAnalyticsEventRequest_ExperimentsEntryInput {
  key?: string;
  value?: boolean;
}

export interface RecordAnalyticsEventRequest_ExtraEntryInput {
  key?: string;
  value?: string;
}

export interface RecordAnalyticsEventRequestInput {
  eventName?: string;
  extra?: RecordAnalyticsEventRequest_ExtraEntryInput[];
  experiments?: RecordAnalyticsEventRequest_ExperimentsEntryInput[];
}

export interface RecordAnalyticsEventResponseInput {
}

export interface RecordChatFeedbackRequestInput {
  messageId?: string;
  feedback?: ChatFeedbackType;
  reason?: string;
  timestamp?: TimestampInput;
}

export interface RecordChatFeedbackResponseInput {
}

export interface RecordChatPanelSessionRequestInput {
  startTimestamp?: TimestampInput;
  endTimestamp?: TimestampInput;
}

export interface RecordChatPanelSessionResponseInput {
}

export interface RecordCommitMessageSaveRequestInput {
  repoRoot?: string;
  branchName?: string;
  commitHash?: string;
  commitMessage?: string;
  commitTimestamp?: TimestampInput;
  parentCommitHash?: string;
  authorName?: string;
  authorEmail?: string;
}

export interface RecordCommitMessageSaveResponseInput {
}

export interface RecordErrorRequestInput {
  errorTrace?: ErrorTraceInput;
  shouldUploadImmediately?: boolean;
}

export interface RecordErrorResponseInput {
}

export interface RecordEventRequestInput {
  event?: EventInput;
}

export interface RecordEventResponseInput {
}

export interface RecordInteractiveCascadeFeedbackRequestInput {
  cascadeId?: string;
  stepIndex?: number;
  chunkIndex?: number;
  acknowledgementType?: AcknowledgementType;
}

export interface RecordInteractiveCascadeFeedbackResponseInput {
}

export interface RecordLintsRequestInput {
  currentLanguage?: Language;
  lints?: CodeDiagnosticInput[];
  timestamp?: TimestampInput;
}

export interface RecordLintsResponseInput {
}

export interface RecordObservabilityDataRequest_ExtraEntryInput {
  key?: string;
  value?: string;
}

export interface RecordObservabilityDataRequest_SensitiveDataEntryInput {
  key?: string;
  value?: string;
}

export interface RecordObservabilityDataRequestInput {
  datatype?: string;
  extra?: RecordObservabilityDataRequest_ExtraEntryInput[];
  sensitiveData?: RecordObservabilityDataRequest_SensitiveDataEntryInput[];
}

export interface RecordObservabilityDataResponseInput {
}

export interface RecordSearchDocOpenRequestInput {
  resultId?: string;
}

export interface RecordSearchDocOpenResponseInput {
}

export interface RecordSearchResultsViewRequestInput {
  clusterSearchId?: string;
  exactSearchId?: string;
  searchResultIds?: string[];
}

export interface RecordSearchResultsViewResponseInput {
}

export interface RecordSidecarEventRequestInput {
  sidecarId?: string;
  payload?: SidecarEventPayloadInput;
  error?: string;
}

export interface RecordSidecarEventResponseInput {
}

export interface RecordUserGrepRequestInput {
  query?: string;
  results?: GrepSearchResultInput[];
  timestamp?: TimestampInput;
}

export interface RecordUserGrepResponseInput {
}

export interface RecordUserStepSnapshotRequestInput {
  cascadeId?: string;
  stepIndex?: number;
  snapshot?: UserStepSnapshotInput;
}

export interface RecordUserStepSnapshotResponseInput {
}

export interface RefreshContextForIdeActionRequestInput {
  activeDocument?: DocumentInput;
  openDocumentFilepathsMigrateMeToUri?: string[];
  openDocumentUris?: string[];
  otherDocuments?: DocumentInput[];
  workspacePathsMigrateMeToUri?: string[];
  workspaceUris?: string[];
  blocking?: boolean;
  experimentConfig?: ExperimentConfigInput;
  ideAction?: IdeAction;
}

export interface RefreshContextForIdeActionResponseInput {
}

export interface RefreshMcpServersRequestInput {
  shallow?: boolean;
  serverName?: string;
}

export interface RefreshMcpServersResponseInput {
}

export interface RegisterGdmUserRequestInput {
}

export interface RegisterGdmUserResponseInput {
  created?: boolean;
  name?: string;
  email?: string;
  apiKey?: string;
}

export interface RemoveTrackedWorkspaceRequestInput {
  workspace?: string;
  isPassiveWorkspace?: boolean;
}

export interface RemoveTrackedWorkspaceResponseInput {
}

export interface ReplayGroundTruthTrajectoryRequestInput {
  replaySteps?: StepInput[];
  cascadeId?: string;
  cascadeConfig?: CascadeConfigInput;
}

export interface ReplayGroundTruthTrajectoryResponseInput {
  trajectory?: TrajectoryInput;
}

export interface RepoInfoInput {
  name?: string;
  repoPath?: string;
  branches?: BranchInfoInput[];
  scmType?: ScmType;
}

export interface ResetOnboardingRequestInput {
  clearHistory?: boolean;
}

export interface ResetOnboardingResponseInput {
}

export interface ResolveOutstandingStepsRequestInput {
  cascadeId?: string;
}

export interface ResolveOutstandingStepsResponseInput {
}

export interface RestartRequestInput {
}

export interface RestartResponseInput {
}

export interface RevertToCascadeStepRequestInput {
  cascadeId?: string;
  stepIndex?: number;
  experimentConfig?: ExperimentConfigInput;
  overrideConfig?: CascadeConfigInput;
}

export interface RevertToCascadeStepResponseInput {
}

export interface RunCommandRequestInput {
  command?: string;
  args?: string[];
  cwd?: string;
  timeoutMs?: bigint;
}

export interface RunCommandResponseInput {
  stdout?: string;
  stderr?: string;
  exitCode?: number;
  timedOut?: boolean;
}

export interface SaveAgentScriptCommandSpecRequestInput {
  name?: string;
  saveToWorkspace?: boolean;
  overwrite?: boolean;
  commandSpec?: AgentScriptCommandSpecInput;
}

export interface SaveAgentScriptCommandSpecResponseInput {
  created?: boolean;
  agentScript?: AgentScriptItemInput;
}

export interface SaveMediaAsArtifactRequestInput {
  media?: MediaInput;
}

export interface SaveMediaAsArtifactResponseInput {
  uri?: string;
}

export interface SaveScreenRecordingRequestInput {
  videoData?: Uint8Array;
  filename?: string;
  cascadeId?: string;
}

export interface SaveScreenRecordingResponseInput {
  filePath?: string;
}

export interface ScanSkillsConfigFileRequestInput {
  configFilePath?: string;
  workspaceUri?: string;
}

export interface ScanSkillsConfigFileResponseInput {
  skills?: WorkflowSpecInput[];
}

export interface SearchCodeRequestInput {
  query?: string;
  workspaceUri?: string;
  maxResults?: number;
  linesContext?: number;
  cancelToken?: bigint;
}

export interface SearchCodeResponseInput {
  results?: SearchCodeResultInput[];
}

export interface SearchCodeResult_WorkspaceUrisToRelativePathsEntryInput {
  key?: string;
  value?: string;
}

export interface SearchCodeResultInput {
  absoluteUri?: string;
  workspaceUrisToRelativePaths?: SearchCodeResult_WorkspaceUrisToRelativePathsEntryInput[];
  lineNumber?: number;
  snippet?: string;
  matchStartCol?: number;
  matchEndCol?: number;
}

export interface SearchConversationsRequestInput {
  query?: string;
  limit?: number;
}

export interface SearchConversationsResponseInput {
  results?: ConversationSearchResultInput[];
}

export interface SearchFilesRequestInput {
  query?: string;
  workspaceUri?: string;
  maxResults?: number;
  includeDirectories?: boolean;
  cancelToken?: bigint;
}

export interface SearchFilesResponseInput {
  results?: PathScopeItemInput[];
}

export interface SendActionToChatPanelRequestInput {
  actionType?: string;
  payload?: Uint8Array[];
}

export interface SendActionToChatPanelResponseInput {
}

export interface SendAgentMessageRequestInput {
  content?: string;
  recipient?: string;
  senderId?: string;
  sourceMetadata?: SourceMetadataInput;
}

export interface SendAgentMessageResponseInput {
}

export interface SendAllQueuedMessagesRequestInput {
  cascadeId?: string;
  cascadeConfig?: CascadeConfigInput;
}

export interface SendAllQueuedMessagesResponseInput {
}

export interface SendAudioChunkRequestInput {
  sessionId?: string;
  data?: Uint8Array;
  sequenceNumber?: number;
}

export interface SendAudioChunkResponseInput {
}

export interface SendStepsToBackgroundRequestInput {
  conversationId?: string;
  stepIndices?: number[];
}

export interface SendStepsToBackgroundResponseInput {
}

export interface SendUserCascadeMessageRequestInput {
  cascadeId?: string;
  items?: TextOrScopeItemInput[];
  images?: ImageDataInput[];
  artifactComments?: ArtifactCommentInput[];
  fileDiffComments?: FileDiffCommentInput[];
  fileComments?: FileCommentInput[];
  media?: MediaInput[];
  cascadeConfig?: CascadeConfigInput;
  customAgentSpec?: CustomAgentSpecInput;
  experimentConfig?: ExperimentConfigInput;
  blocking?: boolean;
  additionalSteps?: StepInput[];
  clientType?: ChatClientRequestStreamClientType;
  propagateError?: boolean;
  plannerResponse?: CortexStepPlannerResponseInput;
  messageOrigin?: AgentMessageOrigin;
}

export interface SendUserCascadeMessageResponseInput {
}

export interface SetBaseExperimentsRequestInput {
  experimentConfig?: ExperimentConfigInput;
}

export interface SetBaseExperimentsResponseInput {
}

export interface SetBrowserOpenConversationRequestInput {
  cascadeId?: string;
  expiresAt?: TimestampInput;
}

export interface SetBrowserOpenConversationResponseInput {
}

export interface SetCloudCodeURLRequestInput {
  url?: string;
}

export interface SetCloudCodeURLResponseInput {
}

export interface SetOrVerifyStaticConfigRequestInput {
  cascadeId?: string;
  customAgentSpec?: CustomAgentSpecInput;
}

export interface SetOrVerifyStaticConfigResponseInput {
}

export interface SetupUniversitySandboxRequestInput {
}

export interface SetupUniversitySandboxResponseInput {
  baseDirectory?: string;
}

export interface SetUserInfoRequestInput {
  userSettings?: V1internalUserSettingsInput;
}

export interface SetUserInfoResponseInput {
  userSettings?: V1internalUserSettingsInput;
}

export interface SetUserSettingsRequestInput {
  userSettings?: UserSettingsInput;
}

export interface SetUserSettingsResponseInput {
  userSettings?: UserSettingsInput;
}

export interface SetWorkingDirectoriesRequestInput {
  directoryUris?: string[];
}

export interface SetWorkingDirectoriesResponseInput {
}

export interface ShouldEnableUnleashRequestInput {
}

export interface ShouldEnableUnleashResponseInput {
  shouldEnable?: boolean;
}

export interface SignalExecutableIdleRequestInput {
  conversationId?: string;
}

export interface SignalExecutableIdleResponseInput {
}

export interface SimulateSegFaultRequestInput {
}

export interface SimulateSegFaultResponseInput {
}

export interface SkipBrowserSubagentRequestInput {
  cascadeId?: string;
  stepIndex?: number;
}

export interface SkipBrowserSubagentResponseInput {
}

export interface SkipOnboardingRequestInput {
}

export interface SkipOnboardingResponseInput {
}

export interface SmartFocusConversationRequestInput {
  cascadeId?: string;
}

export interface SmartFocusConversationResponseInput {
}

export interface SmartOpenBrowserRequestInput {
  url?: string;
  isOnboarded?: boolean;
}

export interface SmartOpenBrowserResponseInput {
}

export interface StartBattleModeRequestInput {
  request?: SendUserCascadeMessageRequestInput;
}

export interface StartBattleModeResponseInput {
  childrenConversationIds?: string[];
}

export interface StartCascadeRequestInput {
  baseTrajectoryIdentifier?: BaseTrajectoryIdentifierInput;
  sourceMetadata?: SourceMetadataInput;
  source?: CortexTrajectorySource;
  trajectoryType?: CortexTrajectoryType;
  agentScriptItem?: AgentScriptItemInput;
  cascadeId?: string;
  workspaceUris?: string[];
  overrideWorkspaceUris?: string[];
  parentConversationId?: string;
  customAgentSpec?: CustomAgentSpecInput;
  experimentConfig?: ExperimentConfigInput;
}

export interface StartCascadeResponseInput {
  cascadeId?: string;
}

export interface StartScreenRecordingRequestInput {
  cascadeId?: string;
  onboarded?: boolean;
}

export interface StartScreenRecordingResponseInput {
}

export interface StatUriRequestInput {
  uri?: string;
}

export interface StatUriResponseInput {
  fileType?: FileType;
  modTime?: TimestampInput;
  normalizedUri?: string;
}

export interface StringMatchRangeInput {
  startOffset?: number;
  endOffsetExclusive?: number;
}

export interface SupercompletePromptTrajectoryInput {
  trajectory?: TrajectoryInput;
  includedSteps?: number[];
}

export interface UpdateCascadeMemoryRequestInput {
  memoryId?: string;
  title?: string;
  content?: string;
  tags?: string[];
}

export interface UpdateCascadeMemoryResponseInput {
}

export interface UpdateConversationAnnotationsRequestInput {
  cascadeId?: string;
  annotations?: ConversationAnnotationsInput;
  mergeAnnotations?: boolean;
}

export interface UpdateConversationAnnotationsResponseInput {
}

export interface UpdateCustomizationPathsFileRequestInput {
  filePath?: string;
  paths?: string[];
  operation?: CustomizationPathsOperation;
}

export interface UpdateCustomizationPathsFileResponseInput {
}

export interface UpdateCustomizationRequestInput {
  path?: string;
  operation?: CustomizationPathsOperation;
  agent?: AgentScriptItemInput;
  plugin?: PluginItemInput;
}

export interface UpdateCustomizationResponseInput {
}

export interface UpdateDevExperimentsRequestInput {
  experimentConfig?: ExperimentConfigInput;
}

export interface UpdateDevExperimentsResponseInput {
}

export interface UpdateEnterpriseExperimentsFromUrlRequestInput {
  portalUrl?: string;
}

export interface UpdateEnterpriseExperimentsFromUrlResponseInput {
  success?: boolean;
  errorMessage?: string;
  experimentConfig?: ExperimentConfigInput;
}

export interface UpdatePRForWorktreeRequestInput {
  worktreeFsPath?: string;
  commitMessage?: string;
  title?: string;
  body?: string;
}

export interface UpdatePRForWorktreeResponseInput {
  prUrl?: string;
}

export interface ValidationStateInput {
  uri?: string;
  lastAcknowledgedState?: string;
  currentState?: string;
  lastStateFileNonexistent?: boolean;
}

export interface WellSupportedLanguagesRequestInput {
}

export interface WellSupportedLanguagesResponseInput {
  languages?: Language[];
}

export interface WorkspaceEditStateInput {
  repoRoot?: string;
  numAdditions?: bigint;
  numDeletions?: bigint;
  edits?: ActionResultEditInput[];
}

export interface WorkspaceInfoInput {
  workspaceUri?: string;
  gitRootUri?: string;
}

export interface WriteFileRequestInput {
  uri?: string;
  content?: Uint8Array;
  overwrite?: boolean;
}

export interface WriteFileResponseInput {
}
