// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { CacheControlType } from "../../../gen/exa/chat_pb/chat_pb.js";
import { ChatMessageSource, ExperimentKey } from "../../../gen/exa/codeium_common_pb/codeium_common_pb.js";
import { ChatToolCallInput, ImageDataInput, MediaInput, PromptAnnotationRangeInput } from "../codeium_common_pb/codeium_common_pb.js";

export interface ChatExperimentStatusInput {
  experimentKey?: ExperimentKey;
  enabled?: boolean;
}

export interface ChatMessagePromptInput {
  messageId?: string;
  source?: ChatMessageSource;
  prompt?: string;
  numTokens?: number;
  safeForCodeTelemetry?: boolean;
  toolCalls?: ChatToolCallInput[];
  toolCallId?: string;
  promptCacheOptions?: PromptCacheOptionsInput;
  toolResultIsError?: boolean;
  images?: ImageDataInput[];
  media?: MediaInput[];
  thinking?: string;
  rawThinking?: string;
  signature?: string;
  thinkingSignature?: Uint8Array;
  thinkingRedacted?: boolean;
  promptAnnotationRanges?: PromptAnnotationRangeInput[];
  stepIdx?: number;
  providerAssignedMessageId?: string;
}

export interface ChatToolChoiceInput {
  optionName?: string;
  toolName?: string;
}

export interface ChatToolDefinitionInput {
  name?: string;
  description?: string;
  jsonSchemaString?: string;
  strict?: boolean;
  attributionFieldNames?: string[];
  serverName?: string;
}

export interface PromptCacheOptionsInput {
  type?: CacheControlType;
}
