// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { UnifiedDiffLineType } from "../../../gen/exa/diff_action_pb/diff_action_pb.js";

export interface DiffBlockInput {
  startLine?: number;
  endLine?: number;
  unifiedDiff?: UnifiedDiffInput;
}

export interface DiffListInput {
  diffs?: DiffBlockInput[];
}

export interface UnifiedDiff_UnifiedDiffLineInput {
  text?: string;
  type?: UnifiedDiffLineType;
}

export interface UnifiedDiffInput {
  lines?: UnifiedDiff_UnifiedDiffLineInput[];
}
