// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { CascadeRunStatus } from "../../../gen/exa/cortex_pb/cortex_pb.js";
import { TimestampInput } from "../../google/protobuf/timestamp_pb.js";
import { CortexTrajectoryMetadataInput, CortexWorkspaceMetadataInput, TrajectoryScopeInput } from "../cortex_pb/cortex_pb.js";
import { StepInput, TrajectoryInput } from "../gemini_coder/proto/trajectory_pb.js";

export interface AgentStatePageUpdateRequestInput {
  conversationId?: string;
  subscriberId?: string;
  stepPageBounds?: SliceInput;
  generatorMetadatasPageBounds?: SliceInput;
  executorMetadatasPageBounds?: SliceInput;
}

export interface AgentStatePageUpdateResponseInput {
}

export interface BaseTrajectoryIdentifierInput {
  cascadeId?: string;
  implicitTrajectoryFileUri?: string;
  lastActiveDoc?: boolean;
  trajectory?: TrajectoryInput;
  forkFrom?: ForkFromIdentifierInput;
}

export interface CascadeTrajectorySummaryInput {
  summary?: string;
  stepCount?: number;
  lastModifiedTime?: TimestampInput;
  trajectoryId?: string;
  status?: CascadeRunStatus;
  createdTime?: TimestampInput;
  waitingSteps?: CortexTrajectoryStepWithIndexInput[];
  workspaces?: CortexWorkspaceMetadataInput[];
  lastUserInputTime?: TimestampInput;
  lastUserInputStepIndex?: number;
  latestNotifyUserStep?: CortexTrajectoryStepWithIndexInput;
  latestTaskBoundaryStep?: CortexTrajectoryStepWithIndexInput;
  annotations?: ConversationAnnotationsInput;
  trajectoryMetadata?: CortexTrajectoryMetadataInput;
  hasActiveChildren?: boolean;
}

export interface ConversationAnnotationsInput {
  title?: string;
  tags?: string[];
  archived?: boolean;
  archivalStatusTimestamp?: TimestampInput;
  starred?: boolean;
  lastUserViewTime?: TimestampInput;
  markedAsUnread?: boolean;
  groupId?: string;
  groupIndex?: number;
  groupDescription?: string;
  pinned?: boolean;
}

export interface CortexTrajectoryStepWithIndexInput {
  step?: StepInput;
  stepIndex?: number;
}

export interface ForkFromIdentifierInput {
  cascadeId?: string;
  stepIndex?: number;
}

export interface ImplicitTrajectoryInput {
  trajectory?: TrajectoryInput;
  trajectoryScope?: TrajectoryScopeInput;
}

export interface SliceInput {
  startIndex?: number;
  endIndexExclusive?: number;
}
