// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { ArtifactReviewMode, CascadeCommandsAutoExecution, Model, PlanningMode } from "../../../gen/exa/codeium_common_pb/codeium_common_pb.js";
import { PostOnboardingStepType, ThemeMode } from "../../../gen/exa/jetbox_state_pb/jetbox_state_pb.js";
import { ModelInfoInput, PermissionGrantsConfigInput } from "../codeium_common_pb/codeium_common_pb.js";

export interface CustomModelsConfig_CustomModelsEntryInput {
  key?: string;
  value?: ModelInfoInput;
}

export interface CustomModelsConfigInput {
  customModels?: CustomModelsConfig_CustomModelsEntryInput[];
}

export interface Jetbox_stateUserSettingsInput {
  autoExecutionPolicy?: CascadeCommandsAutoExecution;
  artifactReviewMode?: ArtifactReviewMode;
  allowAgentAccessNonWorkspaceFiles?: boolean;
  allowedCommands?: string[];
  deniedCommands?: string[];
  planningMode?: PlanningMode;
  secureModeEnabled?: boolean;
  allowCascadeAccessGitignoreFiles?: boolean;
  enableTerminalSandbox?: boolean;
  disableDefaultCustomizations?: boolean;
  globalPermissionGrants?: PermissionGrantsConfigInput;
}

export interface PostOnboardingStateInput {
  completedSteps?: PostOnboardingStepType[];
}

export interface SidebarWorkspaceInfoInput {
  isCollapsed?: boolean;
  isHidden?: boolean;
}

export interface State_SidebarWorkspacesEntryInput {
  key?: string;
  value?: SidebarWorkspaceInfoInput;
}

export interface StateInput {
  postOnboarding?: PostOnboardingStateInput;
  userSettings?: Jetbox_stateUserSettingsInput;
  sidebarWorkspaces?: State_SidebarWorkspacesEntryInput[];
  lastSelectedAgentModel?: Model;
  customModelsConfig?: CustomModelsConfigInput;
  seenNuxUids?: number[];
  themeMode?: ThemeMode;
}
