// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { IntentType, RelevanceReason } from "../../../../gen/exa/code_edit/code_edit_pb/code_edit_pb.js";
import { CodeContextItemInput, GitRepoInfoInput } from "../../codeium_common_pb/codeium_common_pb.js";
import { IndexStatsInput } from "../../index_pb/index_pb.js";

export interface CodeChangeWithContextInput {
  repository?: GitRepoInfoInput;
  fileChanges?: FileChangeInput[];
  testFileChanges?: FileChangeInput[];
  intent?: string;
  indexStats?: IndexStatsInput;
  unrelatedCcis?: CodeContextItemInput[];
  syntheticIntents?: IntentInput[];
  gitCommit?: GitCommitInput;
}

export interface CodeContextItemChange_DescriptionByTypeEntryInput {
  key?: string;
  value?: string;
}

export interface CodeContextItemChangeInput {
  startCci?: CodeContextItemInput;
  endCci?: CodeContextItemInput;
  relevantCodeContexts?: RelevantCodeContextInput[];
  descriptionByType?: CodeContextItemChange_DescriptionByTypeEntryInput[];
  intentRelevance?: IntentRelevanceInput[];
}

export interface FileChangeInput {
  startFilePathMigrateMeToUri?: string;
  startFileUri?: string;
  startFileRelPath?: string;
  endFilePathMigrateMeToUri?: string;
  endFileUri?: string;
  endFileRelPath?: string;
  oldFileContent?: string;
  newFileContent?: string;
  codeContextItemChanges?: CodeContextItemChangeInput[];
  unchangedCodeContextItems?: CodeContextItemInput[];
}

export interface GitCommitInput {
  commitHash?: string;
  parentCommitHash?: string;
}

export interface IntentInput {
  intent?: string;
  intentType?: IntentType;
  includeTestFiles?: boolean;
}

export interface IntentRelevanceInput {
  intent?: string;
  relevanceScore?: number;
  rationale?: string;
}

export interface RelevantCodeContextInput {
  codeContextItem?: CodeContextItemInput;
  relevanceReason?: RelevanceReason;
}
