// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file google/api/client.proto (package google.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3 } from "@bufbuild/protobuf";
import { LaunchStage } from "./launch_stage_pb.js";

/**
 * @generated from enum google.api.ClientLibraryOrganization
 */
export enum ClientLibraryOrganization {
  /**
   * @generated from enum value: CLIENT_LIBRARY_ORGANIZATION_UNSPECIFIED = 0;
   */
  CLIENT_LIBRARY_ORGANIZATION_UNSPECIFIED = 0,

  /**
   * @generated from enum value: CLOUD = 1;
   */
  CLOUD = 1,

  /**
   * @generated from enum value: ADS = 2;
   */
  ADS = 2,

  /**
   * @generated from enum value: PHOTOS = 3;
   */
  PHOTOS = 3,

  /**
   * @generated from enum value: STREET_VIEW = 4;
   */
  STREET_VIEW = 4,

  /**
   * @generated from enum value: SHOPPING = 5;
   */
  SHOPPING = 5,

  /**
   * @generated from enum value: GEO = 6;
   */
  GEO = 6,

  /**
   * @generated from enum value: GENERATIVE_AI = 7;
   */
  GENERATIVE_AI = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(ClientLibraryOrganization)
proto3.util.setEnumType(ClientLibraryOrganization, "google.api.ClientLibraryOrganization", [
  { no: 0, name: "CLIENT_LIBRARY_ORGANIZATION_UNSPECIFIED" },
  { no: 1, name: "CLOUD" },
  { no: 2, name: "ADS" },
  { no: 3, name: "PHOTOS" },
  { no: 4, name: "STREET_VIEW" },
  { no: 5, name: "SHOPPING" },
  { no: 6, name: "GEO" },
  { no: 7, name: "GENERATIVE_AI" },
]);

/**
 * @generated from enum google.api.ClientLibraryDestination
 */
export enum ClientLibraryDestination {
  /**
   * @generated from enum value: CLIENT_LIBRARY_DESTINATION_UNSPECIFIED = 0;
   */
  CLIENT_LIBRARY_DESTINATION_UNSPECIFIED = 0,

  /**
   * @generated from enum value: GITHUB = 10;
   */
  GITHUB = 10,

  /**
   * @generated from enum value: PACKAGE_MANAGER = 20;
   */
  PACKAGE_MANAGER = 20,
}
// Retrieve enum metadata with: proto3.getEnumType(ClientLibraryDestination)
proto3.util.setEnumType(ClientLibraryDestination, "google.api.ClientLibraryDestination", [
  { no: 0, name: "CLIENT_LIBRARY_DESTINATION_UNSPECIFIED" },
  { no: 10, name: "GITHUB" },
  { no: 20, name: "PACKAGE_MANAGER" },
]);

/**
 * @generated from message google.api.CommonLanguageSettings
 */
export class CommonLanguageSettings extends Message<CommonLanguageSettings> {
  /**
   * @generated from field: string reference_docs_uri = 1;
   */
  referenceDocsUri = "";

  /**
   * @generated from field: repeated google.api.ClientLibraryDestination destinations = 2;
   */
  destinations: ClientLibraryDestination[] = [];

  /**
   * @generated from field: google.api.SelectiveGapicGeneration selective_gapic_generation = 3;
   */
  selectiveGapicGeneration?: SelectiveGapicGeneration;

  constructor(data?: PartialMessage<CommonLanguageSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.CommonLanguageSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reference_docs_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "destinations", kind: "enum", T: proto3.getEnumType(ClientLibraryDestination), repeated: true },
    { no: 3, name: "selective_gapic_generation", kind: "message", T: SelectiveGapicGeneration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CommonLanguageSettings {
    return new CommonLanguageSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CommonLanguageSettings {
    return new CommonLanguageSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CommonLanguageSettings {
    return new CommonLanguageSettings().fromJsonString(jsonString, options);
  }

  static equals(a: CommonLanguageSettings | PlainMessage<CommonLanguageSettings> | undefined, b: CommonLanguageSettings | PlainMessage<CommonLanguageSettings> | undefined): boolean {
    return proto3.util.equals(CommonLanguageSettings, a, b);
  }
}

/**
 * @generated from message google.api.ClientLibrarySettings
 */
export class ClientLibrarySettings extends Message<ClientLibrarySettings> {
  /**
   * @generated from field: string version = 1;
   */
  version = "";

  /**
   * @generated from field: google.api.LaunchStage launch_stage = 2;
   */
  launchStage = LaunchStage.LAUNCH_STAGE_UNSPECIFIED;

  /**
   * @generated from field: bool rest_numeric_enums = 3;
   */
  restNumericEnums = false;

  /**
   * @generated from field: google.api.JavaSettings java_settings = 21;
   */
  javaSettings?: JavaSettings;

  /**
   * @generated from field: google.api.CppSettings cpp_settings = 22;
   */
  cppSettings?: CppSettings;

  /**
   * @generated from field: google.api.PhpSettings php_settings = 23;
   */
  phpSettings?: PhpSettings;

  /**
   * @generated from field: google.api.PythonSettings python_settings = 24;
   */
  pythonSettings?: PythonSettings;

  /**
   * @generated from field: google.api.NodeSettings node_settings = 25;
   */
  nodeSettings?: NodeSettings;

  /**
   * @generated from field: google.api.DotnetSettings dotnet_settings = 26;
   */
  dotnetSettings?: DotnetSettings;

  /**
   * @generated from field: google.api.RubySettings ruby_settings = 27;
   */
  rubySettings?: RubySettings;

  /**
   * @generated from field: google.api.GoSettings go_settings = 28;
   */
  goSettings?: GoSettings;

  constructor(data?: PartialMessage<ClientLibrarySettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.ClientLibrarySettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "launch_stage", kind: "enum", T: proto3.getEnumType(LaunchStage) },
    { no: 3, name: "rest_numeric_enums", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 21, name: "java_settings", kind: "message", T: JavaSettings },
    { no: 22, name: "cpp_settings", kind: "message", T: CppSettings },
    { no: 23, name: "php_settings", kind: "message", T: PhpSettings },
    { no: 24, name: "python_settings", kind: "message", T: PythonSettings },
    { no: 25, name: "node_settings", kind: "message", T: NodeSettings },
    { no: 26, name: "dotnet_settings", kind: "message", T: DotnetSettings },
    { no: 27, name: "ruby_settings", kind: "message", T: RubySettings },
    { no: 28, name: "go_settings", kind: "message", T: GoSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClientLibrarySettings {
    return new ClientLibrarySettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClientLibrarySettings {
    return new ClientLibrarySettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClientLibrarySettings {
    return new ClientLibrarySettings().fromJsonString(jsonString, options);
  }

  static equals(a: ClientLibrarySettings | PlainMessage<ClientLibrarySettings> | undefined, b: ClientLibrarySettings | PlainMessage<ClientLibrarySettings> | undefined): boolean {
    return proto3.util.equals(ClientLibrarySettings, a, b);
  }
}

/**
 * @generated from message google.api.Publishing
 */
export class Publishing extends Message<Publishing> {
  /**
   * @generated from field: repeated google.api.MethodSettings method_settings = 2;
   */
  methodSettings: MethodSettings[] = [];

  /**
   * @generated from field: string new_issue_uri = 101;
   */
  newIssueUri = "";

  /**
   * @generated from field: string documentation_uri = 102;
   */
  documentationUri = "";

  /**
   * @generated from field: string api_short_name = 103;
   */
  apiShortName = "";

  /**
   * @generated from field: string github_label = 104;
   */
  githubLabel = "";

  /**
   * @generated from field: repeated string codeowner_github_teams = 105;
   */
  codeownerGithubTeams: string[] = [];

  /**
   * @generated from field: string doc_tag_prefix = 106;
   */
  docTagPrefix = "";

  /**
   * @generated from field: google.api.ClientLibraryOrganization organization = 107;
   */
  organization = ClientLibraryOrganization.CLIENT_LIBRARY_ORGANIZATION_UNSPECIFIED;

  /**
   * @generated from field: repeated google.api.ClientLibrarySettings library_settings = 109;
   */
  librarySettings: ClientLibrarySettings[] = [];

  /**
   * @generated from field: string proto_reference_documentation_uri = 110;
   */
  protoReferenceDocumentationUri = "";

  /**
   * @generated from field: string rest_reference_documentation_uri = 111;
   */
  restReferenceDocumentationUri = "";

  constructor(data?: PartialMessage<Publishing>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.Publishing";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "method_settings", kind: "message", T: MethodSettings, repeated: true },
    { no: 101, name: "new_issue_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 102, name: "documentation_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 103, name: "api_short_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 104, name: "github_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 105, name: "codeowner_github_teams", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 106, name: "doc_tag_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 107, name: "organization", kind: "enum", T: proto3.getEnumType(ClientLibraryOrganization) },
    { no: 109, name: "library_settings", kind: "message", T: ClientLibrarySettings, repeated: true },
    { no: 110, name: "proto_reference_documentation_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 111, name: "rest_reference_documentation_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Publishing {
    return new Publishing().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Publishing {
    return new Publishing().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Publishing {
    return new Publishing().fromJsonString(jsonString, options);
  }

  static equals(a: Publishing | PlainMessage<Publishing> | undefined, b: Publishing | PlainMessage<Publishing> | undefined): boolean {
    return proto3.util.equals(Publishing, a, b);
  }
}

/**
 * @generated from message google.api.JavaSettings
 */
export class JavaSettings extends Message<JavaSettings> {
  /**
   * @generated from field: string library_package = 1;
   */
  libraryPackage = "";

  /**
   * @generated from field: repeated google.api.JavaSettings.ServiceClassNamesEntry service_class_names = 2;
   */
  serviceClassNames: JavaSettings_ServiceClassNamesEntry[] = [];

  /**
   * @generated from field: google.api.CommonLanguageSettings common = 3;
   */
  common?: CommonLanguageSettings;

  constructor(data?: PartialMessage<JavaSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.JavaSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "library_package", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "service_class_names", kind: "message", T: JavaSettings_ServiceClassNamesEntry, repeated: true },
    { no: 3, name: "common", kind: "message", T: CommonLanguageSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JavaSettings {
    return new JavaSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JavaSettings {
    return new JavaSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JavaSettings {
    return new JavaSettings().fromJsonString(jsonString, options);
  }

  static equals(a: JavaSettings | PlainMessage<JavaSettings> | undefined, b: JavaSettings | PlainMessage<JavaSettings> | undefined): boolean {
    return proto3.util.equals(JavaSettings, a, b);
  }
}

/**
 * @generated from message google.api.JavaSettings.ServiceClassNamesEntry
 */
export class JavaSettings_ServiceClassNamesEntry extends Message<JavaSettings_ServiceClassNamesEntry> {
  /**
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * @generated from field: string value = 2;
   */
  value = "";

  constructor(data?: PartialMessage<JavaSettings_ServiceClassNamesEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.JavaSettings.ServiceClassNamesEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JavaSettings_ServiceClassNamesEntry {
    return new JavaSettings_ServiceClassNamesEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JavaSettings_ServiceClassNamesEntry {
    return new JavaSettings_ServiceClassNamesEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JavaSettings_ServiceClassNamesEntry {
    return new JavaSettings_ServiceClassNamesEntry().fromJsonString(jsonString, options);
  }

  static equals(a: JavaSettings_ServiceClassNamesEntry | PlainMessage<JavaSettings_ServiceClassNamesEntry> | undefined, b: JavaSettings_ServiceClassNamesEntry | PlainMessage<JavaSettings_ServiceClassNamesEntry> | undefined): boolean {
    return proto3.util.equals(JavaSettings_ServiceClassNamesEntry, a, b);
  }
}

/**
 * @generated from message google.api.CppSettings
 */
export class CppSettings extends Message<CppSettings> {
  /**
   * @generated from field: google.api.CommonLanguageSettings common = 1;
   */
  common?: CommonLanguageSettings;

  constructor(data?: PartialMessage<CppSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.CppSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "common", kind: "message", T: CommonLanguageSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CppSettings {
    return new CppSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CppSettings {
    return new CppSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CppSettings {
    return new CppSettings().fromJsonString(jsonString, options);
  }

  static equals(a: CppSettings | PlainMessage<CppSettings> | undefined, b: CppSettings | PlainMessage<CppSettings> | undefined): boolean {
    return proto3.util.equals(CppSettings, a, b);
  }
}

/**
 * @generated from message google.api.PhpSettings
 */
export class PhpSettings extends Message<PhpSettings> {
  /**
   * @generated from field: google.api.CommonLanguageSettings common = 1;
   */
  common?: CommonLanguageSettings;

  constructor(data?: PartialMessage<PhpSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.PhpSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "common", kind: "message", T: CommonLanguageSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PhpSettings {
    return new PhpSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PhpSettings {
    return new PhpSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PhpSettings {
    return new PhpSettings().fromJsonString(jsonString, options);
  }

  static equals(a: PhpSettings | PlainMessage<PhpSettings> | undefined, b: PhpSettings | PlainMessage<PhpSettings> | undefined): boolean {
    return proto3.util.equals(PhpSettings, a, b);
  }
}

/**
 * @generated from message google.api.PythonSettings
 */
export class PythonSettings extends Message<PythonSettings> {
  /**
   * @generated from field: google.api.CommonLanguageSettings common = 1;
   */
  common?: CommonLanguageSettings;

  /**
   * @generated from field: google.api.PythonSettings.ExperimentalFeatures experimental_features = 2;
   */
  experimentalFeatures?: PythonSettings_ExperimentalFeatures;

  constructor(data?: PartialMessage<PythonSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.PythonSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "common", kind: "message", T: CommonLanguageSettings },
    { no: 2, name: "experimental_features", kind: "message", T: PythonSettings_ExperimentalFeatures },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PythonSettings {
    return new PythonSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PythonSettings {
    return new PythonSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PythonSettings {
    return new PythonSettings().fromJsonString(jsonString, options);
  }

  static equals(a: PythonSettings | PlainMessage<PythonSettings> | undefined, b: PythonSettings | PlainMessage<PythonSettings> | undefined): boolean {
    return proto3.util.equals(PythonSettings, a, b);
  }
}

/**
 * @generated from message google.api.PythonSettings.ExperimentalFeatures
 */
export class PythonSettings_ExperimentalFeatures extends Message<PythonSettings_ExperimentalFeatures> {
  /**
   * @generated from field: bool rest_async_io_enabled = 1;
   */
  restAsyncIoEnabled = false;

  /**
   * @generated from field: bool protobuf_pythonic_types_enabled = 2;
   */
  protobufPythonicTypesEnabled = false;

  /**
   * @generated from field: bool unversioned_package_disabled = 3;
   */
  unversionedPackageDisabled = false;

  constructor(data?: PartialMessage<PythonSettings_ExperimentalFeatures>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.PythonSettings.ExperimentalFeatures";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "rest_async_io_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "protobuf_pythonic_types_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "unversioned_package_disabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PythonSettings_ExperimentalFeatures {
    return new PythonSettings_ExperimentalFeatures().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PythonSettings_ExperimentalFeatures {
    return new PythonSettings_ExperimentalFeatures().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PythonSettings_ExperimentalFeatures {
    return new PythonSettings_ExperimentalFeatures().fromJsonString(jsonString, options);
  }

  static equals(a: PythonSettings_ExperimentalFeatures | PlainMessage<PythonSettings_ExperimentalFeatures> | undefined, b: PythonSettings_ExperimentalFeatures | PlainMessage<PythonSettings_ExperimentalFeatures> | undefined): boolean {
    return proto3.util.equals(PythonSettings_ExperimentalFeatures, a, b);
  }
}

/**
 * @generated from message google.api.NodeSettings
 */
export class NodeSettings extends Message<NodeSettings> {
  /**
   * @generated from field: google.api.CommonLanguageSettings common = 1;
   */
  common?: CommonLanguageSettings;

  constructor(data?: PartialMessage<NodeSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.NodeSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "common", kind: "message", T: CommonLanguageSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NodeSettings {
    return new NodeSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NodeSettings {
    return new NodeSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NodeSettings {
    return new NodeSettings().fromJsonString(jsonString, options);
  }

  static equals(a: NodeSettings | PlainMessage<NodeSettings> | undefined, b: NodeSettings | PlainMessage<NodeSettings> | undefined): boolean {
    return proto3.util.equals(NodeSettings, a, b);
  }
}

/**
 * @generated from message google.api.DotnetSettings
 */
export class DotnetSettings extends Message<DotnetSettings> {
  /**
   * @generated from field: google.api.CommonLanguageSettings common = 1;
   */
  common?: CommonLanguageSettings;

  /**
   * @generated from field: repeated google.api.DotnetSettings.RenamedServicesEntry renamed_services = 2;
   */
  renamedServices: DotnetSettings_RenamedServicesEntry[] = [];

  /**
   * @generated from field: repeated google.api.DotnetSettings.RenamedResourcesEntry renamed_resources = 3;
   */
  renamedResources: DotnetSettings_RenamedResourcesEntry[] = [];

  /**
   * @generated from field: repeated string ignored_resources = 4;
   */
  ignoredResources: string[] = [];

  /**
   * @generated from field: repeated string forced_namespace_aliases = 5;
   */
  forcedNamespaceAliases: string[] = [];

  /**
   * @generated from field: repeated string handwritten_signatures = 6;
   */
  handwrittenSignatures: string[] = [];

  constructor(data?: PartialMessage<DotnetSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.DotnetSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "common", kind: "message", T: CommonLanguageSettings },
    { no: 2, name: "renamed_services", kind: "message", T: DotnetSettings_RenamedServicesEntry, repeated: true },
    { no: 3, name: "renamed_resources", kind: "message", T: DotnetSettings_RenamedResourcesEntry, repeated: true },
    { no: 4, name: "ignored_resources", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "forced_namespace_aliases", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "handwritten_signatures", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DotnetSettings {
    return new DotnetSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DotnetSettings {
    return new DotnetSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DotnetSettings {
    return new DotnetSettings().fromJsonString(jsonString, options);
  }

  static equals(a: DotnetSettings | PlainMessage<DotnetSettings> | undefined, b: DotnetSettings | PlainMessage<DotnetSettings> | undefined): boolean {
    return proto3.util.equals(DotnetSettings, a, b);
  }
}

/**
 * @generated from message google.api.DotnetSettings.RenamedServicesEntry
 */
export class DotnetSettings_RenamedServicesEntry extends Message<DotnetSettings_RenamedServicesEntry> {
  /**
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * @generated from field: string value = 2;
   */
  value = "";

  constructor(data?: PartialMessage<DotnetSettings_RenamedServicesEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.DotnetSettings.RenamedServicesEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DotnetSettings_RenamedServicesEntry {
    return new DotnetSettings_RenamedServicesEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DotnetSettings_RenamedServicesEntry {
    return new DotnetSettings_RenamedServicesEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DotnetSettings_RenamedServicesEntry {
    return new DotnetSettings_RenamedServicesEntry().fromJsonString(jsonString, options);
  }

  static equals(a: DotnetSettings_RenamedServicesEntry | PlainMessage<DotnetSettings_RenamedServicesEntry> | undefined, b: DotnetSettings_RenamedServicesEntry | PlainMessage<DotnetSettings_RenamedServicesEntry> | undefined): boolean {
    return proto3.util.equals(DotnetSettings_RenamedServicesEntry, a, b);
  }
}

/**
 * @generated from message google.api.DotnetSettings.RenamedResourcesEntry
 */
export class DotnetSettings_RenamedResourcesEntry extends Message<DotnetSettings_RenamedResourcesEntry> {
  /**
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * @generated from field: string value = 2;
   */
  value = "";

  constructor(data?: PartialMessage<DotnetSettings_RenamedResourcesEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.DotnetSettings.RenamedResourcesEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DotnetSettings_RenamedResourcesEntry {
    return new DotnetSettings_RenamedResourcesEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DotnetSettings_RenamedResourcesEntry {
    return new DotnetSettings_RenamedResourcesEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DotnetSettings_RenamedResourcesEntry {
    return new DotnetSettings_RenamedResourcesEntry().fromJsonString(jsonString, options);
  }

  static equals(a: DotnetSettings_RenamedResourcesEntry | PlainMessage<DotnetSettings_RenamedResourcesEntry> | undefined, b: DotnetSettings_RenamedResourcesEntry | PlainMessage<DotnetSettings_RenamedResourcesEntry> | undefined): boolean {
    return proto3.util.equals(DotnetSettings_RenamedResourcesEntry, a, b);
  }
}

/**
 * @generated from message google.api.RubySettings
 */
export class RubySettings extends Message<RubySettings> {
  /**
   * @generated from field: google.api.CommonLanguageSettings common = 1;
   */
  common?: CommonLanguageSettings;

  constructor(data?: PartialMessage<RubySettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.RubySettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "common", kind: "message", T: CommonLanguageSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RubySettings {
    return new RubySettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RubySettings {
    return new RubySettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RubySettings {
    return new RubySettings().fromJsonString(jsonString, options);
  }

  static equals(a: RubySettings | PlainMessage<RubySettings> | undefined, b: RubySettings | PlainMessage<RubySettings> | undefined): boolean {
    return proto3.util.equals(RubySettings, a, b);
  }
}

/**
 * @generated from message google.api.GoSettings
 */
export class GoSettings extends Message<GoSettings> {
  /**
   * @generated from field: google.api.CommonLanguageSettings common = 1;
   */
  common?: CommonLanguageSettings;

  /**
   * @generated from field: repeated google.api.GoSettings.RenamedServicesEntry renamed_services = 2;
   */
  renamedServices: GoSettings_RenamedServicesEntry[] = [];

  constructor(data?: PartialMessage<GoSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.GoSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "common", kind: "message", T: CommonLanguageSettings },
    { no: 2, name: "renamed_services", kind: "message", T: GoSettings_RenamedServicesEntry, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GoSettings {
    return new GoSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GoSettings {
    return new GoSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GoSettings {
    return new GoSettings().fromJsonString(jsonString, options);
  }

  static equals(a: GoSettings | PlainMessage<GoSettings> | undefined, b: GoSettings | PlainMessage<GoSettings> | undefined): boolean {
    return proto3.util.equals(GoSettings, a, b);
  }
}

/**
 * @generated from message google.api.GoSettings.RenamedServicesEntry
 */
export class GoSettings_RenamedServicesEntry extends Message<GoSettings_RenamedServicesEntry> {
  /**
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * @generated from field: string value = 2;
   */
  value = "";

  constructor(data?: PartialMessage<GoSettings_RenamedServicesEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.GoSettings.RenamedServicesEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GoSettings_RenamedServicesEntry {
    return new GoSettings_RenamedServicesEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GoSettings_RenamedServicesEntry {
    return new GoSettings_RenamedServicesEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GoSettings_RenamedServicesEntry {
    return new GoSettings_RenamedServicesEntry().fromJsonString(jsonString, options);
  }

  static equals(a: GoSettings_RenamedServicesEntry | PlainMessage<GoSettings_RenamedServicesEntry> | undefined, b: GoSettings_RenamedServicesEntry | PlainMessage<GoSettings_RenamedServicesEntry> | undefined): boolean {
    return proto3.util.equals(GoSettings_RenamedServicesEntry, a, b);
  }
}

/**
 * @generated from message google.api.MethodSettings
 */
export class MethodSettings extends Message<MethodSettings> {
  /**
   * @generated from field: string selector = 1;
   */
  selector = "";

  /**
   * @generated from field: google.api.MethodSettings.LongRunning long_running = 2;
   */
  longRunning?: MethodSettings_LongRunning;

  /**
   * @generated from field: repeated string auto_populated_fields = 3;
   */
  autoPopulatedFields: string[] = [];

  constructor(data?: PartialMessage<MethodSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.MethodSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "selector", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "long_running", kind: "message", T: MethodSettings_LongRunning },
    { no: 3, name: "auto_populated_fields", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MethodSettings {
    return new MethodSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MethodSettings {
    return new MethodSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MethodSettings {
    return new MethodSettings().fromJsonString(jsonString, options);
  }

  static equals(a: MethodSettings | PlainMessage<MethodSettings> | undefined, b: MethodSettings | PlainMessage<MethodSettings> | undefined): boolean {
    return proto3.util.equals(MethodSettings, a, b);
  }
}

/**
 * @generated from message google.api.MethodSettings.LongRunning
 */
export class MethodSettings_LongRunning extends Message<MethodSettings_LongRunning> {
  /**
   * @generated from field: google.protobuf.Duration initial_poll_delay = 1;
   */
  initialPollDelay?: Duration;

  /**
   * @generated from field: float poll_delay_multiplier = 2;
   */
  pollDelayMultiplier = 0;

  /**
   * @generated from field: google.protobuf.Duration max_poll_delay = 3;
   */
  maxPollDelay?: Duration;

  /**
   * @generated from field: google.protobuf.Duration total_poll_timeout = 4;
   */
  totalPollTimeout?: Duration;

  constructor(data?: PartialMessage<MethodSettings_LongRunning>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.MethodSettings.LongRunning";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "initial_poll_delay", kind: "message", T: Duration },
    { no: 2, name: "poll_delay_multiplier", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "max_poll_delay", kind: "message", T: Duration },
    { no: 4, name: "total_poll_timeout", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MethodSettings_LongRunning {
    return new MethodSettings_LongRunning().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MethodSettings_LongRunning {
    return new MethodSettings_LongRunning().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MethodSettings_LongRunning {
    return new MethodSettings_LongRunning().fromJsonString(jsonString, options);
  }

  static equals(a: MethodSettings_LongRunning | PlainMessage<MethodSettings_LongRunning> | undefined, b: MethodSettings_LongRunning | PlainMessage<MethodSettings_LongRunning> | undefined): boolean {
    return proto3.util.equals(MethodSettings_LongRunning, a, b);
  }
}

/**
 * @generated from message google.api.SelectiveGapicGeneration
 */
export class SelectiveGapicGeneration extends Message<SelectiveGapicGeneration> {
  /**
   * @generated from field: repeated string methods = 1;
   */
  methods: string[] = [];

  /**
   * @generated from field: bool generate_omitted_as_internal = 2;
   */
  generateOmittedAsInternal = false;

  constructor(data?: PartialMessage<SelectiveGapicGeneration>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.SelectiveGapicGeneration";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "methods", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "generate_omitted_as_internal", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SelectiveGapicGeneration {
    return new SelectiveGapicGeneration().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SelectiveGapicGeneration {
    return new SelectiveGapicGeneration().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SelectiveGapicGeneration {
    return new SelectiveGapicGeneration().fromJsonString(jsonString, options);
  }

  static equals(a: SelectiveGapicGeneration | PlainMessage<SelectiveGapicGeneration> | undefined, b: SelectiveGapicGeneration | PlainMessage<SelectiveGapicGeneration> | undefined): boolean {
    return proto3.util.equals(SelectiveGapicGeneration, a, b);
  }
}

