// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file google/api/field_info.proto (package google.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message google.api.FieldInfo
 */
export class FieldInfo extends Message<FieldInfo> {
  /**
   * @generated from field: google.api.FieldInfo.Format format = 1;
   */
  format = FieldInfo_Format.FORMAT_UNSPECIFIED;

  /**
   * @generated from field: repeated google.api.TypeReference referenced_types = 2;
   */
  referencedTypes: TypeReference[] = [];

  constructor(data?: PartialMessage<FieldInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.FieldInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "format", kind: "enum", T: proto3.getEnumType(FieldInfo_Format) },
    { no: 2, name: "referenced_types", kind: "message", T: TypeReference, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FieldInfo {
    return new FieldInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FieldInfo {
    return new FieldInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FieldInfo {
    return new FieldInfo().fromJsonString(jsonString, options);
  }

  static equals(a: FieldInfo | PlainMessage<FieldInfo> | undefined, b: FieldInfo | PlainMessage<FieldInfo> | undefined): boolean {
    return proto3.util.equals(FieldInfo, a, b);
  }
}

/**
 * @generated from enum google.api.FieldInfo.Format
 */
export enum FieldInfo_Format {
  /**
   * @generated from enum value: FORMAT_UNSPECIFIED = 0;
   */
  FORMAT_UNSPECIFIED = 0,

  /**
   * @generated from enum value: UUID4 = 1;
   */
  UUID4 = 1,

  /**
   * @generated from enum value: IPV4 = 2;
   */
  IPV4 = 2,

  /**
   * @generated from enum value: IPV6 = 3;
   */
  IPV6 = 3,

  /**
   * @generated from enum value: IPV4_OR_IPV6 = 4;
   */
  IPV4_OR_IPV6 = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(FieldInfo_Format)
proto3.util.setEnumType(FieldInfo_Format, "google.api.FieldInfo.Format", [
  { no: 0, name: "FORMAT_UNSPECIFIED" },
  { no: 1, name: "UUID4" },
  { no: 2, name: "IPV4" },
  { no: 3, name: "IPV6" },
  { no: 4, name: "IPV4_OR_IPV6" },
]);

/**
 * @generated from message google.api.TypeReference
 */
export class TypeReference extends Message<TypeReference> {
  /**
   * @generated from field: string type_name = 1;
   */
  typeName = "";

  constructor(data?: PartialMessage<TypeReference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.api.TypeReference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TypeReference {
    return new TypeReference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TypeReference {
    return new TypeReference().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TypeReference {
    return new TypeReference().fromJsonString(jsonString, options);
  }

  static equals(a: TypeReference | PlainMessage<TypeReference> | undefined, b: TypeReference | PlainMessage<TypeReference> | undefined): boolean {
    return proto3.util.equals(TypeReference, a, b);
  }
}

