// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file google/api/field_behavior.proto (package google.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum google.api.FieldBehavior
 */
export enum FieldBehavior {
  /**
   * @generated from enum value: FIELD_BEHAVIOR_UNSPECIFIED = 0;
   */
  FIELD_BEHAVIOR_UNSPECIFIED = 0,

  /**
   * @generated from enum value: OPTIONAL = 1;
   */
  OPTIONAL = 1,

  /**
   * @generated from enum value: REQUIRED = 2;
   */
  REQUIRED = 2,

  /**
   * @generated from enum value: OUTPUT_ONLY = 3;
   */
  OUTPUT_ONLY = 3,

  /**
   * @generated from enum value: INPUT_ONLY = 4;
   */
  INPUT_ONLY = 4,

  /**
   * @generated from enum value: IMMUTABLE = 5;
   */
  IMMUTABLE = 5,

  /**
   * @generated from enum value: UNORDERED_LIST = 6;
   */
  UNORDERED_LIST = 6,

  /**
   * @generated from enum value: NON_EMPTY_DEFAULT = 7;
   */
  NON_EMPTY_DEFAULT = 7,

  /**
   * @generated from enum value: IDENTIFIER = 8;
   */
  IDENTIFIER = 8,
}
// Retrieve enum metadata with: proto3.getEnumType(FieldBehavior)
proto3.util.setEnumType(FieldBehavior, "google.api.FieldBehavior", [
  { no: 0, name: "FIELD_BEHAVIOR_UNSPECIFIED" },
  { no: 1, name: "OPTIONAL" },
  { no: 2, name: "REQUIRED" },
  { no: 3, name: "OUTPUT_ONLY" },
  { no: 4, name: "INPUT_ONLY" },
  { no: 5, name: "IMMUTABLE" },
  { no: 6, name: "UNORDERED_LIST" },
  { no: 7, name: "NON_EMPTY_DEFAULT" },
  { no: 8, name: "IDENTIFIER" },
]);

