// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file google/api/launch_stage.proto (package google.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum google.api.LaunchStage
 */
export enum LaunchStage {
  /**
   * @generated from enum value: LAUNCH_STAGE_UNSPECIFIED = 0;
   */
  LAUNCH_STAGE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: UNIMPLEMENTED = 6;
   */
  UNIMPLEMENTED = 6,

  /**
   * @generated from enum value: PRELAUNCH = 7;
   */
  PRELAUNCH = 7,

  /**
   * @generated from enum value: EARLY_ACCESS = 1;
   */
  EARLY_ACCESS = 1,

  /**
   * @generated from enum value: ALPHA = 2;
   */
  ALPHA = 2,

  /**
   * @generated from enum value: BETA = 3;
   */
  BETA = 3,

  /**
   * @generated from enum value: GA = 4;
   */
  GA = 4,

  /**
   * @generated from enum value: DEPRECATED = 5;
   */
  DEPRECATED = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(LaunchStage)
proto3.util.setEnumType(LaunchStage, "google.api.LaunchStage", [
  { no: 0, name: "LAUNCH_STAGE_UNSPECIFIED" },
  { no: 6, name: "UNIMPLEMENTED" },
  { no: 7, name: "PRELAUNCH" },
  { no: 1, name: "EARLY_ACCESS" },
  { no: 2, name: "ALPHA" },
  { no: 3, name: "BETA" },
  { no: 4, name: "GA" },
  { no: 5, name: "DEPRECATED" },
]);

