// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { ClickType, ScrollDirection, WindowState } from "../../../gen/exa/browser_pb/browser_pb.js";
import { ChatClientRequestStreamClientType } from "../../../gen/exa/chat_client_server_pb/chat_client_server_pb.js";
import { ArtifactReviewMode, BrowserJsAutoRunPolicy, BrowserJsExecutionPolicy, CascadeCommandsAutoExecution, ConversationalPlannerMode, DeploymentBuildStatus, Model, StopReason } from "../../../gen/exa/codeium_common_pb/codeium_common_pb.js";
import { AcknowledgementType, AgentMode, ArtifactReviewStatus, AutoRunDecision, BrainEntryType, BrainUpdateTrigger, BrowserActionWaitingReason, BrowserEphemeralOption, BrowserSubagentContextConfig_ContextType, BrowserSubagentMode, BrowserToolSetMode, CheckpointStrategy, ClickFeedbackConfig_FeedbackType, CloudSQLUpdateSchemaErrorCode, CloudSQLUpdateSchemaResult, CodeAcknowledgementScope, CodeHeuristicFailure, CommandOutputPriority, CortexMemorySource, CortexMemoryTrigger, CortexStepCompileTool, CortexStepExecuteNotebook_CellStatus, CortexStepExecuteNotebook_ExecutionStatus, CortexStepManagerFeedbackStatus, CortexStepStatus, CortexStepType, CortexTrajectoryReferenceType, CortexTrajectoryType, EditNotebookOperation, EphemeralMessagePersistenceLevel, ExecutorTerminationReason, FileChangeType, FilePermissionInteractionSpec_BlockReason, FindResultType, FunctionProvider_Protocol, InteractiveCascadeEditImportance, LintDiffType, McpAuthProviderType, McpServerStatus, McpToolBackgroundMode, MemoryActionType, MessagePriority, PermissionScope, RecordingGenerationStatus, ReplaceToolVariant, RetryReason, RunExtensionCodeAutoRunDecision, SearchWebType, SectionOverrideMode, SemanticCodebaseSearchType, SetUpCloudSqlErrorCode, SetUpCloudSqlResult, SetUpFirebaseErrorCode, SetUpFirebaseRequest, SetUpFirebaseResult, SidecarStatus, SidecarUIEntrypoint, TaskDeltaType, TaskStatus, TokenSource, TokenType, TrajectorySearchIdType, TruncationReason } from "../../../gen/exa/cortex_pb/cortex_pb.js";
import { ConnectorType } from "../../../gen/exa/opensearch_clients_pb/opensearch_clients_pb.js";
import { AnyInput } from "../../google/protobuf/any_pb.js";
import { DurationInput } from "../../google/protobuf/duration_pb.js";
import { StructInput } from "../../google/protobuf/struct_pb.js";
import { TimestampInput } from "../../google/protobuf/timestamp_pb.js";
import { ChatMessagePromptInput, ChatToolChoiceInput, ChatToolDefinitionInput, PromptCacheOptionsInput } from "../chat_pb/chat_pb.js";
import { AntigravityDeploymentInput, ArtifactCommentInput, ArtifactMetadataInput, BrowserPageMetadataInput, CciWithSubrangeInput, ChatToolCallInput, CodeContextItemInput, CodeDiagnosticInput, CompletionConfigurationInput, ConsoleLogScopeItemInput, ContextScopeItemInput, DOMTreeInput, DeployTargetInput, DocumentOutlineInput, FileCommentInput, FileDiffCommentInput, ImageDataInput, KnowledgeBaseGroupInput, KnowledgeBaseItemInput, KnowledgeBaseItemWithMetadataInput, LspReferenceInput, MQueryConfigInput, McpPromptArgumentInput, McpResourceContentInput, MediaInput, MetricsRecordInput, ModelInfoInput, ModelOrAliasInput, ModelUsageStatsInput, PathScopeItemInput, PermissionGrantsConfigInput, Point2Input, RecitationMetadataInput, RepositoryInput, TextOrScopeItemInput, ThirdPartyWebSearchConfigInput, ViewportInput } from "../codeium_common_pb/codeium_common_pb.js";
import { CciWithSubrangeWithRetrievalMetadataInput, ContextModuleResultInput } from "../context_module_pb/context_module_pb.js";
import { DiffBlockInput, DiffListInput, UnifiedDiffInput } from "../diff_action_pb/diff_action_pb.js";
import { CreditsInput } from "../google/internal/cloud/code/v1internal/credits_pb.js";
import { TimeRangeInput } from "../opensearch_clients_pb/opensearch_clients_pb.js";

export interface ActionDebugInfo_DebugInfoEntryInput {
  key?: string;
  value?: string;
}

export interface ActionDebugInfoInput {
  entries?: ActionDebugInfo_DebugInfoEntryInput[];
}

export interface ActionResultEditInput {
  absolutePathMigrateMeToUri?: string;
  diff?: DiffBlockInput;
  contextPrefix?: string;
  contextSuffix?: string;
  debugInfo?: ActionDebugInfoInput;
  promptId?: string;
  completionId?: string;
  fileContentHash?: string;
  absoluteUri?: string;
  resultCcis?: CodeContextItemInput[];
  originalContent?: string;
  createFile?: boolean;
}

export interface ActionResultInput {
  applyExistingResult?: boolean;
  edit?: ActionResultEditInput;
}

export interface ActionSpecCommandInput {
  instruction?: string;
  replacementChunks?: ReplacementChunkInput[];
  isEdit?: boolean;
  useFastApply?: boolean;
  referenceCcis?: CodeContextItemInput[];
  classification?: string;
  importance?: InteractiveCascadeEditImportance;
  codeContext?: CodeContextItemInput;
  file?: PathScopeItemInput;
  cciWithSubrange?: CciWithSubrangeInput;
  lineRange?: LineRangeTargetInput;
  contentTarget?: CommandContentTargetInput;
}

export interface ActionSpecCreateFileInput {
  instruction?: string;
  path?: PathScopeItemInput;
  referenceCcis?: CodeContextItemInput[];
  overwrite?: boolean;
}

export interface ActionSpecDeleteFileInput {
  path?: PathScopeItemInput;
}

export interface ActionSpecInput {
  parentStepIndices?: number[];
  command?: ActionSpecCommandInput;
  createFile?: ActionSpecCreateFileInput;
  deleteFile?: ActionSpecDeleteFileInput;
  sed?: ActionSpecSedInput;
}

export interface ActionSpecSed_FileContentEntryInput {
  key?: string;
  value?: string;
}

export interface ActionSpecSedInput {
  expressions?: string[];
  path?: PathScopeItemInput;
  fileContent?: ActionSpecSed_FileContentEntryInput[];
}

export interface AgentApiConfigInput {
  enabled?: boolean;
}

export interface AgentConfigInput {
  mixinConfig?: DeclarativeMixinConfigInput;
  model?: Model;
  customizationDiscovery?: CustomizationDiscoveryConfigInput;
  cascadeConfig?: CascadeConfigInput;
}

export interface AgentCustomizationInput {
  path?: string;
  agent?: AgentScriptItemInput;
  isGlobal?: boolean;
}

export interface AgentDiscoveryConfigInput {
  inheritUser?: boolean;
  builtinAgentNames?: string[];
  agents?: AgentScriptItemInput[];
}

export interface AgenticModeConfig_InjectArtifactReminderThresholdMapEntryInput {
  key?: string;
  value?: number;
}

export interface AgenticModeConfigInput {
  injectArtifactReminderThresholdMap?: AgenticModeConfig_InjectArtifactReminderThresholdMapEntryInput[];
  disableArtifactReminders?: boolean;
}

export interface AgentMessageInput {
  id?: string;
  recipient?: string;
  sender?: string;
  priority?: MessagePriority;
  timestamp?: TimestampInput;
  renderDetails?: MessageRenderDetailsInput;
  hideFromUser?: boolean;
  sourceMetadata?: SourceMetadataInput;
  content?: string;
  stepPayload?: Uint8Array;
}

export interface AgentScriptCommandSpecInput {
  command?: string;
  args?: string[];
}

export interface AgentScriptConfigPathInput {
  configPathUri?: string;
  relativePathToConfig?: string;
}

export interface AgentScriptItemInput {
  name?: string;
  description?: string;
  disabled?: boolean;
  hidden?: boolean;
  subagent?: boolean;
  mainAgent?: boolean;
  commandSpec?: AgentScriptCommandSpecInput;
  pythonSpec?: AgentScriptPythonSpecInput;
  configPath?: AgentScriptConfigPathInput;
  config?: CustomAgentSpecInput;
  cascadeConfig?: CascadeConfigInput;
}

export interface AgentScriptPythonSpecInput {
  mainPyPathUri?: string;
  requirementsTxtPathUri?: string;
  relativePathToMainPy?: string;
  relativePathToRequirementsTxt?: string;
}

export interface AntigravityBrowserToolConfigInput {
  enabled?: boolean;
  autoRunDecision?: AutoRunDecision;
  captureBrowserScreenshot?: CaptureBrowserScreenshotToolConfigInput;
  browserSubagent?: BrowserSubagentToolConfigInput;
  clickBrowserPixel?: ClickBrowserPixelToolConfigInput;
  browserStateDiffingConfig?: BrowserStateDiffingConfigInput;
  browserListNetworkRequestsToolConfig?: BrowserListNetworkRequestsToolConfigInput;
  browserGetNetworkRequestToolConfig?: BrowserGetNetworkRequestToolConfigInput;
  toolSetMode?: BrowserToolSetMode;
  disableOpenUrl?: boolean;
  isEvalMode?: boolean;
  browserJsExecutionPolicy?: BrowserJsExecutionPolicy;
  disableActuationOverlay?: boolean;
  variableWaitTool?: boolean;
  browserJsAutoRunPolicy?: BrowserJsAutoRunPolicy;
  initialBrowserWindowSize?: BrowserWindowSizeInput;
  domExtractionConfig?: DOMExtractionConfigInput;
  disableWorkspaceApi?: boolean;
  openPageInBackground?: boolean;
  useAntigravityAsBrowserPrompting?: boolean;
  enableRefreshTool?: boolean;
  disableReadBrowserPage?: boolean;
  useExtendedTimeout?: boolean;
  logTimeoutErrorsInsteadOfSentry?: boolean;
  skipPermissionChecks?: boolean;
  displayOnCrd?: boolean;
}

export interface ApprovalInteractionInput {
  confirm?: boolean;
}

export interface ApprovalInteractionSpecInput {
}

export interface ArtifactReviewStateInput {
  artifactUri?: string;
  status?: ArtifactReviewStatus;
  lastReviewedTime?: TimestampInput;
  lastReviewedContent?: string;
}

export interface ArtifactSnapshotInput {
  artifactName?: string;
  content?: string;
  artifactAbsoluteUri?: string;
  lastEdited?: TimestampInput;
  reviewState?: ArtifactReviewStateInput;
}

export interface AskQuestionEntryInput {
  question?: string;
  options?: AskQuestionOptionInput[];
  isMultiSelect?: boolean;
  selectedOptionIds?: string[];
  writeInResponse?: string;
  skipped?: boolean;
}

export interface AskQuestionInteractionInput {
  responses?: AskQuestionEntryInput[];
  cancelled?: boolean;
}

export interface AskQuestionInteractionSpecInput {
  questions?: AskQuestionEntryInput[];
}

export interface AskQuestionOptionInput {
  id?: string;
  text?: string;
}

export interface AskQuestionToolConfigInput {
  enabled?: boolean;
}

export interface AutoCommandConfigInput {
  enableModelAutoRun?: boolean;
  userAllowlist?: string[];
  userDenylist?: string[];
  systemAllowlist?: string[];
  systemDenylist?: string[];
  systemDenylistRegex?: string[];
  systemNooplist?: string[];
  autoExecutionPolicy?: CascadeCommandsAutoExecution;
}

export interface AutoFixLintsConfigInput {
  enabled?: boolean;
  notifyingPrompt?: string;
}

export interface BrainEntryDeltaInput {
  before?: BrainEntryInput;
  after?: BrainEntryInput;
  absolutePathUri?: string;
  summary?: BrainEntryDeltaSummaryInput;
}

export interface BrainEntryDeltaSummaryInput {
  plan?: PlanEntryDeltaSummaryInput;
  task?: TaskEntryDeltaSummaryInput;
}

export interface BrainEntryInput {
  id?: string;
  type?: BrainEntryType;
  content?: string;
}

export interface BrowserCustomReminderModeInput {
  reminder?: string;
}

export interface BrowserGetNetworkRequestToolConfigInput {
  enabled?: boolean;
}

export interface BrowserListNetworkRequestsToolConfigInput {
  enabled?: boolean;
}

export interface BrowserStateDiffingConfigInput {
  captureAgentActionDiffs?: boolean;
  includeDomTreeInDiffs?: boolean;
}

export interface BrowserSubagentContextConfigInput {
  type?: BrowserSubagentContextConfig_ContextType;
  maxChars?: number;
}

export interface BrowserSubagentToolConfigInput {
  mode?: BrowserSubagentMode;
  browserSubagentModel?: Model;
  useDetailedConverter?: boolean;
  suggestedMaxToolCalls?: number;
  disableOnboarding?: boolean;
  subagentReminderMode?: SubagentReminderModeInput;
  maxContextTokens?: number;
  contextConfig?: BrowserSubagentContextConfigInput;
  domExtractionConfig?: DOMExtractionConfigInput;
  disableScreenshot?: boolean;
  lowLevelToolsConfig?: LowLevelToolsConfigInput;
  enableScratchpad?: boolean;
  includeCiPrompt?: boolean;
}

export interface BrowserVerifyCompletenessModeInput {
}

export interface BrowserVerifyScreenshotsModeInput {
}

export interface BrowserWindowSizeInput {
  widthPx?: number;
  heightPx?: number;
}

export interface CacheBreakpointMetadataInput {
  index?: number;
  options?: PromptCacheOptionsInput;
  contentChecksum?: string;
}

export interface CacheRequestOptionsInput {
  enabled?: boolean;
  cacheBreakpointIndices?: number[];
}

export interface CaptureBrowserScreenshotToolConfigInput {
  enableSaving?: boolean;
}

export interface CascadeBrowserActionInteractionInput {
  confirm?: boolean;
}

export interface CascadeCaptureBrowserScreenshotInteractionInput {
  confirm?: boolean;
}

export interface CascadeCaptureBrowserScreenshotInteractionSpecInput {
}

export interface CascadeClickBrowserPixelInteractionInput {
  confirm?: boolean;
}

export interface CascadeClickBrowserPixelInteractionSpecInput {
}

export interface CascadeConfigInput {
  plannerConfig?: CascadePlannerConfigInput;
  checkpointConfig?: CheckpointConfigInput;
  executorConfig?: CascadeExecutorConfigInput;
  trajectoryConversionConfig?: TrajectoryConversionConfigInput;
  applyModelDefaultOverride?: boolean;
  conversationHistoryConfig?: ConversationHistoryConfigInput;
  splitDynamicPromptSections?: boolean;
  messageConfig?: MessageConfigInput;
  useDbTrajectory?: boolean;
  agentApiConfig?: AgentApiConfigInput;
}

export interface CascadeConfirmBrowserSetupInteractionInput {
  confirm?: boolean;
}

export interface CascadeConversationalPlannerConfigInput {
  plannerMode?: ConversationalPlannerMode;
  evalMode?: boolean;
  agenticMode?: boolean;
  promptCombinationName?: string;
  conversationHistoryConfig?: ConversationHistoryConfigInput;
  overrideWorkspaceDirExperimentalUseOnly?: string;
  overrideCascadeIdForPrompt?: string;
}

export interface CascadeDeployInteractionInput {
  cancel?: boolean;
  deployTarget?: DeployTargetInput;
  subdomain?: string;
}

export interface CascadeDeployInteractionSpecInput {
  deployTargetOptions?: DeployTargetInput[];
}

export interface CascadeExecuteBrowserJavaScriptInteractionInput {
  confirm?: boolean;
}

export interface CascadeExecuteBrowserJavaScriptInteractionSpecInput {
}

export interface CascadeExecutorConfigInput {
  disableAsync?: boolean;
  maxGeneratorInvocations?: number;
  terminalStepTypes?: CortexStepType[];
  holdForValidCheckpoint?: boolean;
  holdForValidCheckpointTimeout?: number;
  researchOnly?: boolean;
  useAggressiveSnapshotting?: boolean;
  requireFinishTool?: boolean;
  maxForcedInvocations?: number;
  queueAllSteps?: boolean;
  storeGenSvcRequest?: boolean;
  enableTasks?: boolean;
  disableEmptyOutputContinuation?: boolean;
}

export interface CascadeMcpInteractionInput {
  confirm?: boolean;
}

export interface CascadeMcpInteractionSpecInput {
}

export interface CascadeOpenBrowserSetupInteractionInput {
  confirm?: boolean;
}

export interface CascadeOpenBrowserUrlInteractionInput {
  confirm?: boolean;
}

export interface CascadeOpenBrowserUrlInteractionSpecInput {
}

export interface CascadePlannerConfigInput {
  customizationConfig?: CustomizationConfigInput;
  promptSectionCustomizationConfig?: PromptSectionCustomizationConfigInput;
  toolConfig?: CascadeToolConfigInput;
  stepStringConverterConfig?: StepStringConverterConfigInput;
  planModel?: Model;
  requestedModel?: ModelOrAliasInput;
  modelName?: string;
  customModelInfoOverride?: ModelInfoInput;
  maxOutputTokens?: number;
  noToolExplanation?: boolean;
  noToolSummary?: boolean;
  truncationThresholdTokens?: number;
  ephemeralMessagesConfig?: EphemeralMessagesConfigInput;
  showAllErrors?: boolean;
  retryConfig?: PlannerRetryConfigInput;
  knowledgeConfig?: KnowledgeConfigInput;
  agenticModeConfig?: AgenticModeConfigInput;
  noWaitForPreviousTools?: boolean;
  experiments?: ExperimentsInput;
  conversational?: CascadeConversationalPlannerConfigInput;
  google?: CascadeConversationalPlannerConfigInput;
  cider?: CascadeConversationalPlannerConfigInput;
  customAgent?: CustomAgentConfigInput;
  customAgentConfigAbsoluteUri?: string;
  googleMinimal?: CascadeConversationalPlannerConfigInput;
  declarativeMixinConfig?: DeclarativeMixinConfigInput;
}

export interface CascadeReadUrlContentInteractionInput {
  confirm?: boolean;
}

export interface CascadeReadUrlContentInteractionSpecInput {
}

export interface CascadeRunCommandInteractionInput {
  confirm?: boolean;
  proposedCommandLine?: string;
  submittedCommandLine?: string;
  sandboxOverride?: boolean;
}

export interface CascadeRunCommandInteractionSpecInput {
}

export interface CascadeRunExtensionCodeInteractionInput {
  confirm?: boolean;
}

export interface CascadeRunExtensionCodeInteractionSpecInput {
}

export interface CascadeSendCommandInputInteractionInput {
  confirm?: boolean;
}

export interface CascadeSendCommandInputInteractionSpecInput {
}

export interface CascadeToolConfigInput {
  mquery?: MqueryToolConfigInput;
  code?: CodeToolConfigInput;
  intent?: IntentToolConfigInput;
  grep?: GrepToolConfigInput;
  find?: FindToolConfigInput;
  runCommand?: RunCommandToolConfigInput;
  knowledgeBaseSearch?: KnowledgeBaseSearchToolConfigInput;
  viewFile?: ViewFileToolConfigInput;
  suggestedResponse?: SuggestedResponseConfigInput;
  searchWeb?: SearchWebToolConfigInput;
  memory?: MemoryToolConfigInput;
  mcp?: McpToolConfigInput;
  listDir?: ListDirToolConfigInput;
  viewCodeItem?: ViewCodeItemToolConfigInput;
  readKnowledgeBaseItem?: ReadKnowledgeBaseItemToolConfigInput;
  commandStatus?: CommandStatusToolConfigInput;
  antigravityBrowser?: AntigravityBrowserToolConfigInput;
  trajectorySearch?: TrajectorySearchToolConfigInput;
  codeSearch?: CodeSearchToolConfigInput;
  internalSearch?: InternalSearchToolConfigInput;
  notifyUser?: NotifyUserConfigInput;
  browserSubagent?: BrowserSubagentToolConfigInput;
  taskBoundary?: TaskBoundaryToolConfigInput;
  finish?: FinishToolConfigInput;
  workspaceApi?: WorkspaceAPIToolConfigInput;
  notebookEdit?: NotebookEditToolConfigInput;
  invokeSubagent?: InvokeSubagentToolConfigInput;
  generateImage?: GenerateImageToolConfigInput;
  askQuestion?: AskQuestionToolConfigInput;
  permissionConfig?: PermissionConfigInput;
  descriptionOverrideMap?: ToolDescriptionOverrideMapInput;
  disableSimpleResearchTools?: boolean;
}

export interface CascadeUserInteractionInput {
  trajectoryId?: string;
  stepIndex?: number;
  deploy?: CascadeDeployInteractionInput;
  runCommand?: CascadeRunCommandInteractionInput;
  openBrowserUrl?: CascadeOpenBrowserUrlInteractionInput;
  runExtensionCode?: CascadeRunExtensionCodeInteractionInput;
  executeBrowserJavascript?: CascadeExecuteBrowserJavaScriptInteractionInput;
  captureBrowserScreenshot?: CascadeCaptureBrowserScreenshotInteractionInput;
  clickBrowserPixel?: CascadeClickBrowserPixelInteractionInput;
  browserAction?: CascadeBrowserActionInteractionInput;
  openBrowserSetup?: CascadeOpenBrowserSetupInteractionInput;
  confirmBrowserSetup?: CascadeConfirmBrowserSetupInteractionInput;
  sendCommandInput?: CascadeSendCommandInputInteractionInput;
  readUrlContent?: CascadeReadUrlContentInteractionInput;
  mcp?: CascadeMcpInteractionInput;
  filePermission?: FilePermissionInteractionInput;
  elicitation?: ElicitationInteractionInput;
  permission?: PermissionInteractionInput;
  askQuestion?: AskQuestionInteractionInput;
  approvalInteraction?: ApprovalInteractionInput;
}

export interface ChatModelMetadataInput {
  systemPrompt?: string;
  messagePrompts?: ChatMessagePromptInput[];
  messageMetadata?: MessagePromptMetadataInput[];
  model?: Model;
  usage?: ModelUsageStatsInput;
  modelCost?: number;
  lastCacheIndex?: number;
  toolChoice?: ChatToolChoiceInput;
  tools?: ChatToolDefinitionInput[];
  chatStartMetadata?: ChatStartMetadataInput;
  timeToFirstToken?: DurationInput;
  streamingDuration?: DurationInput;
  creditCost?: number;
  retries?: number;
  completionConfig?: CompletionConfigurationInput;
  promptSections?: PromptSectionInput[];
  retryInfos?: RetryInfoInput[];
  consumedCredits?: CreditsInput[];
  responseModel?: string;
}

export interface ChatStartMetadataInput {
  createdAt?: TimestampInput;
  startStepIndex?: number;
  checkpointIndex?: number;
  stepsCoveredByCheckpoint?: number[];
  latestStableMessageIndex?: number;
  cacheBreakpoints?: CacheBreakpointMetadataInput[];
  systemPromptCache?: CacheBreakpointMetadataInput;
  timeSinceLastInvocation?: DurationInput;
  cacheRequest?: CacheRequestOptionsInput;
  contextWindowMetadata?: ContextWindowMetadataInput;
}

export interface CheckpointConfigInput {
  tokenThreshold?: number;
  maxOverheadRatio?: number;
  movingWindowSize?: number;
  maxTokenLimit?: number;
  maxOutputTokens?: number;
  checkpointModel?: Model;
  enabled?: boolean;
  fullAsync?: boolean;
  maxUserRequests?: number;
  maxUserRequestBytes?: number;
  maxSubagentSnapshots?: number;
  retryConfig?: ModelAPIRetryConfigInput;
  enableFallback?: boolean;
  strategy?: CheckpointStrategy;
}

export interface ClickBrowserPixelToolConfigInput {
  clickFeedback?: ClickFeedbackConfigInput;
}

export interface ClickFeedbackConfigInput {
  enabled?: boolean;
  red?: number;
  green?: number;
  blue?: number;
  alpha?: number;
  displayColor?: string;
  radius?: number;
  feedbackType?: ClickFeedbackConfig_FeedbackType;
}

export interface CodeAcknowledgementConverterConfigInput {
  showToModelOnWrittenFeedback?: boolean;
  showToModelOnRejection?: boolean;
}

export interface CodeAcknowledgementInfoInput {
  uriPath?: string;
  stepIndices?: number[];
  diff?: UnifiedDiffInput;
}

export interface CodeSearchMatchInput {
  snippet?: string;
  lineNumber?: number;
}

export interface CodeSearchResultsInput {
  path?: string;
  matches?: CodeSearchMatchInput[];
  changelist?: string;
  depotPath?: string;
}

export interface CodeSearchToolConfigInput {
  csPath?: string;
  useEvalTag?: boolean;
}

export interface CodeToolConfigInput {
  disableExtensions?: string[];
  allowEditGitignore?: boolean;
  fileAllowlist?: string[];
  dirAllowlist?: string[];
  applyEdits?: boolean;
  onlyShowIncrementalDiffZone?: boolean;
  skipAwaitLintErrors?: boolean;
  autoFixLintsConfig?: AutoFixLintsConfigInput;
  replaceContentToolConfig?: ReplaceContentToolConfigInput;
  classifyEdit?: boolean;
  provideImportance?: boolean;
  skipReplaceContentValidation?: boolean;
  overrideAllowActionOnUnsavedFile?: boolean;
  useSedEdit?: boolean;
  useReplaceContentEditTool?: boolean;
  useReplaceContentProposeCode?: boolean;
  runProposalExtensionVerifier?: boolean;
}

export interface CodingAgentConfigInput {
  googleMode?: boolean;
  agenticMode?: boolean;
}

export interface CommandContentTargetInput {
  content?: string;
  absoluteUri?: string;
}

export interface CommandStatusToolConfigInput {
  useDelta?: boolean;
  maxOutputCharacters?: number;
  minOutputCharacters?: number;
  maxWaitDurationSeconds?: number;
  outputStabilizationDurationSeconds?: number;
  enableInputDetection?: boolean;
  inputDetectionModel?: Model;
}

export interface CompletedInteractionInput {
  request?: RequestedInteractionInput;
  response?: CascadeUserInteractionInput;
}

export interface ContextWindowMetadataInput {
  estimatedTokensUsed?: number;
  truncationReason?: TruncationReason;
  tokenBreakdown?: TokenBreakdownInput;
}

export interface ConversationHistoryConfigInput {
  enabled?: boolean;
  maxConversations?: number;
  maxTitleChars?: number;
  maxUserIntentChars?: number;
  maxConversationLogsChars?: number;
  maxArtifactSummaryChars?: number;
}

export interface CortexErrorDetailsInput {
  userErrorMessage?: string;
  modelErrorMessage?: string;
  structuredErrorParts?: StructuredErrorPartInput[];
  shortError?: string;
  fullError?: string;
  isBenign?: boolean;
  errorCode?: number;
  details?: string;
  errorId?: string;
  rpcErrorDetails?: string[];
}

export interface CortexMemoryAllScopeInput {
}

export interface CortexMemoryGlobalScopeInput {
}

export interface CortexMemoryInput {
  memoryId?: string;
  title?: string;
  source?: CortexMemorySource;
  scope?: CortexMemoryScopeInput;
  textMemory?: CortexMemoryTextInput;
}

export interface CortexMemoryLocalScopeInput {
  corpusNames?: string[];
  baseDirUris?: string[];
  repoBaseDirUri?: string;
}

export interface CortexMemoryProjectScopeInput {
  filePath?: string;
  absoluteFilePath?: string;
  baseDirUris?: string[];
  corpusNames?: string[];
  trigger?: CortexMemoryTrigger;
  description?: string;
  globs?: string[];
  priority?: number;
}

export interface CortexMemoryScopeInput {
  globalScope?: CortexMemoryGlobalScopeInput;
  localScope?: CortexMemoryLocalScopeInput;
  allScope?: CortexMemoryAllScopeInput;
  projectScope?: CortexMemoryProjectScopeInput;
}

export interface CortexMemoryTextInput {
  content?: string;
}

export interface CortexStepAgencyToolCallInput {
  agentName?: string;
  functionName?: string;
  requestMessages?: AnyInput[];
  responseMessages?: AnyInput[];
}

export interface CortexStepAskQuestionInput {
  questions?: AskQuestionEntryInput[];
}

export interface CortexStepBrainUpdateInput {
  trigger?: BrainUpdateTrigger;
  deltas?: BrainEntryDeltaInput[];
  entryType?: BrainEntryType;
}

export interface CortexStepBrowserClickElementInput {
  pageId?: string;
  index?: number;
  description?: string;
  clickType?: ClickType;
  userRejected?: boolean;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserDragPixelToPixelInput {
  pageId?: string;
  waypoints?: Point2Input[];
  userRejected?: boolean;
  pageMetadata?: BrowserPageMetadataInput;
  screenshotsWithDragFeedback?: MediaInput[];
}

export interface CortexStepBrowserGetDomInput {
  pageId?: string;
  domTree?: DOMTreeInput;
  serializedDomTree?: string;
  serializedDomTreeUri?: string;
  pageMetadata?: BrowserPageMetadataInput;
}

export interface CortexStepBrowserGetNetworkRequestInput {
  pageId?: string;
  requestId?: string;
  pageMetadata?: BrowserPageMetadataInput;
  networkRequestDetails?: string;
}

export interface CortexStepBrowserInputInput {
  pageId?: string;
  index?: number;
  text?: string;
  pressEnter?: boolean;
  clearText?: boolean;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserListNetworkRequestsInput {
  pageId?: string;
  includePreservedRequests?: boolean;
  resourceTypes?: string[];
  pageMetadata?: BrowserPageMetadataInput;
  networkRequests?: string;
}

export interface CortexStepBrowserMouseDownInput {
  pageId?: string;
  button?: string;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserMouseUpInput {
  pageId?: string;
  button?: string;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserMouseWheelInput {
  pageId?: string;
  x?: number;
  y?: number;
  dx?: number;
  dy?: number;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserMoveMouseInput {
  pageId?: string;
  x?: number;
  y?: number;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserPressKeyInput {
  pageId?: string;
  key?: string;
  text?: string;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserRefreshPageInput {
  pageId?: string;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserResizeWindowInput {
  pageId?: string;
  width?: number;
  height?: number;
  windowState?: WindowState;
  userRejected?: boolean;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserScrollDownInput {
  pageId?: string;
  scrollToEnd?: boolean;
  scrollByElementIndex?: boolean;
  elementIndex?: number;
  browserStateDiff?: string;
}

export interface CortexStepBrowserScrollInput {
  pageId?: string;
  direction?: ScrollDirection;
  scrollToEnd?: boolean;
  scrollByElementIndex?: boolean;
  elementIndex?: number;
  pixelsScrolledX?: number;
  pixelsScrolledY?: number;
  browserStateDiff?: string;
}

export interface CortexStepBrowserScrollUpInput {
  pageId?: string;
  scrollToEnd?: boolean;
  scrollByElementIndex?: boolean;
  elementIndex?: number;
  browserStateDiff?: string;
}

export interface CortexStepBrowserSelectOptionInput {
  pageId?: string;
  index?: number;
  value?: string;
  pageMetadata?: BrowserPageMetadataInput;
  browserStateDiff?: string;
}

export interface CortexStepBrowserSubagentInput {
  task?: string;
  reusedSubagentId?: string;
  recordingName?: string;
  media?: MediaInput[];
  result?: string;
  taskName?: string;
  taskSummary?: string;
  recordingPath?: string;
  recordingGenerationStatus?: RecordingGenerationStatus;
  subagentId?: string;
  skipped?: boolean;
  scratchpadPath?: string;
}

export interface CortexStepCaptureBrowserConsoleLogsInput {
  pageId?: string;
  pageMetadata?: BrowserPageMetadataInput;
  consoleLogs?: ConsoleLogScopeItemInput;
}

export interface CortexStepCaptureBrowserScreenshotInput {
  pageId?: string;
  saveScreenshot?: boolean;
  screenshotName?: string;
  captureByElementIndex?: boolean;
  elementIndex?: number;
  captureBeyondViewport?: boolean;
  userRejected?: boolean;
  screenshot?: ImageDataInput;
  mediaScreenshot?: MediaInput;
  screenshotViewport?: ViewportInput;
  pageMetadata?: BrowserPageMetadataInput;
  autoRunDecision?: AutoRunDecision;
}

export interface CortexStepCheckDeployStatusInput {
  antigravityDeploymentId?: string;
  deployment?: AntigravityDeploymentInput;
  buildStatus?: DeploymentBuildStatus;
  buildError?: string;
  buildLogs?: string;
  isClaimed?: boolean;
  claimUrl?: string;
}

export interface CortexStepCheckpoint_EditedFileMapEntryInput {
  key?: string;
  value?: DiffListInput;
}

export interface CortexStepCheckpointInput {
  checkpointIndex?: number;
  intentOnly?: boolean;
  includedStepIndexStart?: number;
  includedStepIndexEnd?: number;
  conversationTitle?: string;
  userIntent?: string;
  sessionSummary?: string;
  codeChangeSummary?: string;
  modelSummarizationFailed?: boolean;
  usedFallbackSummary?: boolean;
  artifactSnapshots?: ArtifactSnapshotInput[];
  conversationLogUris?: string[];
  trajectoryFileDiffs?: TrajectoryFileDiffInput[];
  userRequests?: string[];
  subagentSnapshots?: SubagentSnapshotInput[];
  runningTaskSnapshots?: TaskSnapshotInput[];
  editedFileMap?: CortexStepCheckpoint_EditedFileMapEntryInput[];
  includedStepIndices?: number[];
  memorySummary?: string;
}

export interface CortexStepClickBrowserPixelInput {
  pageId?: string;
  x?: number;
  y?: number;
  clickType?: ClickType;
  userRejected?: boolean;
  pageMetadata?: BrowserPageMetadataInput;
  screenshotWithClickFeedback?: MediaInput;
  browserStateDiff?: string;
}

export interface CortexStepClipboardInput {
  content?: string;
}

export interface CortexStepCloudSQLExecuteSQLInput {
  projectId?: string;
  instanceName?: string;
  sqlStatement?: string;
  errorMessage?: string;
  output?: string;
}

export interface CortexStepCloudSQLSchemaUpdateInput {
  errorMessage?: string;
  rpcErrorCode?: CloudSQLUpdateSchemaErrorCode;
  result?: CloudSQLUpdateSchemaResult;
  output?: string;
}

export interface CortexStepCodeAcknowledgementInput {
  isAccept?: boolean;
  writtenFeedback?: string;
  acknowledgementScope?: CodeAcknowledgementScope;
  codeAcknowledgementInfos?: CodeAcknowledgementInfoInput[];
}

export interface CortexStepCodeActionInput {
  actionSpec?: ActionSpecInput;
  actionResult?: ActionResultInput;
  useFastApply?: boolean;
  acknowledgementType?: AcknowledgementType;
  heuristicFailure?: CodeHeuristicFailure;
  codeInstruction?: string;
  lintErrors?: CodeDiagnosticInput[];
  persistentLintErrors?: CodeDiagnosticInput[];
  replacementInfos?: ReplacementChunkInfoInput[];
  lintErrorIdsAimingToFix?: string[];
  fastApplyFallbackInfo?: FastApplyFallbackInfoInput;
  targetFileHasCarriageReturns?: boolean;
  targetFileHasAllCarriageReturns?: boolean;
  introducedErrors?: CortexStepCompileDiagnosticInput[];
  triggeredMemories?: string;
  isArtifactFile?: boolean;
  artifactVersion?: number;
  artifactMetadata?: ArtifactMetadataInput;
  isKnowledgeFile?: boolean;
  filePermissionRequest?: FilePermissionInteractionSpecInput;
  description?: string;
  markdownValidationError?: string;
}

export interface CortexStepCodeSearchInput {
  query?: string;
  onlyPaths?: boolean;
  allowDirs?: boolean;
  results?: CodeSearchResultsInput[];
}

export interface CortexStepCommandStatusInput {
  commandId?: string;
  outputCharacterCount?: number;
  waitDurationSeconds?: number;
  status?: CortexStepStatus;
  combined?: string;
  delta?: string;
  exitCode?: number;
  error?: CortexErrorDetailsInput;
  waitedDurationSeconds?: number;
  stdout?: string;
  stderr?: string;
  outputPriority?: CommandOutputPriority;
}

export interface CortexStepCompile_OptionsEntryInput {
  key?: string;
  value?: string;
}

export interface CortexStepCompileAppletInput {
  errorMessage?: string;
  logs?: string;
}

export interface CortexStepCompileDiagnosticInput {
  message?: string;
  path?: string;
  line?: number;
  column?: number;
  symbol?: string;
}

export interface CortexStepCompileInput {
  tool?: CortexStepCompileTool;
  inputSpec?: string;
  options?: CortexStepCompile_OptionsEntryInput[];
  target?: string;
  artifactPath?: string;
  artifactIsExecutable?: boolean;
  errors?: CortexStepCompileDiagnosticInput[];
  warnings?: CortexStepCompileDiagnosticInput[];
}

export interface CortexStepConversationHistoryInput {
  content?: string;
}

export interface CortexStepDeleteDirectoryInput {
  directoryPathUri?: string;
  force?: boolean;
}

export interface CortexStepDeployFirebaseInput {
  errorMessage?: string;
}

export interface CortexStepDummyInput {
  input?: number;
  output?: number;
}

export interface CortexStepEditNotebook_ArgsInput {
  absolutePathUri?: string;
  operation?: EditNotebookOperation;
  anchorCellId?: string;
  anchorCellIndex?: number;
  cells?: CortexStepEditNotebook_CellInput[];
  deleteCount?: number;
}

export interface CortexStepEditNotebook_CellInput {
  kind?: string;
  content?: string;
}

export interface CortexStepEditNotebook_ModifiedCellInput {
  cellId?: string;
  kind?: string;
  content?: string;
  index?: number;
}

export interface CortexStepEditNotebook_ReplyInput {
  modifiedCells?: CortexStepEditNotebook_ModifiedCellInput[];
  totalCellCount?: number;
}

export interface CortexStepEditNotebookInput {
  toolName?: string;
  args?: CortexStepEditNotebook_ArgsInput;
  reply?: CortexStepEditNotebook_ReplyInput;
}

export interface CortexStepEphemeralMessageInput {
  content?: string;
  media?: MediaInput[];
  triggeredHeuristics?: string[];
  attachments?: MediaInput[];
  domTreeUri?: string;
}

export interface CortexStepErrorMessageInput {
  error?: CortexErrorDetailsInput;
  shouldShowUser?: boolean;
  shouldShowModel?: boolean;
}

export interface CortexStepExecuteBrowserJavaScriptInput {
  title?: string;
  pageId?: string;
  javascriptSource?: string;
  javascriptDescription?: string;
  shouldAutoRun?: boolean;
  waitingReason?: BrowserActionWaitingReason;
  userRejected?: boolean;
  screenshotEnd?: ImageDataInput;
  mediaScreenshotEnd?: MediaInput;
  pageMetadata?: BrowserPageMetadataInput;
  executionDurationMs?: bigint;
  javascriptResult?: string;
  browserStateDiff?: string;
}

export interface CortexStepExecuteNotebook_ArgsInput {
  absolutePathUri?: string;
  cellIds?: string[];
  cellIndices?: number[];
  stopOnError?: boolean;
  restartKernel?: boolean;
}

export interface CortexStepExecuteNotebook_CellOutputInput {
  cellId?: string;
  cellIndex?: number;
  status?: CortexStepExecuteNotebook_CellStatus;
  outputText?: string;
  outputTextTruncated?: boolean;
  generatedImages?: boolean;
  errorTrace?: string;
}

export interface CortexStepExecuteNotebook_ReplyInput {
  status?: CortexStepExecuteNotebook_ExecutionStatus;
  executedCellsCount?: number;
  cellOutputs?: CortexStepExecuteNotebook_CellOutputInput[];
  errorTrace?: string;
}

export interface CortexStepExecuteNotebookInput {
  toolName?: string;
  args?: CortexStepExecuteNotebook_ArgsInput;
  reply?: CortexStepExecuteNotebook_ReplyInput;
}

export interface CortexStepFileBreakdownInput {
  absolutePath?: string;
  documentOutline?: DocumentOutlineInput;
}

export interface CortexStepFileChangeInput {
  absolutePathUri?: string;
  fileChangeType?: FileChangeType;
  replacementChunks?: ReplacementChunkInput[];
  instruction?: string;
  diff?: DiffBlockInput;
  replacementInfos?: ReplacementChunkInfoInput[];
  fastApplyFallbackInfo?: FastApplyFallbackInfoInput;
  overwrite?: boolean;
}

export interface CortexStepFindAllReferencesInput {
  absoluteUri?: string;
  symbol?: string;
  line?: number;
  occurrenceIndex?: number;
  references?: LspReferenceInput[];
}

export interface CortexStepFindInput {
  searchDirectory?: string;
  pattern?: string;
  excludes?: string[];
  type?: FindResultType;
  maxDepth?: number;
  extensions?: string[];
  fullPath?: boolean;
  truncatedOutput?: string;
  truncatedTotalResults?: number;
  totalResults?: number;
  rawOutput?: string;
  commandRun?: string;
  includes?: string[];
  findError?: string;
}

export interface CortexStepFinish_OutputEntryInput {
  key?: string;
  value?: string;
}

export interface CortexStepFinishInput {
  output?: CortexStepFinish_OutputEntryInput[];
  outputString?: string;
}

export interface CortexStepGenerateImageInput {
  prompt?: string;
  imagePaths?: string[];
  imageName?: string;
  generatedImage?: ImageDataInput;
  modelName?: string;
  generatedMedia?: MediaInput;
}

export interface CortexStepGeneratorMetadataInput {
  stepIndices?: number[];
  plannerConfig?: CascadePlannerConfigInput;
  executionId?: string;
  error?: string;
  mendelExperimentIds?: number[];
  chatModel?: ChatModelMetadataInput;
  injected?: InjectedResponseMetadataInput;
}

export interface CortexStepGeneric_ArgsEntryInput {
  key?: string;
  value?: string;
}

export interface CortexStepGenericInput {
  args?: CortexStepGeneric_ArgsEntryInput[];
  result?: GenericStepResultInput;
}

export interface CortexStepGitCommitInput {
  input?: PlanInputInput;
  commitMessage?: string;
  commitHash?: string;
}

export interface CortexStepGrepSearchInput {
  searchPathUri?: string;
  query?: string;
  matchPerLine?: boolean;
  includes?: string[];
  caseInsensitive?: boolean;
  allowAccessGitignore?: boolean;
  isRegex?: boolean;
  results?: GrepSearchResultInput[];
  totalResults?: number;
  rawOutput?: string;
  commandRun?: string;
  noFilesSearched?: boolean;
  timedOut?: boolean;
  filePermissionRequest?: FilePermissionInteractionSpecInput;
  grepError?: string;
}

export interface CortexStepInstallAppletDependenciesInput {
  errorMessage?: string;
  logs?: string;
}

export interface CortexStepInstallAppletPackageInput {
  packageName?: string;
  errorMessage?: string;
  logs?: string;
  isDevDependency?: boolean;
  packageNames?: string[];
}

export interface CortexStepInternalSearchInput {
  query?: string;
  results?: InternalSearchResultsInput[];
}

export interface CortexStepInvokeSubagentInput {
  subagents?: SubagentSpecInput[];
  results?: SubagentResultInput[];
  subagentName?: string;
  prompt?: string;
  conversationId?: string;
}

export interface CortexStepKIInsertion_KiReferencesEntryInput {
  key?: string;
  value?: KnowledgeReferencesInput;
}

export interface CortexStepKIInsertionInput {
  kiReferences?: CortexStepKIInsertion_KiReferencesEntryInput[];
}

export interface CortexStepKnowledgeArtifactsInput {
  content?: string;
}

export interface CortexStepKnowledgeGenerationInput {
}

export interface CortexStepLintAppletInput {
  exitCode?: number;
  output?: string;
  errorMessage?: string;
}

export interface CortexStepLintDiffInput {
  type?: LintDiffType;
  lint?: CodeDiagnosticInput;
}

export interface CortexStepListBrowserPagesInput {
  pages?: BrowserPageMetadataInput[];
}

export interface CortexStepListDirectoryInput {
  directoryPathUri?: string;
  children?: string[];
  results?: ListDirectoryResultInput[];
  dirNotFound?: boolean;
  filePermissionRequest?: FilePermissionInteractionSpecInput;
}

export interface CortexStepListResourcesInput {
  serverName?: string;
  cursor?: string;
  resources?: McpResourceInput[];
  nextCursor?: string;
}

export interface CortexStepLookupKnowledgeBaseInput {
  urls?: string[];
  documentIds?: string[];
  knowledgeBaseItems?: KnowledgeBaseItemWithMetadataInput[];
}

export interface CortexStepManagerFeedbackInput {
  status?: CortexStepManagerFeedbackStatus;
  feedback?: string;
}

export interface CortexStepMcpToolInput {
  serverName?: string;
  toolCall?: ChatToolCallInput;
  serverInfo?: McpServerInfoInput;
  images?: ImageDataInput[];
  media?: MediaInput[];
  userRejected?: boolean;
  renderInfo?: StepRenderInfoInput;
  progressMessage?: string;
  progress?: number;
  progressTotal?: number;
  resultString?: string;
  resultUri?: string;
}

export interface CortexStepMemoryInput {
  memoryId?: string;
  memory?: CortexMemoryInput;
  prevMemory?: CortexMemoryInput;
  action?: MemoryActionType;
}

export interface CortexStepMoveInput {
  srcAbsolutePathUri?: string;
  dstAbsolutePathUri?: string;
}

export interface CortexStepMqueryInput {
  input?: PlanInputInput;
  ccis?: CciWithSubrangeWithRetrievalMetadataInput[];
  numTokensProcessed?: number;
  numItemsScored?: number;
  searchType?: SemanticCodebaseSearchType;
}

export interface CortexStepNotifyUserInput {
  reviewAbsoluteUris?: string[];
  notificationContent?: string;
  isBlocking?: boolean;
  confidenceScore?: number;
  confidenceJustification?: string;
  shouldAutoProceed?: boolean;
  diffsUri?: string;
  askForUserFeedback?: boolean;
}

export interface CortexStepOpenBrowserUrlInput {
  url?: string;
  pageIdToReplace?: string;
  autoRunDecision?: AutoRunDecision;
  userRejected?: boolean;
  pageId?: string;
  webDocument?: KnowledgeBaseItemInput;
  pageMetadata?: BrowserPageMetadataInput;
  screenshot?: ImageDataInput;
  mediaScreenshot?: MediaInput;
  browserStateDiff?: string;
}

export interface CortexStepPlanInputInput {
  planInput?: PlanInputInput;
  userProvided?: boolean;
}

export interface CortexStepPlannerResponseInput {
  response?: string;
  modifiedResponse?: string;
  thinking?: string;
  rawThinking?: string;
  signature?: string;
  thinkingSignature?: Uint8Array;
  thinkingRedacted?: boolean;
  messageId?: string;
  providerAssignedMessageId?: string;
  toolCalls?: ChatToolCallInput[];
  knowledgeBaseItems?: KnowledgeBaseItemWithMetadataInput[];
  thinkingDuration?: DurationInput;
  stopReason?: StopReason;
  recitationMetadata?: RecitationMetadataInput;
}

export interface CortexStepPostPrReviewInput {
  body?: string;
  commitId?: string;
  path?: string;
  side?: string;
  startLine?: number;
  endLine?: number;
  category?: string;
}

export interface CortexStepProposalFeedbackInput {
  acknowledgementType?: AcknowledgementType;
  targetStepIndex?: number;
  replacementChunk?: ReplacementChunkInput;
}

export interface CortexStepProposeCodeInput {
  actionSpec?: ActionSpecInput;
  actionResult?: ActionResultInput;
  codeInstruction?: string;
  markdownLanguage?: string;
}

export interface CortexStepReadBrowserPageInput {
  pageId?: string;
  webDocument?: KnowledgeBaseItemInput;
  pageMetadata?: BrowserPageMetadataInput;
}

export interface CortexStepReadNotebook_ArgsInput {
  absolutePathUri?: string;
  cellIndices?: number[];
  cellIds?: string[];
}

export interface CortexStepReadNotebook_ReplyInput {
  flattenedContent?: string;
  readCellCount?: number;
}

export interface CortexStepReadNotebookInput {
  toolName?: string;
  args?: CortexStepReadNotebook_ArgsInput;
  reply?: CortexStepReadNotebook_ReplyInput;
}

export interface CortexStepReadResourceInput {
  serverName?: string;
  uri?: string;
  contents?: McpResourceContentInput[];
  skippedNonImageBinaryContent?: boolean;
}

export interface CortexStepReadTerminalInput {
  processId?: string;
  name?: string;
  contents?: string;
}

export interface CortexStepReadUrlContentInput {
  url?: string;
  webDocument?: KnowledgeBaseItemInput;
  resolvedUrl?: string;
  latencyMs?: number;
  userRejected?: boolean;
  contentPath?: string;
}

export interface CortexStepRestartDevServerInput {
  errorMessage?: string;
}

export interface CortexStepRetrieveMemoryInput {
  runSubagent?: boolean;
  addUserMemories?: boolean;
  cascadeMemorySummary?: string;
  userMemorySummary?: string;
  reason?: string;
  showReason?: boolean;
  retrievedMemories?: CortexMemoryInput[];
  blocking?: boolean;
}

export interface CortexStepRPCActionInput {
  serviceName?: string;
  methodName?: string;
  arguments?: StructInput;
  errorMessage?: string;
  result?: StructInput;
}

export interface CortexStepRunCommandInput {
  commandLine?: string;
  proposedCommandLine?: string;
  cwd?: string;
  waitMsBeforeAsync?: bigint;
  shouldAutoRun?: boolean;
  requestedTerminalId?: string;
  sandboxOverride?: boolean;
  runPersistent?: boolean;
  blocking?: boolean;
  commandId?: string;
  exitCode?: number;
  userRejected?: boolean;
  autoRunDecision?: AutoRunDecision;
  terminalId?: string;
  combinedOutput?: RunCommandOutputInput;
  combinedOutputSnapshot?: RunCommandOutputInput;
  usedIdeTerminal?: boolean;
  rawDebugOutput?: string;
  command?: string;
  args?: string[];
  stdout?: string;
  stderr?: string;
  stdoutBuffer?: string;
  stderrBuffer?: string;
  stdoutLinesAbove?: number;
  stderrLinesAbove?: number;
  stdoutOutput?: RunCommandOutputInput;
  stderrOutput?: RunCommandOutputInput;
}

export interface CortexStepRunExtensionCodeInput {
  code?: string;
  language?: string;
  modelWantsAutoRun?: boolean;
  userFacingExplanation?: string;
  output?: string;
  userRejected?: boolean;
  autoRunDecision?: RunExtensionCodeAutoRunDecision;
}

export interface CortexStepSearchKnowledgeBaseInput {
  queries?: string[];
  timeRange?: TimeRangeInput;
  connectorTypes?: ConnectorType[];
  aggregateIds?: string[];
  knowledgeBaseGroups?: KnowledgeBaseGroupInput[];
}

export interface CortexStepSearchWebInput {
  query?: string;
  domain?: string;
  webDocuments?: KnowledgeBaseItemInput[];
  webSearchUrl?: string;
  summary?: string;
  thirdPartyConfig?: ThirdPartyWebSearchConfigInput;
  searchType?: SearchWebType;
}

export interface CortexStepSendCommandInputInput {
  commandId?: string;
  input?: string;
  shouldAutoRun?: boolean;
  terminate?: boolean;
  waitMs?: bigint;
  userRejected?: boolean;
  autoRunDecision?: AutoRunDecision;
  output?: RunCommandOutputInput;
  running?: boolean;
  exitCode?: number;
}

export interface CortexStepSetUpCloudSqlInput {
  errorMessage?: string;
  rpcErrorCode?: SetUpCloudSqlErrorCode;
  result?: SetUpCloudSqlResult;
  appConfig?: SetUpCloudSqlAppConfigInput;
}

export interface CortexStepSetUpFirebaseInput {
  errorMessage?: string;
  rpcErrorCode?: SetUpFirebaseErrorCode;
  firebaseProjectId?: string;
  request?: SetUpFirebaseRequest;
  result?: SetUpFirebaseResult;
  appConfig?: SetUpFirebaseAppConfigInput;
  firestoreRegion?: string;
  databaseId?: string;
}

export interface CortexStepShellExecInput {
  command?: string;
  exitCode?: number;
  output?: string;
  errorMessage?: string;
}

export interface CortexStepSuggestedResponsesInput {
  suggestions?: string[];
}

export interface CortexStepSystemMessageInput {
  message?: string;
  renderInfo?: StepRenderInfoInput;
  eventType?: string;
  agentMessage?: AgentMessageInput;
}

export interface CortexStepTaskBoundaryInput {
  taskName?: string;
  taskStatus?: string;
  taskSummary?: string;
  taskSummaryWithCitations?: string;
  deltaSummary?: string;
  deltaSummaryWithCitations?: string;
  mode?: AgentMode;
}

export interface CortexStepToolCallChoiceInput {
  proposalToolCalls?: ChatToolCallInput[];
  choice?: number;
  reason?: string;
}

export interface CortexStepToolCallProposalInput {
  toolCall?: ChatToolCallInput;
}

export interface CortexStepTrajectoryChoiceInput {
  proposalTrajectoryIds?: string[];
  choice?: number;
  reason?: string;
}

export interface CortexStepTrajectorySearchInput {
  id?: string;
  query?: string;
  idType?: TrajectorySearchIdType;
  chunks?: CciWithSubrangeWithRetrievalMetadataInput[];
  trajectoryDescription?: TrajectoryDescriptionInput;
  totalChunks?: number;
}

export interface CortexStepUserInputInput {
  items?: TextOrScopeItemInput[];
  userResponse?: string;
  activeUserState?: ContextModuleResultInput;
  artifactComments?: ArtifactCommentInput[];
  fileDiffComments?: FileDiffCommentInput[];
  fileComments?: FileCommentInput[];
  isQueuedMessage?: boolean;
  clientType?: ChatClientRequestStreamClientType;
  userConfig?: CascadeConfigInput;
  lastUserConfig?: CascadeConfigInput;
  query?: string;
  images?: ImageDataInput[];
  media?: MediaInput[];
}

export interface CortexStepViewCodeItemInput {
  absoluteUri?: string;
  nodePaths?: string[];
  ccis?: CodeContextItemInput[];
  filePermissionRequest?: FilePermissionInteractionSpecInput;
}

export interface CortexStepViewContentChunkInput {
  documentId?: string;
  position?: number;
  croppedItem?: KnowledgeBaseItemInput;
}

export interface CortexStepViewFileInput {
  absolutePathUri?: string;
  startLine?: number;
  endLine?: number;
  content?: string;
  isSkillFile?: boolean;
  skillMetadata?: SkillMetadataInput;
  rawContent?: string;
  binaryData?: ImageDataInput;
  mediaData?: MediaInput;
  triggeredMemories?: string;
  numLines?: number;
  numBytes?: number;
  isInjectedReminder?: boolean;
  filePermissionRequest?: FilePermissionInteractionSpecInput;
}

export interface CortexStepViewFileOutlineInput {
  absolutePathUri?: string;
  cciOffset?: number;
  ccis?: CodeContextItemInput[];
  outlineItems?: string[];
  numItemsScanned?: number;
  totalCciCount?: number;
  numLines?: number;
  numBytes?: number;
  contents?: string;
  contentLinesTruncated?: number;
  triggeredMemories?: string;
  rawContent?: string;
  filePermissionRequest?: FilePermissionInteractionSpecInput;
}

export interface CortexStepWaitInput {
  durationMs?: bigint;
}

export interface CortexStepWorkspaceAPIInput {
  url?: string;
  httpMethod?: string;
  body?: string;
  description?: string;
  statusCode?: number;
  response?: string;
}

export interface CortexStepWriteBlobInput {
  blobId?: string;
  targetPath?: string;
  errorMessage?: string;
  bytesWritten?: bigint;
}

export interface CortexStepWriteToFileInput {
  targetFileUri?: string;
  codeContent?: string[];
  diff?: DiffBlockInput;
  fileCreated?: boolean;
  acknowledgementType?: AcknowledgementType;
}

export interface CortexTrajectoryMetadataInput {
  workspaces?: CortexWorkspaceMetadataInput[];
  createdAt?: TimestampInput;
  initializationStateId?: string;
  parentConversationId?: string;
  rootConversationId?: string;
  workspaceUris?: string[];
  mappedWorkspaceUris?: string[];
  subagentSpec?: SubagentSpecInput;
  staticConfig?: CustomAgentSpecInput;
  executableSpec?: ExecutableScriptSpecInput;
  sourceMetadata?: SourceMetadataInput;
  battleModeSourceConversationId?: string;
  agentScript?: AgentScriptItemInput;
}

export interface CortexTrajectoryReferenceInput {
  trajectoryId?: string;
  trajectoryType?: CortexTrajectoryType;
  stepIndex?: number;
  stepType?: CortexStepType;
  referenceType?: CortexTrajectoryReferenceType;
}

export interface CortexWorkspaceMetadataInput {
  workspaceFolderAbsoluteUri?: string;
  gitRootAbsoluteUri?: string;
  repository?: RepositoryInput;
  branchName?: string;
}

export interface CustomAgentConfigInput {
  systemPromptSections?: PromptSectionInput[];
  toolNames?: string[];
  systemPromptConfig?: CustomAgentSystemPromptConfigInput;
  preInvocationHooks?: string[];
  postInvocationHooks?: string[];
  stopHooks?: string[];
}

export interface CustomAgentSpecInput {
  launchedMcpServers?: McpServerSpecInput[];
  commandExecutionPolicy?: string;
  enforcedWorkspaceValidation?: boolean;
  promptSectionCustomization?: PromptSectionCustomizationConfigInput;
  cascadeConfig?: CascadeConfigInput;
  customizationConfig?: CustomizationConfigInput;
  mcpServers?: McpServerSpecInput[];
  skipMcpPrefixes?: boolean;
  customTools?: string[];
  skills?: SkillsConfigInput;
  agents?: AgentDiscoveryConfigInput;
  customAgent?: CustomAgentConfigInput;
  codingAgent?: CodingAgentConfigInput;
  agentConfig?: AgentConfigInput;
  userActiveWorkspaces?: boolean;
  workspacePaths?: WorkspacePathsInput;
}

export interface CustomAgentSystemPromptConfigInput {
  includeSections?: string[];
}

export interface CustomizationConfigInput {
  customizationServerUrl?: string;
  toolNames?: string[];
  preInvocationHookNames?: string[];
  postInvocationHookNames?: string[];
  mcpServers?: McpServerSpecInput[];
  trajectoryToChatMessageOverride?: string;
  preToolHookNames?: string[];
  postToolHookNames?: string[];
  skipToolNamePrefix?: boolean;
  skipToolDescriptionPrefix?: boolean;
  stopHookNames?: string[];
  customizationDiscoveryConfig?: CustomizationDiscoveryConfigInput;
  agentPath?: string;
  enableJsonHooks?: boolean;
  userActiveWorkspaces?: boolean;
  workspacePaths?: WorkspacePathsInput;
}

export interface CustomizationDiscoveryConfigInput {
  skills?: SkillsConfigInput;
  agents?: AgentDiscoveryConfigInput;
  mcp?: McpDiscoveryConfigInput;
}

export interface CustomizationPathInput {
  agentRelative?: string;
  workspaceRelative?: string;
  absolute?: string;
}

export interface CustomPromptSectionInput {
  promptSection?: PromptSectionInput;
  insertAfterSection?: string;
  insertBeforeSection?: string;
}

export interface DeclarativeMixinConfigInput {
  providers?: FunctionProviderInput[];
  promptSections?: PromptSectionItemInput[];
  tools?: NamedItemInput[];
  preInvocationHooks?: NamedItemInput[];
  postInvocationHooks?: NamedItemInput[];
  preToolHooks?: NamedItemInput[];
  postToolHooks?: NamedItemInput[];
  stopHooks?: NamedItemInput[];
}

export interface DOMExtractionConfigInput {
  includeCoordinates?: boolean;
}

export interface ElicitationInteractionInput {
  action?: string;
  contentJson?: string;
}

export interface ElicitationInteractionSpecInput {
  serverName?: string;
  mode?: string;
  message?: string;
  requestedSchemaJson?: string;
  url?: string;
}

export interface EnterpriseToolConfigInput {
  enforceWorkspaceValidation?: boolean;
  customWorkspace?: string[];
}

export interface EphemeralMessagesConfigInput {
  enabled?: boolean;
  persistenceLevel?: EphemeralMessagePersistenceLevel;
  browserEphemeralOptions?: BrowserEphemeralOption[];
  excludeUnleashBrowserEphemeralOptions?: boolean;
  disabledHeuristics?: string[];
  numSteps?: number;
  heuristicPrompts?: HeuristicPromptInput[];
}

export interface ExecutableScriptSpecInput {
  commandSpec?: AgentScriptCommandSpecInput;
  pythonSpec?: AgentScriptPythonSpecInput;
}

export interface ExecutorMetadataInput {
  terminationReason?: ExecutorTerminationReason;
  numGeneratorInvocations?: number;
  lastStepIdx?: number;
  proceededWithAutoContinue?: boolean;
  numForcedInvocations?: number;
  segmentRecords?: MetricsRecordInput[];
  trajectoryRecords?: MetricsRecordInput[];
  genSvcRequest?: AnyInput;
  executionId?: string;
  cascadeConfig?: CascadeConfigInput;
  mendelExperimentIds?: number[];
}

export interface Experiments_ValuesEntryInput {
  key?: string;
  value?: ExperimentValueInput;
}

export interface ExperimentsInput {
  values?: Experiments_ValuesEntryInput[];
}

export interface ExperimentValueInput {
  boolValue?: boolean;
  stringValue?: string;
  numberValue?: number;
}

export interface FastApplyFallbackConfigInput {
  enabled?: boolean;
  promptUnchangedThreshold?: number;
  contentViewRadiusLines?: number;
  contentEditRadiusLines?: number;
  fastApplyModel?: Model;
  repairReplaceBlocks?: boolean;
}

export interface FastApplyFallbackInfoInput {
  fallbackAttempted?: boolean;
  fallbackError?: string;
  fastApplyResult?: ActionResultInput;
  heuristicFailure?: CodeHeuristicFailure;
  fastApplyPrompt?: string;
  numFastApplyEditsMasked?: number;
  fallbackMatchHadNoDiff?: boolean;
  usedRepairFallback?: boolean;
}

export interface FileAccessPermissionInput {
  path?: string;
  isDirectory?: boolean;
  allow?: boolean;
  scope?: PermissionScope;
  fromCurrentStep?: boolean;
}

export interface FilePermissionInteractionInput {
  allow?: boolean;
  scope?: PermissionScope;
  absolutePathUri?: string;
}

export interface FilePermissionInteractionSpecInput {
  absolutePathUri?: string;
  isDirectory?: boolean;
  blockReason?: FilePermissionInteractionSpec_BlockReason;
}

export interface FindToolConfigInput {
  maxFindResults?: number;
  fdPath?: string;
  useCodeSearch?: boolean;
  disableFallbackToLocalExecution?: boolean;
  forceDisable?: boolean;
}

export interface FinishToolConfigInput {
  resultJsonSchemaString?: string;
}

export interface FunctionProviderInput {
  name?: string;
  url?: string;
  protocol?: FunctionProvider_Protocol;
}

export interface GenerateImageToolConfigInput {
  forceDisable?: boolean;
  outputDirectory?: string;
}

export interface GenericStepResultInput {
  result?: string;
  media?: MediaInput[];
  data?: AnyInput;
  stepRenderInfo?: StepRenderInfoInput;
}

export interface GrepSearchResultInput {
  relativePath?: string;
  lineNumber?: number;
  content?: string;
  absolutePath?: string;
  cci?: CodeContextItemInput;
}

export interface GrepToolConfigInput {
  maxGrepResults?: number;
  includeCciInResult?: boolean;
  numFullSourceCcis?: number;
  maxBytesPerCci?: number;
  allowAccessGitignore?: boolean;
  useCodeSearch?: boolean;
  disableFallbackToLocalExecution?: boolean;
}

export interface HeuristicPromptInput {
  heuristic?: string;
  prompt?: string;
}

export interface ImplicitTrajectoryDescriptionInput {
  trajectoryId?: string;
  trajectoryScope?: TrajectoryScopeInput;
  current?: boolean;
}

export interface InjectedResponseMetadataInput {
}

export interface IntentToolConfigInput {
  intentModel?: Model;
  maxContextTokens?: number;
}

export interface InternalSearchResultsInput {
  url?: string;
  title?: string;
  content?: string;
}

export interface InternalSearchToolConfigInput {
  maxResults?: number;
  maxContentLength?: number;
}

export interface InvokeSubagentToolConfigInput {
  enabled?: boolean;
  fastModel?: Model;
  heavyModel?: Model;
}

export interface KnowledgeBaseSearchToolConfigInput {
  maxTokensPerKnowledgeBaseSearch?: number;
  promptFraction?: number;
}

export interface KnowledgeConfigInput {
  enabled?: boolean;
  model?: Model;
  maxContextTokens?: number;
  maxInvocations?: number;
  minTurnsBetweenKnowledgeGeneration?: number;
  maxKnowledgeItems?: number;
  maxArtifactsPerKi?: number;
  maxTitleLength?: number;
  maxSummaryLength?: number;
  enableKiInsertion?: boolean;
}

export interface KnowledgeReferenceInput {
  filePath?: string;
  conversationId?: string;
  url?: string;
}

export interface KnowledgeReferencesInput {
  references?: KnowledgeReferenceInput[];
}

export interface LineRangeTargetInput {
  absoluteUri?: string;
  startLine?: number;
  endLine?: number;
}

export interface ListDirectoryResultInput {
  name?: string;
  isDir?: boolean;
  numChildren?: number;
  sizeBytes?: bigint;
}

export interface ListDirToolConfigInput {
}

export interface LogArtifactsConfigInput {
  enabled?: boolean;
  hideNominalToolSteps?: boolean;
  hidePlannerResponseText?: boolean;
  maxBytesPerStep?: number;
  maxBytesPerToolArg?: number;
  hideSystemSteps?: boolean;
  hideUserImplicitSteps?: boolean;
}

export interface LowLevelToolsConfigInput {
  enableLowLevelToolsInstructions?: boolean;
  enableMouseTools?: boolean;
}

export interface McpDiscoveryConfigInput {
  inheritUser?: boolean;
  servers?: McpServerSpecInput[];
}

export interface McpOAuthConfigInput {
  clientId?: string;
  clientSecret?: string;
}

export interface McpPromptSpecInput {
  serverName?: string;
  name?: string;
  title?: string;
  description?: string;
  arguments?: McpPromptArgumentInput[];
}

export interface McpResourceInput {
  uri?: string;
  name?: string;
  description?: string;
  mimeType?: string;
}

export interface McpServerInfoInput {
  name?: string;
  version?: string;
}

export interface McpServerSpec_EnvEntryInput {
  key?: string;
  value?: string;
}

export interface McpServerSpec_HeadersEntryInput {
  key?: string;
  value?: string;
}

export interface McpServerSpec_ToolConfigEntryInput {
  key?: string;
  value?: McpServerToolConfigInput;
}

export interface McpServerSpecInput {
  serverName?: string;
  command?: string;
  args?: string[];
  env?: McpServerSpec_EnvEntryInput[];
  serverUrl?: string;
  disabled?: boolean;
  disabledTools?: string[];
  enabledTools?: string[];
  headers?: McpServerSpec_HeadersEntryInput[];
  cwd?: string;
  serverIndex?: number;
  skipToolNamePrefix?: boolean;
  skipToolDescriptionPrefix?: boolean;
  toolConfig?: McpServerSpec_ToolConfigEntryInput[];
  oauth?: McpOAuthConfigInput;
  authProviderType?: McpAuthProviderType;
}

export interface McpServerStateInput {
  spec?: McpServerSpecInput;
  status?: McpServerStatus;
  error?: string;
  tools?: ChatToolDefinitionInput[];
  toolErrors?: string[];
  serverInfo?: McpServerInfoInput;
  instructions?: string;
  authUrl?: string;
  hasAuthToken?: boolean;
}

export interface McpServerToolConfigInput {
  background?: McpToolBackgroundMode;
}

export interface McpToolConfigInput {
  forceDisable?: boolean;
  maxOutputBytes?: number;
}

export interface MemoryToolConfigInput {
  forceDisable?: boolean;
  disableAutoGenerateMemories?: boolean;
}

export interface MessageConfigInput {
  enabled?: boolean;
}

export interface MessagePromptMetadataInput {
  messageIndex?: number;
  segmentIndex?: number;
}

export interface MessageRenderDetailsInput {
  messageTitle?: string;
}

export interface ModelAPIRetryConfigInput {
  maxRetries?: number;
  initialSleepDurationMs?: number;
  exponentialMultiplier?: number;
  includeErrorFeedback?: boolean;
  range?: number;
}

export interface ModelOutputRetryConfigInput {
  maxRetries?: number;
  forbidToolUse?: boolean;
  forceToolName?: string;
}

export interface MqueryToolConfigInput {
  mQueryConfig?: MQueryConfigInput;
  mQueryModel?: Model;
  maxTokensPerMQuery?: number;
  numItemsFullSource?: number;
  maxLinesPerSnippet?: number;
  enableSearchInFileTool?: boolean;
  allowAccessGitignore?: boolean;
  disableSemanticCodebaseSearch?: boolean;
  forceDisable?: boolean;
}

export interface NamedItemInput {
  name?: string;
  pattern?: string;
  builtin?: boolean;
  providerName?: string;
}

export interface NewConversationEventInput {
  prompt?: string;
  conversationId?: string;
}

export interface NotebookEditToolConfigInput {
  enabled?: boolean;
}

export interface NotifyUserConfigInput {
  artifactReviewMode?: ArtifactReviewMode;
}

export interface PermissionConfigInput {
  enterpriseConfig?: EnterpriseToolConfigInput;
  globalPermissionGrants?: PermissionGrantsConfigInput;
}

export interface PermissionGrantInput {
  resource?: PermissionResourceInput;
  allow?: boolean;
  scope?: PermissionScope;
}

export interface PermissionInteractionInput {
  allow?: boolean;
  scope?: PermissionScope;
  sandboxOverride?: boolean;
}

export interface PermissionInteractionSpecInput {
  resource?: PermissionResourceInput;
}

export interface PermissionResourceInput {
  action?: string;
  target?: string;
}

export interface PlanEntryDeltaSummaryInput {
  itemsAdded?: string[];
  itemsCompleted?: string[];
}

export interface PlanInputInput {
  goal?: string;
  nextSteps?: string[];
  targetDirectories?: string[];
  targetFiles?: string[];
  scopeItems?: ContextScopeItemInput[];
}

export interface PlannerRetryConfigInput {
  modelOutputRetry?: ModelOutputRetryConfigInput;
  apiRetry?: ModelAPIRetryConfigInput;
}

export interface PluginItemInput {
  name?: string;
  description?: string;
  disabled?: boolean;
}

export interface PromptSectionCustomizationConfigInput {
  removePromptSections?: string[];
  addPromptSections?: CustomPromptSectionInput[];
  appendPromptSections?: PromptSectionInput[];
  replacePromptSections?: PromptSectionInput[];
}

export interface PromptSectionInput {
  title?: string;
  content?: string;
  criteria?: SectionJudgeCriteriaInput[];
  dynamicContent?: string;
  tokenType?: TokenType;
  tokenSource?: TokenSource;
  templatedContent?: string;
  templatedDynamicContent?: string;
}

export interface PromptSectionItemInput {
  custom?: PromptSectionInput;
  builtinName?: string;
}

export interface ReadKnowledgeBaseItemToolConfigInput {
  enabled?: boolean;
  knowledgeBaseItems?: KnowledgeBaseItemInput[];
}

export interface ReplaceContentToolConfigInput {
  maxFuzzyEditDistanceFraction?: number;
  allowPartialReplacementSuccess?: boolean;
  viewFileRecencyMaxDistance?: number;
  enableFuzzySandwichMatch?: boolean;
  fastApplyFallbackConfig?: FastApplyFallbackConfigInput;
  toolVariant?: ReplaceToolVariant;
  showTriggeredMemories?: boolean;
  disableAllowMultiple?: boolean;
  useLineRange?: boolean;
}

export interface ReplacementChunkInfoInput {
  originalChunk?: ReplacementChunkInput;
  fuzzyMatch?: string;
  editDistance?: number;
  relEditDistance?: number;
  numMatches?: number;
  isNonExact?: boolean;
  boundaryLinesMatch?: boolean;
  error?: boolean;
  errorStr?: string;
  fastApplyFixable?: boolean;
  useGlobalMatch?: boolean;
  repairFixable?: boolean;
  repaired?: boolean;
}

export interface ReplacementChunkInput {
  targetContent?: string;
  replacementContent?: string;
  allowMultiple?: boolean;
  targetHasCarriageReturn?: boolean;
  contextLines?: string[];
  startLine?: number;
  endLine?: number;
  acknowledgementType?: AcknowledgementType;
  index?: number;
}

export interface RequestedInteractionInput {
  deploy?: CascadeDeployInteractionSpecInput;
  runCommand?: CascadeRunCommandInteractionSpecInput;
  openBrowserUrl?: CascadeOpenBrowserUrlInteractionSpecInput;
  runExtensionCode?: CascadeRunExtensionCodeInteractionSpecInput;
  executeBrowserJavascript?: CascadeExecuteBrowserJavaScriptInteractionSpecInput;
  captureBrowserScreenshot?: CascadeCaptureBrowserScreenshotInteractionSpecInput;
  clickBrowserPixel?: CascadeClickBrowserPixelInteractionSpecInput;
  browserAction?: CascadeBrowserActionInteractionInput;
  openBrowserSetup?: CascadeOpenBrowserSetupInteractionInput;
  confirmBrowserSetup?: CascadeConfirmBrowserSetupInteractionInput;
  sendCommandInput?: CascadeSendCommandInputInteractionSpecInput;
  readUrlContent?: CascadeReadUrlContentInteractionSpecInput;
  mcp?: CascadeMcpInteractionSpecInput;
  filePermission?: FilePermissionInteractionSpecInput;
  elicitation?: ElicitationInteractionSpecInput;
  permission?: PermissionInteractionSpecInput;
  askQuestion?: AskQuestionInteractionSpecInput;
  approvalInteraction?: ApprovalInteractionSpecInput;
}

export interface RetryInfoInput {
  sherlogLink?: string;
  usage?: ModelUsageStatsInput;
  error?: string;
  traceId?: string;
  retryReason?: RetryReason;
  consumedCredits?: CreditsInput[];
}

export interface RunCommandOutputInput {
  full?: string;
  truncated?: string;
  numLinesAbove?: number;
}

export interface RunCommandToolConfigInput {
  maxCharsCommandStdout?: number;
  forceDisable?: boolean;
  autoCommandConfig?: AutoCommandConfigInput;
  enableIdeTerminalExecution?: boolean;
  forceGoTerminalExecution?: boolean;
  shellName?: string;
  shellPath?: string;
  maxTimeoutMs?: number;
  shellSetupScript?: string;
  forbidSearchCommands?: boolean;
  enablePty?: boolean;
  enablePersistentMode?: boolean;
  enableMidtermOutputProcessor?: boolean;
}

export interface SearchWebToolConfigInput {
  forceDisable?: boolean;
  thirdPartyConfig?: ThirdPartyWebSearchConfigInput;
}

export interface SectionJudgeCriteriaInput {
  name?: string;
  description?: string;
  weight?: number;
}

export interface SectionOverrideConfigInput {
  mode?: SectionOverrideMode;
  content?: string;
}

export interface SendMessageEventInput {
  recipientId?: string;
  content?: string;
}

export interface SetUpCloudSqlAppConfigInput {
  instanceName?: string;
  projectId?: string;
}

export interface SetUpFirebaseAppConfigInput {
  firebaseProjectId?: string;
}

export interface SidecarCommandSourceInput {
  sidecarId?: string;
  config?: SidecarConfigInput;
}

export interface SidecarConfigInput {
  command?: string;
  restartPolicy?: string;
  args?: string[];
  disabled?: boolean;
  description?: string;
}

export interface SidecarEventInput {
  timestampMs?: bigint;
  commandInvocationTimestampMs?: bigint;
  error?: string;
  payload?: SidecarEventPayloadInput;
}

export interface SidecarEventPayloadInput {
  sendMessage?: SendMessageEventInput;
  newConversation?: NewConversationEventInput;
}

export interface SidecarStatusInfoInput {
  sidecarId?: string;
  config?: SidecarConfigInput;
  status?: SidecarStatus;
  lastError?: string;
  startTimeMs?: bigint;
  webPort?: number;
  uiConfig?: SidecarUIConfigInput;
}

export interface SidecarUIConfigInput {
  displayName?: string;
  views?: SidecarUIViewInput[];
}

export interface SidecarUIViewInput {
  url?: string;
  entrypoint?: SidecarUIEntrypoint;
}

export interface SkillMetadataInput {
  name?: string;
  description?: string;
  publisher?: string;
  version?: string;
}

export interface SkillsConfigInput {
  inheritUser?: boolean;
  skillsPaths?: CustomizationPathInput[];
}

export interface SourceMetadataInput {
  tool?: ToolSourceMetadataInput;
  sidecar?: SidecarCommandSourceInput;
}

export interface StepRenderInfoInput {
  title?: string;
  markdown?: string;
  hidden?: boolean;
}

export interface StepStringConverterConfigInput {
  codeAcknowledgement?: CodeAcknowledgementConverterConfigInput;
}

export interface StructuredErrorPartInput {
  text?: string;
  fileUri?: string;
  directoryUri?: string;
  url?: string;
  codeText?: string;
}

export interface SubagentReminderModeInput {
  verifyScreenshots?: BrowserVerifyScreenshotsModeInput;
  verifyCompleteness?: BrowserVerifyCompletenessModeInput;
  custom?: BrowserCustomReminderModeInput;
}

export interface SubagentResultInput {
  conversationId?: string;
  logAbsoluteUri?: string;
  workspaceUris?: string[];
}

export interface SubagentSnapshotInput {
  spec?: SubagentSpecInput;
  result?: SubagentResultInput;
}

export interface SubagentSpecInput {
  typeName?: string;
  role?: string;
  initialPrompt?: string;
  model?: Model;
  inherit?: boolean;
  branch?: string;
  workspaceUri?: string;
}

export interface SuggestedResponseConfigInput {
  forceDisable?: boolean;
}

export interface TaskBoundaryToolConfigInput {
  minimumPredictedTaskSize?: number;
  targetStatusUpdateFrequency?: number;
  noActiveTaskSoftReminderToolThreshold?: number;
  noActiveTaskStrictReminderToolThreshold?: number;
}

export interface TaskDeltaInput {
  type?: TaskDeltaType;
  id?: string;
  content?: string;
  status?: TaskStatus;
  parentId?: string;
  prevSiblingId?: string;
  fromParent?: string;
  fromPrevSibling?: string;
}

export interface TaskEntryDeltaSummaryInput {
  deltas?: TaskDeltaInput[];
  itemsAdded?: number;
  itemsPruned?: number;
  itemsDeleted?: number;
  itemsUpdated?: number;
  itemsMoved?: number;
}

export interface TaskSnapshotInput {
  taskId?: string;
  toolName?: string;
  toolSummary?: string;
  description?: string;
  startTime?: TimestampInput;
  stepIndex?: number;
}

export interface TokenBreakdownInput {
  groups?: TopLevelTokenGroupInput[];
  totalTokens?: number;
}

export interface TokenGroupInput {
  name?: string;
  children?: TokenGroupInput[];
  numTokens?: number;
}

export interface ToolDescriptionOverrideMap_DescriptionsEntryInput {
  key?: string;
  value?: SectionOverrideConfigInput;
}

export interface ToolDescriptionOverrideMap_ToolOverridesEntryInput {
  key?: string;
  value?: ToolOverrideConfigInput;
}

export interface ToolDescriptionOverrideMapInput {
  descriptions?: ToolDescriptionOverrideMap_DescriptionsEntryInput[];
  toolOverrides?: ToolDescriptionOverrideMap_ToolOverridesEntryInput[];
}

export interface ToolOverrideConfig_ArgumentDescriptionOverridesEntryInput {
  key?: string;
  value?: string;
}

export interface ToolOverrideConfig_ArgumentNameOverridesEntryInput {
  key?: string;
  value?: string;
}

export interface ToolOverrideConfigInput {
  nameOverride?: string;
  argumentNameOverrides?: ToolOverrideConfig_ArgumentNameOverridesEntryInput[];
  descriptionOverride?: SectionOverrideConfigInput;
  argumentDescriptionOverrides?: ToolOverrideConfig_ArgumentDescriptionOverridesEntryInput[];
}

export interface ToolSourceMetadataInput {
  conversationId?: string;
  stepIndex?: number;
  toolCall?: ChatToolCallInput;
}

export interface TopLevelTokenGroupInput {
  name?: string;
  type?: TokenType;
  source?: TokenSource;
  numTokens?: number;
  children?: TokenGroupInput[];
}

export interface TrajectoryConversionConfigInput {
  groupToolsWithPlannerResponse?: boolean;
  wrapToolResponses?: boolean;
  logArtifactsConfig?: LogArtifactsConfigInput;
  appendEphemeralToPreviousToolResult?: boolean;
  disableStepId?: boolean;
  enableToolTimestamp?: boolean;
  useRawUserMessage?: boolean;
}

export interface TrajectoryDescriptionInput {
  cascadeConversationTitle?: string;
  mainlineBranchName?: string;
}

export interface TrajectoryFileDiffInput {
  uri?: string;
  originalContent?: string;
  modifiedContent?: string;
  isArtifactFile?: boolean;
  isKnowledgeFile?: boolean;
  lastModifiedAt?: TimestampInput;
  hasModelEdited?: boolean;
}

export interface TrajectoryPermissionsInput {
  fileAccessPermissions?: FileAccessPermissionInput[];
  permissionGrants?: PermissionGrantInput[];
}

export interface TrajectoryScopeInput {
  workspaceUri?: string;
  gitRootUri?: string;
  branchName?: string;
}

export interface TrajectorySearchToolConfigInput {
  forceDisable?: boolean;
  conversationsEnabled?: boolean;
  userActivitiesEnabled?: boolean;
  maxScoredChunks?: number;
}

export interface UserStepAnnotationsInput {
  snapshot?: UserStepSnapshotInput;
}

export interface UserStepSnapshotInput {
  name?: string;
}

export interface ViewCodeItemToolConfigInput {
  maxNumItems?: number;
  maxBytesPerItem?: number;
  allowAccessGitignore?: boolean;
}

export interface ViewFileToolConfigInput {
  allowViewGitignore?: boolean;
  splitOutlineTool?: boolean;
  showTriggeredMemories?: boolean;
  maxLinesPerView?: number;
  includeLineNumbers?: boolean;
  dirAllowlist?: string[];
  maxTotalOutlineBytes?: number;
  maxBytesPerOutlineItem?: number;
  showFullFileBytes?: number;
}

export interface WorkflowSpecInput {
  path?: string;
  name?: string;
  description?: string;
  content?: string;
  turbo?: boolean;
  isBuiltin?: boolean;
  scope?: CortexMemoryScopeInput;
  baseDir?: string;
  disableModelInvocation?: boolean;
}

export interface WorkspaceAPIToolConfigInput {
  readOnly?: boolean;
}

export interface WorkspacePathsInput {
  absolutePaths?: string[];
}
