syntax = "proto3";

package google.rpc;

import "google/protobuf/any.proto";

// The `Status` type defines a logical error model that is suitable for
// different programming environments, including REST APIs and RPC APIs.
message Status {
  // The status code, which should be an enum value of google.rpc.Code.
  int32 code = 1;

  // A developer-facing error message, which should be in English.
  string message = 2;

  // A list of messages that carry the error details.
  repeated google.protobuf.Any details = 3;
}
