// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

export interface CascadePluginCommandInput {
  template?: CascadePluginCommandTemplateInput;
  variables?: CascadePluginCommandVariableInput[];
}

export interface CascadePluginCommandTemplate_EnvEntryInput {
  key?: string;
  value?: string;
}

export interface CascadePluginCommandTemplateInput {
  command?: string;
  args?: string[];
  env?: CascadePluginCommandTemplate_EnvEntryInput[];
}

export interface CascadePluginCommandVariableInput {
  name?: string;
  title?: string;
  description?: string;
  link?: string;
}

export interface CascadePluginLocalConfig_CommandsEntryInput {
  key?: string;
  value?: CascadePluginCommandInput;
}

export interface CascadePluginLocalConfigInput {
  commands?: CascadePluginLocalConfig_CommandsEntryInput[];
}

export interface CascadePluginRemoteConfigInput {
  template?: CascadePluginRemoteConfigTemplateInput;
}

export interface CascadePluginRemoteConfigTemplate_HeadersEntryInput {
  key?: string;
  value?: string;
}

export interface CascadePluginRemoteConfigTemplateInput {
  serverUrl?: string;
  headers?: CascadePluginRemoteConfigTemplate_HeadersEntryInput[];
  authProviderType?: string;
}

export interface CascadePluginTemplate_CommandsEntryInput {
  key?: string;
  value?: CascadePluginCommandInput;
}

export interface CascadePluginTemplateInput {
  title?: string;
  id?: string;
  link?: string;
  description?: string;
  commands?: CascadePluginTemplate_CommandsEntryInput[];
  installationCount?: bigint;
  trustLevel?: string;
  readme?: string;
  local?: CascadePluginLocalConfigInput;
  remote?: CascadePluginRemoteConfigInput;
}
