// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { NullValue } from "@bufbuild/protobuf";

export interface ListValueInput {
  values?: ValueInput[];
}

export interface StructInput {
  fields?: Record<string, ValueInput>;
}

export interface ValueInput {
  nullValue?: NullValue;
  numberValue?: number;
  stringValue?: string;
  boolValue?: boolean;
  structValue?: StructInput;
  listValue?: ListValueInput;
}
