
import * as fs from "fs";
import * as path from "path";

/**
 * generate-event-types.ts
 * 
 * trajectory_pb.ts から Step の全種類を抽出し、
 * Cascade 用の型安全なイベント定義を自動生成します。
 */

const PROTO_PATH = path.join(process.cwd(), "src/gen/exa/gemini_coder/proto/trajectory_pb.ts");
const OUTPUT_PATH = path.join(process.cwd(), "src/event-types.ts");

function generate() {
    console.log(`Reading proto definitions from: ${PROTO_PATH}`);
    const content = fs.readFileSync(PROTO_PATH, "utf-8");

    // "case: \"name\"" というパターンをすべて抽出
    const stepCases = Array.from(content.matchAll(/case: "(.*?)"/g)).map(m => m[1]);
    const uniqueCases = Array.from(new Set(stepCases)).sort();

    console.log(`Found ${uniqueCases.length} step cases.`);

    let code = `/**
 * AUTO-GENERATED EVENT TYPES
 * Do not edit this file manually. Run scripts/generate-event-types.ts instead.
 */

import { Step } from "./gen/exa/gemini_coder/proto/trajectory_pb.js";

/** 
 * Step 型から動的に Value 型を抽出するヘルパー 
 */
type StepValue<T extends string> = Extract<NonNullable<Step["step"]>, { case: T }>["value"];

/**
 * Cascade で利用可能な全イベント定数
 */
export const CascadeEvents = {
    // Basic Events
    Text: "text" as const,
    Thinking: "thinking" as const,
    Interaction: "interaction" as const,
    CommandOutput: "commandOutput" as const,
    StepNew: "stepNew" as const,
    StepUpdate: "stepUpdate" as const,
    StatusChange: "statusChange" as const,
    Error: "error" as const,
    Done: "done" as const,
    RawUpdate: "rawUpdate" as const,
    All: "all" as const,
    Other: "other" as const,

    // Auto-generated Step-specific Events
`;

    // Step ごとの定数を生成 (例: RunCommand: "step:runCommand")
    uniqueCases.forEach(c => {
        const key = c.charAt(0).toUpperCase() + c.slice(1);
        code += `    ${key}: "step:${c}" as const,\n`;
    });

    code += `} as const;\n\n`;

    code += `/**
 * イベント名とペイロードの型マッピング
 */
export interface CascadeEventPayloads {
    "text": { delta: string; fullText: string; stepIndex: number };
    "thinking": { delta: string; fullText: string; stepIndex: number };
    "interaction": import("./types.js").ApprovalRequest;
    "commandOutput": { delta: string; fullText: string; stream: "stdout" | "stderr"; stepIndex: number };
    "stepNew": { step: import("./types.js").CascadeStep };
    "stepUpdate": { step: import("./types.js").CascadeStep; previousStatus: import("./types.js").StepStatus };
    "statusChange": { status: import("./types.js").RunStatus; previousStatus: import("./types.js").RunStatus };
    "error": any;
    "done": {};
    "rawUpdate": import("./gen/exa/jetski_cortex_pb/jetski_cortex_pb.js").CascadeState;
    "all": { event: string; data: any };
    "other": import("./types.js").CascadeStep;

    // Auto-generated Step Payload Mappings
`;

    uniqueCases.forEach(c => {
        code += `    "step:${c}": import("./types.js").CascadeStep & { type: "${c}", value: StepValue<"${c}"> };\n`;
    });

    code += `}\n`;

    fs.writeFileSync(OUTPUT_PATH, code);
    console.log(`✅ Successfully generated ${OUTPUT_PATH}`);
}

generate();
