// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file exa/index_pb.proto (package exa.index_pb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { CodeContextItem, GitRepoInfo, ScmProvider, WorkspacePath } from "./codeium_common_pb_pb.js";

/**
 * @generated from enum exa.index_pb.IndexMode
 */
export enum IndexMode {
  /**
   * @generated from enum value: INDEX_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INDEX_MODE_HALFVEC = 1;
   */
  HALFVEC = 1,

  /**
   * @generated from enum value: INDEX_MODE_BINARY = 2;
   */
  BINARY = 2,

  /**
   * @generated from enum value: INDEX_MODE_BINARY_WITH_RERANK = 3;
   */
  BINARY_WITH_RERANK = 3,

  /**
   * @generated from enum value: INDEX_MODE_BRUTE_FORCE = 4;
   */
  BRUTE_FORCE = 4,

  /**
   * @generated from enum value: INDEX_MODE_RANDOM_SEARCH = 5;
   */
  RANDOM_SEARCH = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(IndexMode)
proto3.util.setEnumType(IndexMode, "exa.index_pb.IndexMode", [
  { no: 0, name: "INDEX_MODE_UNSPECIFIED" },
  { no: 1, name: "INDEX_MODE_HALFVEC" },
  { no: 2, name: "INDEX_MODE_BINARY" },
  { no: 3, name: "INDEX_MODE_BINARY_WITH_RERANK" },
  { no: 4, name: "INDEX_MODE_BRUTE_FORCE" },
  { no: 5, name: "INDEX_MODE_RANDOM_SEARCH" },
]);

/**
 * @generated from enum exa.index_pb.IndexingStatus
 */
export enum IndexingStatus {
  /**
   * @generated from enum value: INDEXING_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INDEXING_STATUS_ERROR = 1;
   */
  ERROR = 1,

  /**
   * @generated from enum value: INDEXING_STATUS_QUEUED = 2;
   */
  QUEUED = 2,

  /**
   * @generated from enum value: INDEXING_STATUS_CLONING_REPO = 3;
   */
  CLONING_REPO = 3,

  /**
   * @generated from enum value: INDEXING_STATUS_SCANNING_REPO = 4;
   */
  SCANNING_REPO = 4,

  /**
   * @generated from enum value: INDEXING_STATUS_GENERATING_EMBEDDINGS = 5;
   */
  GENERATING_EMBEDDINGS = 5,

  /**
   * @generated from enum value: INDEXING_STATUS_VECTOR_INDEXING = 6;
   */
  VECTOR_INDEXING = 6,

  /**
   * @generated from enum value: INDEXING_STATUS_DONE = 7;
   */
  DONE = 7,

  /**
   * @generated from enum value: INDEXING_STATUS_CANCELING = 8;
   */
  CANCELING = 8,

  /**
   * @generated from enum value: INDEXING_STATUS_CANCELED = 9;
   */
  CANCELED = 9,
}
// Retrieve enum metadata with: proto3.getEnumType(IndexingStatus)
proto3.util.setEnumType(IndexingStatus, "exa.index_pb.IndexingStatus", [
  { no: 0, name: "INDEXING_STATUS_UNSPECIFIED" },
  { no: 1, name: "INDEXING_STATUS_ERROR" },
  { no: 2, name: "INDEXING_STATUS_QUEUED" },
  { no: 3, name: "INDEXING_STATUS_CLONING_REPO" },
  { no: 4, name: "INDEXING_STATUS_SCANNING_REPO" },
  { no: 5, name: "INDEXING_STATUS_GENERATING_EMBEDDINGS" },
  { no: 6, name: "INDEXING_STATUS_VECTOR_INDEXING" },
  { no: 7, name: "INDEXING_STATUS_DONE" },
  { no: 8, name: "INDEXING_STATUS_CANCELING" },
  { no: 9, name: "INDEXING_STATUS_CANCELED" },
]);

/**
 * @generated from message exa.index_pb.BackupMessage
 */
export class BackupMessage extends Message<BackupMessage> {
  /**
   * @generated from field: bytes data = 1;
   */
  data = new Uint8Array(0);

  constructor(data?: PartialMessage<BackupMessage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.BackupMessage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackupMessage {
    return new BackupMessage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackupMessage {
    return new BackupMessage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackupMessage {
    return new BackupMessage().fromJsonString(jsonString, options);
  }

  static equals(a: BackupMessage | PlainMessage<BackupMessage> | undefined, b: BackupMessage | PlainMessage<BackupMessage> | undefined): boolean {
    return proto3.util.equals(BackupMessage, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexDbVersion
 */
export class IndexDbVersion extends Message<IndexDbVersion> {
  /**
   * @generated from field: int32 version = 1;
   */
  version = 0;

  /**
   * @generated from field: int32 enterprise_version = 2;
   */
  enterpriseVersion = 0;

  constructor(data?: PartialMessage<IndexDbVersion>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexDbVersion";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "enterprise_version", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexDbVersion {
    return new IndexDbVersion().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexDbVersion {
    return new IndexDbVersion().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexDbVersion {
    return new IndexDbVersion().fromJsonString(jsonString, options);
  }

  static equals(a: IndexDbVersion | PlainMessage<IndexDbVersion> | undefined, b: IndexDbVersion | PlainMessage<IndexDbVersion> | undefined): boolean {
    return proto3.util.equals(IndexDbVersion, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexBuildConfig
 */
export class IndexBuildConfig extends Message<IndexBuildConfig> {
  /**
   * @generated from field: exa.index_pb.IndexDbVersion db_version = 2;
   */
  dbVersion?: IndexDbVersion;

  /**
   * @generated from field: int32 cci_timeout_secs = 3;
   */
  cciTimeoutSecs = 0;

  /**
   * @generated from field: exa.index_pb.IndexMode index_mode = 4;
   */
  indexMode = IndexMode.UNSPECIFIED;

  constructor(data?: PartialMessage<IndexBuildConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexBuildConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "db_version", kind: "message", T: IndexDbVersion },
    { no: 3, name: "cci_timeout_secs", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "index_mode", kind: "enum", T: proto3.getEnumType(IndexMode) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexBuildConfig {
    return new IndexBuildConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexBuildConfig {
    return new IndexBuildConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexBuildConfig {
    return new IndexBuildConfig().fromJsonString(jsonString, options);
  }

  static equals(a: IndexBuildConfig | PlainMessage<IndexBuildConfig> | undefined, b: IndexBuildConfig | PlainMessage<IndexBuildConfig> | undefined): boolean {
    return proto3.util.equals(IndexBuildConfig, a, b);
  }
}

/**
 * @generated from message exa.index_pb.RepositoryConfig
 */
export class RepositoryConfig extends Message<RepositoryConfig> {
  /**
   * @generated from field: string git_url = 1;
   */
  gitUrl = "";

  /**
   * @generated from field: exa.codeium_common_pb.ScmProvider scm_provider = 2;
   */
  scmProvider = ScmProvider.UNSPECIFIED;

  /**
   * @generated from field: exa.index_pb.RepositoryConfig_AutoIndexConfig auto_index_config = 3;
   */
  autoIndexConfig?: RepositoryConfig_AutoIndexConfig;

  /**
   * @generated from field: bool store_snippets = 4;
   */
  storeSnippets = false;

  /**
   * @generated from field: repeated string whitelisted_groups = 5;
   */
  whitelistedGroups: string[] = [];

  /**
   * @generated from field: bool use_github_app = 6;
   */
  useGithubApp = false;

  /**
   * @generated from field: string auth_uid = 7;
   */
  authUid = "";

  /**
   * @generated from field: string email = 9;
   */
  email = "";

  /**
   * @generated from field: string service_key_id = 8;
   */
  serviceKeyId = "";

  constructor(data?: PartialMessage<RepositoryConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.RepositoryConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "git_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "scm_provider", kind: "enum", T: proto3.getEnumType(ScmProvider) },
    { no: 3, name: "auto_index_config", kind: "message", T: RepositoryConfig_AutoIndexConfig },
    { no: 4, name: "store_snippets", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "whitelisted_groups", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "use_github_app", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "auth_uid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "service_key_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RepositoryConfig {
    return new RepositoryConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RepositoryConfig {
    return new RepositoryConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RepositoryConfig {
    return new RepositoryConfig().fromJsonString(jsonString, options);
  }

  static equals(a: RepositoryConfig | PlainMessage<RepositoryConfig> | undefined, b: RepositoryConfig | PlainMessage<RepositoryConfig> | undefined): boolean {
    return proto3.util.equals(RepositoryConfig, a, b);
  }
}

/**
 * @generated from message exa.index_pb.RepositoryConfig_AutoIndexConfig
 */
export class RepositoryConfig_AutoIndexConfig extends Message<RepositoryConfig_AutoIndexConfig> {
  /**
   * @generated from field: string branch_name = 1;
   */
  branchName = "";

  /**
   * @generated from field: google.protobuf.Duration interval = 2;
   */
  interval?: Duration;

  /**
   * @generated from field: int32 max_num_auto_indexes = 3;
   */
  maxNumAutoIndexes = 0;

  constructor(data?: PartialMessage<RepositoryConfig_AutoIndexConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.RepositoryConfig_AutoIndexConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "branch_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "interval", kind: "message", T: Duration },
    { no: 3, name: "max_num_auto_indexes", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RepositoryConfig_AutoIndexConfig {
    return new RepositoryConfig_AutoIndexConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RepositoryConfig_AutoIndexConfig {
    return new RepositoryConfig_AutoIndexConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RepositoryConfig_AutoIndexConfig {
    return new RepositoryConfig_AutoIndexConfig().fromJsonString(jsonString, options);
  }

  static equals(a: RepositoryConfig_AutoIndexConfig | PlainMessage<RepositoryConfig_AutoIndexConfig> | undefined, b: RepositoryConfig_AutoIndexConfig | PlainMessage<RepositoryConfig_AutoIndexConfig> | undefined): boolean {
    return proto3.util.equals(RepositoryConfig_AutoIndexConfig, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexConfig
 */
export class IndexConfig extends Message<IndexConfig> {
  /**
   * @generated from field: google.protobuf.Timestamp prune_time = 1;
   */
  pruneTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Duration prune_interval = 2;
   */
  pruneInterval?: Duration;

  /**
   * @generated from field: bool enable_prune = 3;
   */
  enablePrune = false;

  /**
   * @generated from field: bool enable_smallest_repo_first = 4;
   */
  enableSmallestRepoFirst = false;

  /**
   * @generated from field: bool enable_round_robin = 5;
   */
  enableRoundRobin = false;

  constructor(data?: PartialMessage<IndexConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prune_time", kind: "message", T: Timestamp },
    { no: 2, name: "prune_interval", kind: "message", T: Duration },
    { no: 3, name: "enable_prune", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "enable_smallest_repo_first", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "enable_round_robin", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexConfig {
    return new IndexConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexConfig {
    return new IndexConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexConfig {
    return new IndexConfig().fromJsonString(jsonString, options);
  }

  static equals(a: IndexConfig | PlainMessage<IndexConfig> | undefined, b: IndexConfig | PlainMessage<IndexConfig> | undefined): boolean {
    return proto3.util.equals(IndexConfig, a, b);
  }
}

/**
 * @generated from message exa.index_pb.VectorIndexStats
 */
export class VectorIndexStats extends Message<VectorIndexStats> {
  /**
   * @generated from field: int64 num_embeddings = 1;
   */
  numEmbeddings = protoInt64.zero;

  /**
   * @generated from field: int64 index_bytes_count = 2;
   */
  indexBytesCount = protoInt64.zero;

  constructor(data?: PartialMessage<VectorIndexStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.VectorIndexStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "num_embeddings", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "index_bytes_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VectorIndexStats {
    return new VectorIndexStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VectorIndexStats {
    return new VectorIndexStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VectorIndexStats {
    return new VectorIndexStats().fromJsonString(jsonString, options);
  }

  static equals(a: VectorIndexStats | PlainMessage<VectorIndexStats> | undefined, b: VectorIndexStats | PlainMessage<VectorIndexStats> | undefined): boolean {
    return proto3.util.equals(VectorIndexStats, a, b);
  }
}

/**
 * @generated from message exa.index_pb.ProgressBar
 */
export class ProgressBar extends Message<ProgressBar> {
  /**
   * @generated from field: float progress = 1;
   */
  progress = 0;

  /**
   * @generated from field: string text = 2;
   */
  text = "";

  /**
   * @generated from field: google.protobuf.Duration remaining_time = 3;
   */
  remainingTime?: Duration;

  constructor(data?: PartialMessage<ProgressBar>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.ProgressBar";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "progress", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 2, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "remaining_time", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProgressBar {
    return new ProgressBar().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProgressBar {
    return new ProgressBar().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProgressBar {
    return new ProgressBar().fromJsonString(jsonString, options);
  }

  static equals(a: ProgressBar | PlainMessage<ProgressBar> | undefined, b: ProgressBar | PlainMessage<ProgressBar> | undefined): boolean {
    return proto3.util.equals(ProgressBar, a, b);
  }
}

/**
 * @generated from message exa.index_pb.Index
 */
export class Index extends Message<Index> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string repo_name = 2;
   */
  repoName = "";

  /**
   * @generated from field: string workspace = 3;
   */
  workspace = "";

  /**
   * @generated from field: exa.codeium_common_pb.GitRepoInfo repo_info = 4;
   */
  repoInfo?: GitRepoInfo;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp scheduled_at = 13;
   */
  scheduledAt?: Timestamp;

  /**
   * @generated from field: exa.index_pb.IndexingStatus status = 7;
   */
  status = IndexingStatus.UNSPECIFIED;

  /**
   * @generated from field: string status_detail = 8;
   */
  statusDetail = "";

  /**
   * @generated from field: bool auto_indexed = 9;
   */
  autoIndexed = false;

  /**
   * @generated from field: bool has_snippets = 12;
   */
  hasSnippets = false;

  /**
   * @generated from field: string auth_uid = 15;
   */
  authUid = "";

  /**
   * @generated from field: string email = 16;
   */
  email = "";

  /**
   * @generated from field: exa.index_pb.Index_RepoStats repo_stats = 14;
   */
  repoStats?: Index_RepoStats;

  /**
   * @generated from field: map<string, exa.index_pb.ProgressBar> indexing_progress = 10;
   */
  indexingProgress: { [key: string]: ProgressBar } = {};

  /**
   * @generated from field: exa.index_pb.VectorIndexStats index_stats = 11;
   */
  indexStats?: VectorIndexStats;

  constructor(data?: PartialMessage<Index>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.Index";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "workspace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "repo_info", kind: "message", T: GitRepoInfo },
    { no: 5, name: "created_at", kind: "message", T: Timestamp },
    { no: 6, name: "updated_at", kind: "message", T: Timestamp },
    { no: 13, name: "scheduled_at", kind: "message", T: Timestamp },
    { no: 7, name: "status", kind: "enum", T: proto3.getEnumType(IndexingStatus) },
    { no: 8, name: "status_detail", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "auto_indexed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "has_snippets", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 15, name: "auth_uid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "repo_stats", kind: "message", T: Index_RepoStats },
    { no: 10, name: "indexing_progress", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: ProgressBar} },
    { no: 11, name: "index_stats", kind: "message", T: VectorIndexStats },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Index {
    return new Index().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Index {
    return new Index().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Index {
    return new Index().fromJsonString(jsonString, options);
  }

  static equals(a: Index | PlainMessage<Index> | undefined, b: Index | PlainMessage<Index> | undefined): boolean {
    return proto3.util.equals(Index, a, b);
  }
}

/**
 * @generated from message exa.index_pb.Index_RepoStats
 */
export class Index_RepoStats extends Message<Index_RepoStats> {
  /**
   * @generated from field: int64 size = 1;
   */
  size = protoInt64.zero;

  /**
   * @generated from field: int64 file_count = 2;
   */
  fileCount = protoInt64.zero;

  /**
   * @generated from field: int64 size_no_ignore = 3;
   */
  sizeNoIgnore = protoInt64.zero;

  /**
   * @generated from field: int64 file_count_no_ignore = 4;
   */
  fileCountNoIgnore = protoInt64.zero;

  constructor(data?: PartialMessage<Index_RepoStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.Index_RepoStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "file_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "size_no_ignore", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "file_count_no_ignore", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Index_RepoStats {
    return new Index_RepoStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Index_RepoStats {
    return new Index_RepoStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Index_RepoStats {
    return new Index_RepoStats().fromJsonString(jsonString, options);
  }

  static equals(a: Index_RepoStats | PlainMessage<Index_RepoStats> | undefined, b: Index_RepoStats | PlainMessage<Index_RepoStats> | undefined): boolean {
    return proto3.util.equals(Index_RepoStats, a, b);
  }
}

/**
 * @generated from message exa.index_pb.Repository
 */
export class Repository extends Message<Repository> {
  /**
   * @generated from field: string repo_name = 1;
   */
  repoName = "";

  /**
   * @generated from field: exa.index_pb.RepositoryConfig config = 2;
   */
  config?: RepositoryConfig;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_used_at = 6;
   */
  lastUsedAt?: Timestamp;

  /**
   * @generated from field: exa.index_pb.Index latest_index = 3;
   */
  latestIndex?: Index;

  constructor(data?: PartialMessage<Repository>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.Repository";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "config", kind: "message", T: RepositoryConfig },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
    { no: 5, name: "updated_at", kind: "message", T: Timestamp },
    { no: 6, name: "last_used_at", kind: "message", T: Timestamp },
    { no: 3, name: "latest_index", kind: "message", T: Index },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Repository {
    return new Repository().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Repository {
    return new Repository().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Repository {
    return new Repository().fromJsonString(jsonString, options);
  }

  static equals(a: Repository | PlainMessage<Repository> | undefined, b: Repository | PlainMessage<Repository> | undefined): boolean {
    return proto3.util.equals(Repository, a, b);
  }
}

/**
 * @generated from message exa.index_pb.RequestIndexVersion
 */
export class RequestIndexVersion extends Message<RequestIndexVersion> {
  /**
   * @generated from field: string version_alias = 3;
   */
  versionAlias = "";

  /**
   * @generated from oneof exa.index_pb.RequestIndexVersion.version
   */
  version: {
    /**
     * @generated from field: string commit = 1;
     */
    value: string;
    case: "commit";
  } | {
    /**
     * @generated from field: string branch = 2;
     */
    value: string;
    case: "branch";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<RequestIndexVersion>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.RequestIndexVersion";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "version_alias", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 1, name: "commit", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "version" },
    { no: 2, name: "branch", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "version" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestIndexVersion {
    return new RequestIndexVersion().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestIndexVersion {
    return new RequestIndexVersion().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestIndexVersion {
    return new RequestIndexVersion().fromJsonString(jsonString, options);
  }

  static equals(a: RequestIndexVersion | PlainMessage<RequestIndexVersion> | undefined, b: RequestIndexVersion | PlainMessage<RequestIndexVersion> | undefined): boolean {
    return proto3.util.equals(RequestIndexVersion, a, b);
  }
}

/**
 * @generated from message exa.index_pb.ManagementMetadata
 */
export class ManagementMetadata extends Message<ManagementMetadata> {
  /**
   * @generated from field: string auth_token = 1;
   */
  authToken = "";

  /**
   * @generated from field: string auth_uid = 2;
   */
  authUid = "";

  /**
   * @generated from field: string service_key = 3;
   */
  serviceKey = "";

  /**
   * @generated from field: bool force_target_public_index = 4;
   */
  forceTargetPublicIndex = false;

  /**
   * @generated from field: string force_team_id = 5;
   */
  forceTeamId = "";

  /**
   * @generated from field: string service_key_id = 6;
   */
  serviceKeyId = "";

  constructor(data?: PartialMessage<ManagementMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.ManagementMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "auth_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "auth_uid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "service_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "force_target_public_index", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "force_team_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "service_key_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ManagementMetadata {
    return new ManagementMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ManagementMetadata {
    return new ManagementMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ManagementMetadata {
    return new ManagementMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: ManagementMetadata | PlainMessage<ManagementMetadata> | undefined, b: ManagementMetadata | PlainMessage<ManagementMetadata> | undefined): boolean {
    return proto3.util.equals(ManagementMetadata, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexerEvent_Untrack
 */
export class IndexerEvent_Untrack extends Message<IndexerEvent_Untrack> {
  /**
   * @generated from field: string absolute_uri = 1;
   */
  absoluteUri = "";

  /**
   * @generated from field: repeated exa.codeium_common_pb.WorkspacePath paths = 2;
   */
  paths: WorkspacePath[] = [];

  /**
   * @generated from field: string workspace_uri = 3;
   */
  workspaceUri = "";

  constructor(data?: PartialMessage<IndexerEvent_Untrack>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexerEvent_Untrack";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "absolute_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "paths", kind: "message", T: WorkspacePath, repeated: true },
    { no: 3, name: "workspace_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexerEvent_Untrack {
    return new IndexerEvent_Untrack().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexerEvent_Untrack {
    return new IndexerEvent_Untrack().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexerEvent_Untrack {
    return new IndexerEvent_Untrack().fromJsonString(jsonString, options);
  }

  static equals(a: IndexerEvent_Untrack | PlainMessage<IndexerEvent_Untrack> | undefined, b: IndexerEvent_Untrack | PlainMessage<IndexerEvent_Untrack> | undefined): boolean {
    return proto3.util.equals(IndexerEvent_Untrack, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexerEvent_Update
 */
export class IndexerEvent_Update extends Message<IndexerEvent_Update> {
  /**
   * @generated from field: string absolute_uri = 1;
   */
  absoluteUri = "";

  /**
   * @generated from field: repeated exa.codeium_common_pb.WorkspacePath paths = 2;
   */
  paths: WorkspacePath[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp mod_time = 3;
   */
  modTime?: Timestamp;

  /**
   * @generated from field: exa.index_pb.IndexerEvent_Update_AddWorkspaceInfo add_workspace_info = 4;
   */
  addWorkspaceInfo?: IndexerEvent_Update_AddWorkspaceInfo;

  constructor(data?: PartialMessage<IndexerEvent_Update>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexerEvent_Update";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "absolute_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "paths", kind: "message", T: WorkspacePath, repeated: true },
    { no: 3, name: "mod_time", kind: "message", T: Timestamp },
    { no: 4, name: "add_workspace_info", kind: "message", T: IndexerEvent_Update_AddWorkspaceInfo },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexerEvent_Update {
    return new IndexerEvent_Update().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexerEvent_Update {
    return new IndexerEvent_Update().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexerEvent_Update {
    return new IndexerEvent_Update().fromJsonString(jsonString, options);
  }

  static equals(a: IndexerEvent_Update | PlainMessage<IndexerEvent_Update> | undefined, b: IndexerEvent_Update | PlainMessage<IndexerEvent_Update> | undefined): boolean {
    return proto3.util.equals(IndexerEvent_Update, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexerEvent_Update_AddWorkspaceInfo
 */
export class IndexerEvent_Update_AddWorkspaceInfo extends Message<IndexerEvent_Update_AddWorkspaceInfo> {
  /**
   * @generated from field: uint64 add_workspace_uid = 1;
   */
  addWorkspaceUid = protoInt64.zero;

  /**
   * @generated from field: uint64 add_workspace_queue_uid = 2;
   */
  addWorkspaceQueueUid = protoInt64.zero;

  constructor(data?: PartialMessage<IndexerEvent_Update_AddWorkspaceInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexerEvent_Update_AddWorkspaceInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "add_workspace_uid", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "add_workspace_queue_uid", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexerEvent_Update_AddWorkspaceInfo {
    return new IndexerEvent_Update_AddWorkspaceInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexerEvent_Update_AddWorkspaceInfo {
    return new IndexerEvent_Update_AddWorkspaceInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexerEvent_Update_AddWorkspaceInfo {
    return new IndexerEvent_Update_AddWorkspaceInfo().fromJsonString(jsonString, options);
  }

  static equals(a: IndexerEvent_Update_AddWorkspaceInfo | PlainMessage<IndexerEvent_Update_AddWorkspaceInfo> | undefined, b: IndexerEvent_Update_AddWorkspaceInfo | PlainMessage<IndexerEvent_Update_AddWorkspaceInfo> | undefined): boolean {
    return proto3.util.equals(IndexerEvent_Update_AddWorkspaceInfo, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexerEvent_AddWorkspace
 */
export class IndexerEvent_AddWorkspace extends Message<IndexerEvent_AddWorkspace> {
  /**
   * @generated from field: uint64 add_workspace_uid = 1;
   */
  addWorkspaceUid = protoInt64.zero;

  /**
   * @generated from field: uint64 add_workspace_queue_uid = 2;
   */
  addWorkspaceQueueUid = protoInt64.zero;

  /**
   * @generated from field: string workspace_uri = 3;
   */
  workspaceUri = "";

  /**
   * @generated from field: int64 num_files = 4;
   */
  numFiles = protoInt64.zero;

  /**
   * @generated from field: int64 size = 5;
   */
  size = protoInt64.zero;

  constructor(data?: PartialMessage<IndexerEvent_AddWorkspace>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexerEvent_AddWorkspace";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "add_workspace_uid", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "add_workspace_queue_uid", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "workspace_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "num_files", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexerEvent_AddWorkspace {
    return new IndexerEvent_AddWorkspace().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexerEvent_AddWorkspace {
    return new IndexerEvent_AddWorkspace().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexerEvent_AddWorkspace {
    return new IndexerEvent_AddWorkspace().fromJsonString(jsonString, options);
  }

  static equals(a: IndexerEvent_AddWorkspace | PlainMessage<IndexerEvent_AddWorkspace> | undefined, b: IndexerEvent_AddWorkspace | PlainMessage<IndexerEvent_AddWorkspace> | undefined): boolean {
    return proto3.util.equals(IndexerEvent_AddWorkspace, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexerEvent_RemoveWorkspace
 */
export class IndexerEvent_RemoveWorkspace extends Message<IndexerEvent_RemoveWorkspace> {
  /**
   * @generated from field: string workspace_uri = 1;
   */
  workspaceUri = "";

  constructor(data?: PartialMessage<IndexerEvent_RemoveWorkspace>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexerEvent_RemoveWorkspace";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexerEvent_RemoveWorkspace {
    return new IndexerEvent_RemoveWorkspace().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexerEvent_RemoveWorkspace {
    return new IndexerEvent_RemoveWorkspace().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexerEvent_RemoveWorkspace {
    return new IndexerEvent_RemoveWorkspace().fromJsonString(jsonString, options);
  }

  static equals(a: IndexerEvent_RemoveWorkspace | PlainMessage<IndexerEvent_RemoveWorkspace> | undefined, b: IndexerEvent_RemoveWorkspace | PlainMessage<IndexerEvent_RemoveWorkspace> | undefined): boolean {
    return proto3.util.equals(IndexerEvent_RemoveWorkspace, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexerEvent_IgnoreWorkspace
 */
export class IndexerEvent_IgnoreWorkspace extends Message<IndexerEvent_IgnoreWorkspace> {
  /**
   * @generated from field: string workspace_uri = 1;
   */
  workspaceUri = "";

  constructor(data?: PartialMessage<IndexerEvent_IgnoreWorkspace>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexerEvent_IgnoreWorkspace";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workspace_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexerEvent_IgnoreWorkspace {
    return new IndexerEvent_IgnoreWorkspace().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexerEvent_IgnoreWorkspace {
    return new IndexerEvent_IgnoreWorkspace().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexerEvent_IgnoreWorkspace {
    return new IndexerEvent_IgnoreWorkspace().fromJsonString(jsonString, options);
  }

  static equals(a: IndexerEvent_IgnoreWorkspace | PlainMessage<IndexerEvent_IgnoreWorkspace> | undefined, b: IndexerEvent_IgnoreWorkspace | PlainMessage<IndexerEvent_IgnoreWorkspace> | undefined): boolean {
    return proto3.util.equals(IndexerEvent_IgnoreWorkspace, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexerEvent_AddCommit
 */
export class IndexerEvent_AddCommit extends Message<IndexerEvent_AddCommit> {
  /**
   * @generated from field: string sha = 1;
   */
  sha = "";

  constructor(data?: PartialMessage<IndexerEvent_AddCommit>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexerEvent_AddCommit";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sha", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexerEvent_AddCommit {
    return new IndexerEvent_AddCommit().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexerEvent_AddCommit {
    return new IndexerEvent_AddCommit().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexerEvent_AddCommit {
    return new IndexerEvent_AddCommit().fromJsonString(jsonString, options);
  }

  static equals(a: IndexerEvent_AddCommit | PlainMessage<IndexerEvent_AddCommit> | undefined, b: IndexerEvent_AddCommit | PlainMessage<IndexerEvent_AddCommit> | undefined): boolean {
    return proto3.util.equals(IndexerEvent_AddCommit, a, b);
  }
}

/**
 * @generated from message exa.index_pb.GetRepositoriesFilter
 */
export class GetRepositoriesFilter extends Message<GetRepositoriesFilter> {
  /**
   * @generated from field: string repo_name = 1;
   */
  repoName = "";

  /**
   * @generated from field: string group_id = 2;
   */
  groupId = "";

  constructor(data?: PartialMessage<GetRepositoriesFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.GetRepositoriesFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repo_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRepositoriesFilter {
    return new GetRepositoriesFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRepositoriesFilter {
    return new GetRepositoriesFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRepositoriesFilter {
    return new GetRepositoriesFilter().fromJsonString(jsonString, options);
  }

  static equals(a: GetRepositoriesFilter | PlainMessage<GetRepositoriesFilter> | undefined, b: GetRepositoriesFilter | PlainMessage<GetRepositoriesFilter> | undefined): boolean {
    return proto3.util.equals(GetRepositoriesFilter, a, b);
  }
}

/**
 * @generated from message exa.index_pb.RemoteIndexStats
 */
export class RemoteIndexStats extends Message<RemoteIndexStats> {
  /**
   * @generated from field: string index_id = 1;
   */
  indexId = "";

  /**
   * @generated from field: int64 cci_count = 2;
   */
  cciCount = protoInt64.zero;

  /**
   * @generated from field: int64 snippet_count = 3;
   */
  snippetCount = protoInt64.zero;

  /**
   * @generated from field: int64 embedding_count = 4;
   */
  embeddingCount = protoInt64.zero;

  constructor(data?: PartialMessage<RemoteIndexStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.RemoteIndexStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "index_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "cci_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "snippet_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "embedding_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoteIndexStats {
    return new RemoteIndexStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoteIndexStats {
    return new RemoteIndexStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoteIndexStats {
    return new RemoteIndexStats().fromJsonString(jsonString, options);
  }

  static equals(a: RemoteIndexStats | PlainMessage<RemoteIndexStats> | undefined, b: RemoteIndexStats | PlainMessage<RemoteIndexStats> | undefined): boolean {
    return proto3.util.equals(RemoteIndexStats, a, b);
  }
}

/**
 * @generated from message exa.index_pb.RepositoryFilter
 */
export class RepositoryFilter extends Message<RepositoryFilter> {
  /**
   * @generated from field: exa.codeium_common_pb.GitRepoInfo repository = 1;
   */
  repository?: GitRepoInfo;

  /**
   * @generated from field: repeated string excluded_files = 2;
   */
  excludedFiles: string[] = [];

  /**
   * @generated from field: repeated string filter_paths = 3;
   */
  filterPaths: string[] = [];

  constructor(data?: PartialMessage<RepositoryFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.RepositoryFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repository", kind: "message", T: GitRepoInfo },
    { no: 2, name: "excluded_files", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "filter_paths", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RepositoryFilter {
    return new RepositoryFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RepositoryFilter {
    return new RepositoryFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RepositoryFilter {
    return new RepositoryFilter().fromJsonString(jsonString, options);
  }

  static equals(a: RepositoryFilter | PlainMessage<RepositoryFilter> | undefined, b: RepositoryFilter | PlainMessage<RepositoryFilter> | undefined): boolean {
    return proto3.util.equals(RepositoryFilter, a, b);
  }
}

/**
 * @generated from message exa.index_pb.ScoredContextItem
 */
export class ScoredContextItem extends Message<ScoredContextItem> {
  /**
   * @generated from field: exa.codeium_common_pb.CodeContextItem code_context_item = 1;
   */
  codeContextItem?: CodeContextItem;

  /**
   * @generated from field: float score = 2;
   */
  score = 0;

  constructor(data?: PartialMessage<ScoredContextItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.ScoredContextItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code_context_item", kind: "message", T: CodeContextItem },
    { no: 2, name: "score", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ScoredContextItem {
    return new ScoredContextItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ScoredContextItem {
    return new ScoredContextItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ScoredContextItem {
    return new ScoredContextItem().fromJsonString(jsonString, options);
  }

  static equals(a: ScoredContextItem | PlainMessage<ScoredContextItem> | undefined, b: ScoredContextItem | PlainMessage<ScoredContextItem> | undefined): boolean {
    return proto3.util.equals(ScoredContextItem, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexStats
 */
export class IndexStats extends Message<IndexStats> {
  /**
   * @generated from field: string repository_name = 1;
   */
  repositoryName = "";

  /**
   * @generated from field: int64 file_count = 2;
   */
  fileCount = protoInt64.zero;

  /**
   * @generated from field: int64 code_context_item_count = 3;
   */
  codeContextItemCount = protoInt64.zero;

  constructor(data?: PartialMessage<IndexStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "repository_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "file_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "code_context_item_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexStats {
    return new IndexStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexStats {
    return new IndexStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexStats {
    return new IndexStats().fromJsonString(jsonString, options);
  }

  static equals(a: IndexStats | PlainMessage<IndexStats> | undefined, b: IndexStats | PlainMessage<IndexStats> | undefined): boolean {
    return proto3.util.equals(IndexStats, a, b);
  }
}

/**
 * @generated from message exa.index_pb.IndexerEvent_Deletion
 */
export class IndexerEvent_Deletion extends Message<IndexerEvent_Deletion> {
  /**
   * @generated from field: string absolute_uri = 1;
   */
  absoluteUri = "";

  constructor(data?: PartialMessage<IndexerEvent_Deletion>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "exa.index_pb.IndexerEvent_Deletion";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "absolute_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexerEvent_Deletion {
    return new IndexerEvent_Deletion().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexerEvent_Deletion {
    return new IndexerEvent_Deletion().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexerEvent_Deletion {
    return new IndexerEvent_Deletion().fromJsonString(jsonString, options);
  }

  static equals(a: IndexerEvent_Deletion | PlainMessage<IndexerEvent_Deletion> | undefined, b: IndexerEvent_Deletion | PlainMessage<IndexerEvent_Deletion> | undefined): boolean {
    return proto3.util.equals(IndexerEvent_Deletion, a, b);
  }
}

