// @generated by protoc-gen-connect-es v1.6.0 with parameter "target=ts"
// @generated from file exa/google/internal/cloud/code/v1internal/jetski_service.proto (package google.internal.cloud.code.v1internal, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AgentPlugin, CheckUrlDenylistRequest, CheckUrlDenylistResponse, FetchFromTrawlerCacheRequest, FetchFromTrawlerCacheResponse, FetchUserInfoRequest, FetchUserInfoResponse, GetAgentPluginRequest, GetHealthRequest, Health, ListAgentPluginsRequest, ListAgentPluginsResponse, ListCascadeNuxesRequest, ListCascadeNuxesResponse, ListWebDocsOptionsRequest, ListWebDocsOptionsResponse, RecordTrajectoryAnalyticsRequest, RecordTrajectoryAnalyticsResponse, RewriteUriRequest, RewriteUriResponse, SetUserSettingsRequest, SetUserSettingsResponse, TabChatRequest, TabChatResponse } from "./jetski_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service google.internal.cloud.code.v1internal.JetskiService
 */
export const JetskiService = {
  typeName: "google.internal.cloud.code.v1internal.JetskiService",
  methods: {
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.ListAgentPlugins
     */
    listAgentPlugins: {
      name: "ListAgentPlugins",
      I: ListAgentPluginsRequest,
      O: ListAgentPluginsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.GetAgentPlugin
     */
    getAgentPlugin: {
      name: "GetAgentPlugin",
      I: GetAgentPluginRequest,
      O: AgentPlugin,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.ListCascadeNuxes
     */
    listCascadeNuxes: {
      name: "ListCascadeNuxes",
      I: ListCascadeNuxesRequest,
      O: ListCascadeNuxesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.ListWebDocsOptions
     */
    listWebDocsOptions: {
      name: "ListWebDocsOptions",
      I: ListWebDocsOptionsRequest,
      O: ListWebDocsOptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.RewriteUri
     */
    rewriteUri: {
      name: "RewriteUri",
      I: RewriteUriRequest,
      O: RewriteUriResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.FetchUserInfo
     */
    fetchUserInfo: {
      name: "FetchUserInfo",
      I: FetchUserInfoRequest,
      O: FetchUserInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.SetUserSettings
     */
    setUserSettings: {
      name: "SetUserSettings",
      I: SetUserSettingsRequest,
      O: SetUserSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.TabChat
     */
    tabChat: {
      name: "TabChat",
      I: TabChatRequest,
      O: TabChatResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.CheckUrlDenylist
     */
    checkUrlDenylist: {
      name: "CheckUrlDenylist",
      I: CheckUrlDenylistRequest,
      O: CheckUrlDenylistResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.GetHealth
     */
    getHealth: {
      name: "GetHealth",
      I: GetHealthRequest,
      O: Health,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.RecordTrajectoryAnalytics
     */
    recordTrajectoryAnalytics: {
      name: "RecordTrajectoryAnalytics",
      I: RecordTrajectoryAnalyticsRequest,
      O: RecordTrajectoryAnalyticsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc google.internal.cloud.code.v1internal.JetskiService.FetchFromTrawlerCache
     */
    fetchFromTrawlerCache: {
      name: "FetchFromTrawlerCache",
      I: FetchFromTrawlerCacheRequest,
      O: FetchFromTrawlerCacheResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

