// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY
import { Transport, createPromiseClient } from "@connectrpc/connect";
import { T } from "./index.js";
import * as ServiceMod from "../gen/exa/language_server_pb/language_server_connect.js";
import * as PB from "../gen/exa/language_server_pb/language_server_pb.js";

export class LanguageServerFacade {
  private client;
  constructor(transport: Transport) {
    this.client = createPromiseClient((ServiceMod as any).LanguageServerService, transport);
  }

  async provideCompletionFeedback(input: T.LanguageServer.ProvideCompletionFeedbackRequestInput) {
    const req = new (PB as any).ProvideCompletionFeedbackRequest(input as any);
    return await this.client.provideCompletionFeedback(req);
  }

  async heartbeat(input: T.LanguageServer.HeartbeatRequestInput) {
    const req = new (PB as any).HeartbeatRequest(input as any);
    return await this.client.heartbeat(req);
  }

  async getStatus(input: T.LanguageServer.GetStatusRequestInput) {
    const req = new (PB as any).GetStatusRequest(input as any);
    return await this.client.getStatus(req);
  }

  async getCommandModelConfigs(input: T.LanguageServer.GetCommandModelConfigsRequestInput) {
    const req = new (PB as any).GetCommandModelConfigsRequest(input as any);
    return await this.client.getCommandModelConfigs(req);
  }

  async getCascadeModelConfigs(input: T.LanguageServer.GetCascadeModelConfigsRequestInput) {
    const req = new (PB as any).GetCascadeModelConfigsRequest(input as any);
    return await this.client.getCascadeModelConfigs(req);
  }

  async recordEvent(input: T.LanguageServer.RecordEventRequestInput) {
    const req = new (PB as any).RecordEventRequest(input as any);
    return await this.client.recordEvent(req);
  }

  async recordSidecarEvent(input: T.LanguageServer.RecordSidecarEventRequestInput) {
    const req = new (PB as any).RecordSidecarEventRequest(input as any);
    return await this.client.recordSidecarEvent(req);
  }

  async getSidecars(input: T.LanguageServer.GetSidecarsRequestInput) {
    const req = new (PB as any).GetSidecarsRequest(input as any);
    return await this.client.getSidecars(req);
  }

  async getSidecarEvents(input: T.LanguageServer.GetSidecarEventsRequestInput) {
    const req = new (PB as any).GetSidecarEventsRequest(input as any);
    return await this.client.getSidecarEvents(req);
  }

  async manageSidecar(input: T.LanguageServer.ManageSidecarRequestInput) {
    const req = new (PB as any).ManageSidecarRequest(input as any);
    return await this.client.manageSidecar(req);
  }

  async registerGdmUser(input: T.LanguageServer.RegisterGdmUserRequestInput) {
    const req = new (PB as any).RegisterGdmUserRequest(input as any);
    return await this.client.registerGdmUser(req);
  }

  async migrateApiKey(input: T.LanguageServer.MigrateApiKeyRequestInput) {
    const req = new (PB as any).MigrateApiKeyRequest(input as any);
    return await this.client.migrateApiKey(req);
  }

  async wellSupportedLanguages(input: T.LanguageServer.WellSupportedLanguagesRequestInput) {
    const req = new (PB as any).WellSupportedLanguagesRequest(input as any);
    return await this.client.wellSupportedLanguages(req);
  }

  async recordSearchDocOpen(input: T.LanguageServer.RecordSearchDocOpenRequestInput) {
    const req = new (PB as any).RecordSearchDocOpenRequest(input as any);
    return await this.client.recordSearchDocOpen(req);
  }

  async recordSearchResultsView(input: T.LanguageServer.RecordSearchResultsViewRequestInput) {
    const req = new (PB as any).RecordSearchResultsViewRequest(input as any);
    return await this.client.recordSearchResultsView(req);
  }

  async getMcpServerTemplates(input: T.LanguageServer.GetMcpServerTemplatesRequestInput) {
    const req = new (PB as any).GetMcpServerTemplatesRequest(input as any);
    return await this.client.getMcpServerTemplates(req);
  }

  async addTrackedWorkspace(input: T.LanguageServer.AddTrackedWorkspaceRequestInput) {
    const req = new (PB as any).AddTrackedWorkspaceRequest(input as any);
    return await this.client.addTrackedWorkspace(req);
  }

  async removeTrackedWorkspace(input: T.LanguageServer.RemoveTrackedWorkspaceRequestInput) {
    const req = new (PB as any).RemoveTrackedWorkspaceRequest(input as any);
    return await this.client.removeTrackedWorkspace(req);
  }

  async smartFocusConversation(input: T.LanguageServer.SmartFocusConversationRequestInput) {
    const req = new (PB as any).SmartFocusConversationRequest(input as any);
    return await this.client.smartFocusConversation(req);
  }

  async statUri(input: T.LanguageServer.StatUriRequestInput) {
    const req = new (PB as any).StatUriRequest(input as any);
    return await this.client.statUri(req);
  }

  async readFile(input: T.LanguageServer.ReadFileRequestInput) {
    const req = new (PB as any).ReadFileRequest(input as any);
    return await this.client.readFile(req);
  }

  async writeFile(input: T.LanguageServer.WriteFileRequestInput) {
    const req = new (PB as any).WriteFileRequest(input as any);
    return await this.client.writeFile(req);
  }

  async readDir(input: T.LanguageServer.ReadDirRequestInput) {
    const req = new (PB as any).ReadDirRequest(input as any);
    return await this.client.readDir(req);
  }

  async deleteFileOrDirectory(input: T.LanguageServer.DeleteFileOrDirectoryRequestInput) {
    const req = new (PB as any).DeleteFileOrDirectoryRequest(input as any);
    return await this.client.deleteFileOrDirectory(req);
  }

  async setBrowserOpenConversation(input: T.LanguageServer.SetBrowserOpenConversationRequestInput) {
    const req = new (PB as any).SetBrowserOpenConversationRequest(input as any);
    return await this.client.setBrowserOpenConversation(req);
  }

  async getBrowserOpenConversation(input: T.LanguageServer.GetBrowserOpenConversationRequestInput) {
    const req = new (PB as any).GetBrowserOpenConversationRequest(input as any);
    return await this.client.getBrowserOpenConversation(req);
  }

  async refreshContextForIdeAction(input: T.LanguageServer.RefreshContextForIdeActionRequestInput) {
    const req = new (PB as any).RefreshContextForIdeActionRequest(input as any);
    return await this.client.refreshContextForIdeAction(req);
  }

  async getMatchingContextScopeItems(input: T.LanguageServer.GetMatchingContextScopeItemsRequestInput) {
    const req = new (PB as any).GetMatchingContextScopeItemsRequest(input as any);
    return await this.client.getMatchingContextScopeItems(req);
  }

  async recordChatFeedback(input: T.LanguageServer.RecordChatFeedbackRequestInput) {
    const req = new (PB as any).RecordChatFeedbackRequest(input as any);
    return await this.client.recordChatFeedback(req);
  }

  async recordChatPanelSession(input: T.LanguageServer.RecordChatPanelSessionRequestInput) {
    const req = new (PB as any).RecordChatPanelSessionRequest(input as any);
    return await this.client.recordChatPanelSession(req);
  }

  async shouldEnableUnleash(input: T.LanguageServer.ShouldEnableUnleashRequestInput) {
    const req = new (PB as any).ShouldEnableUnleashRequest(input as any);
    return await this.client.shouldEnableUnleash(req);
  }

  async getWorkspaceEditState(input: T.LanguageServer.GetWorkspaceEditStateRequestInput) {
    const req = new (PB as any).GetWorkspaceEditStateRequest(input as any);
    return await this.client.getWorkspaceEditState(req);
  }

  async getRepoInfos(input: T.LanguageServer.GetRepoInfosRequestInput) {
    const req = new (PB as any).GetRepoInfosRequest(input as any);
    return await this.client.getRepoInfos(req);
  }

  async getWorkspaceInfos(input: T.LanguageServer.GetWorkspaceInfosRequestInput) {
    const req = new (PB as any).GetWorkspaceInfosRequest(input as any);
    return await this.client.getWorkspaceInfos(req);
  }

  async createWorktree(input: T.LanguageServer.CreateWorktreeRequestInput) {
    const req = new (PB as any).CreateWorktreeRequest(input as any);
    return await this.client.createWorktree(req);
  }

  async deleteWorktree(input: T.LanguageServer.DeleteWorktreeRequestInput) {
    const req = new (PB as any).DeleteWorktreeRequest(input as any);
    return await this.client.deleteWorktree(req);
  }

  async checkoutWorktree(input: T.LanguageServer.CheckoutWorktreeRequestInput) {
    const req = new (PB as any).CheckoutWorktreeRequest(input as any);
    return await this.client.checkoutWorktree(req);
  }

  async getWorktreeDiff(input: T.LanguageServer.GetWorktreeDiffRequestInput) {
    const req = new (PB as any).GetWorktreeDiffRequest(input as any);
    return await this.client.getWorktreeDiff(req);
  }

  async createCitcWorkspace(input: T.LanguageServer.CreateCitcWorkspaceRequestInput) {
    const req = new (PB as any).CreateCitcWorkspaceRequest(input as any);
    return await this.client.createCitcWorkspace(req);
  }

  async setWorkingDirectories(input: T.LanguageServer.SetWorkingDirectoriesRequestInput) {
    const req = new (PB as any).SetWorkingDirectoriesRequest(input as any);
    return await this.client.setWorkingDirectories(req);
  }

  async getWorkingDirectories(input: T.LanguageServer.GetWorkingDirectoriesRequestInput) {
    const req = new (PB as any).GetWorkingDirectoriesRequest(input as any);
    return await this.client.getWorkingDirectories(req);
  }

  async getRevisionArtifact(input: T.LanguageServer.GetRevisionArtifactRequestInput) {
    const req = new (PB as any).GetRevisionArtifactRequest(input as any);
    return await this.client.getRevisionArtifact(req);
  }

  async generateCommitMessage(input: T.LanguageServer.GenerateCommitMessageRequestInput) {
    const req = new (PB as any).GenerateCommitMessageRequest(input as any);
    return await this.client.generateCommitMessage(req);
  }

  async recordCommitMessageSave(input: T.LanguageServer.RecordCommitMessageSaveRequestInput) {
    const req = new (PB as any).RecordCommitMessageSaveRequest(input as any);
    return await this.client.recordCommitMessageSave(req);
  }

  async updatePRForWorktree(input: T.LanguageServer.UpdatePRForWorktreeRequestInput) {
    const req = new (PB as any).UpdatePRForWorktreeRequest(input as any);
    return await this.client.updatePRForWorktree(req);
  }

  async sendActionToChatPanel(input: T.LanguageServer.SendActionToChatPanelRequestInput) {
    const req = new (PB as any).SendActionToChatPanelRequest(input as any);
    return await this.client.sendActionToChatPanel(req);
  }

  async getUserSettings(input: T.LanguageServer.GetUserSettingsRequestInput) {
    const req = new (PB as any).GetUserSettingsRequest(input as any);
    return await this.client.getUserSettings(req);
  }

  async setUserSettings(input: T.LanguageServer.SetUserSettingsRequestInput) {
    const req = new (PB as any).SetUserSettingsRequest(input as any);
    return await this.client.setUserSettings(req);
  }

  async fetchUserInfo(input: T.LanguageServer.FetchUserInfoRequestInput) {
    const req = new (PB as any).FetchUserInfoRequest(input as any);
    return await this.client.fetchUserInfo(req);
  }

  async setUserInfo(input: T.LanguageServer.SetUserInfoRequestInput) {
    const req = new (PB as any).SetUserInfoRequest(input as any);
    return await this.client.setUserInfo(req);
  }

  async getDebugDiagnostics(input: T.LanguageServer.GetDebugDiagnosticsRequestInput) {
    const req = new (PB as any).GetDebugDiagnosticsRequest(input as any);
    return await this.client.getDebugDiagnostics(req);
  }

  async dumpFlightRecorder(input: T.LanguageServer.DumpFlightRecorderRequestInput) {
    const req = new (PB as any).DumpFlightRecorderRequest(input as any);
    return await this.client.dumpFlightRecorder(req);
  }

  async dumpPprof(input: T.LanguageServer.DumpPprofRequestInput) {
    const req = new (PB as any).DumpPprofRequest(input as any);
    return await this.client.dumpPprof(req);
  }

  async getUserAnalyticsSummary(input: T.LanguageServer.GetUserAnalyticsSummaryRequestInput) {
    const req = new (PB as any).GetUserAnalyticsSummaryRequest(input as any);
    return await this.client.getUserAnalyticsSummary(req);
  }

  async getUserStatus(input: T.LanguageServer.GetUserStatusRequestInput) {
    const req = new (PB as any).GetUserStatusRequest(input as any);
    return await this.client.getUserStatus(req);
  }

  async getProfileData(input: T.LanguageServer.GetProfileDataRequestInput) {
    const req = new (PB as any).GetProfileDataRequest(input as any);
    return await this.client.getProfileData(req);
  }

  async getChangelog(input: T.LanguageServer.GetChangelogRequestInput) {
    const req = new (PB as any).GetChangelogRequest(input as any);
    return await this.client.getChangelog(req);
  }

  async setupUniversitySandbox(input: T.LanguageServer.SetupUniversitySandboxRequestInput) {
    const req = new (PB as any).SetupUniversitySandboxRequest(input as any);
    return await this.client.setupUniversitySandbox(req);
  }

  async exit(input: T.LanguageServer.ExitRequestInput) {
    const req = new (PB as any).ExitRequest(input as any);
    return await this.client.exit(req);
  }

  async restart(input: T.LanguageServer.RestartRequestInput) {
    const req = new (PB as any).RestartRequest(input as any);
    return await this.client.restart(req);
  }

  async resetOnboarding(input: T.LanguageServer.ResetOnboardingRequestInput) {
    const req = new (PB as any).ResetOnboardingRequest(input as any);
    return await this.client.resetOnboarding(req);
  }

  async skipOnboarding(input: T.LanguageServer.SkipOnboardingRequestInput) {
    const req = new (PB as any).SkipOnboardingRequest(input as any);
    return await this.client.skipOnboarding(req);
  }

  async getTermsOfService(input: T.LanguageServer.GetTermsOfServiceRequestInput) {
    const req = new (PB as any).GetTermsOfServiceRequest(input as any);
    return await this.client.getTermsOfService(req);
  }

  async acceptTermsOfService(input: T.LanguageServer.AcceptTermsOfServiceRequestInput) {
    const req = new (PB as any).AcceptTermsOfServiceRequest(input as any);
    return await this.client.acceptTermsOfService(req);
  }

  async getUserTrajectoryDebug(input: T.LanguageServer.GetUserTrajectoryDebugRequestInput) {
    const req = new (PB as any).GetUserTrajectoryDebugRequest(input as any);
    return await this.client.getUserTrajectoryDebug(req);
  }

  async getUserTrajectoryDescriptions(input: T.LanguageServer.GetUserTrajectoryDescriptionsRequestInput) {
    const req = new (PB as any).GetUserTrajectoryDescriptionsRequest(input as any);
    return await this.client.getUserTrajectoryDescriptions(req);
  }

  async getCascadeMemories(input: T.LanguageServer.GetCascadeMemoriesRequestInput) {
    const req = new (PB as any).GetCascadeMemoriesRequest(input as any);
    return await this.client.getCascadeMemories(req);
  }

  async deleteCascadeMemory(input: T.LanguageServer.DeleteCascadeMemoryRequestInput) {
    const req = new (PB as any).DeleteCascadeMemoryRequest(input as any);
    return await this.client.deleteCascadeMemory(req);
  }

  async updateCascadeMemory(input: T.LanguageServer.UpdateCascadeMemoryRequestInput) {
    const req = new (PB as any).UpdateCascadeMemoryRequest(input as any);
    return await this.client.updateCascadeMemory(req);
  }

  async getUserMemories(input: T.LanguageServer.GetUserMemoriesRequestInput) {
    const req = new (PB as any).GetUserMemoriesRequest(input as any);
    return await this.client.getUserMemories(req);
  }

  async updateConversationAnnotations(input: T.LanguageServer.UpdateConversationAnnotationsRequestInput) {
    const req = new (PB as any).UpdateConversationAnnotationsRequest(input as any);
    return await this.client.updateConversationAnnotations(req);
  }

  async startCascade(input: T.LanguageServer.StartCascadeRequestInput) {
    const req = new (PB as any).StartCascadeRequest(input as any);
    return await this.client.startCascade(req);
  }

  async startBattleMode(input: T.LanguageServer.StartBattleModeRequestInput) {
    const req = new (PB as any).StartBattleModeRequest(input as any);
    return await this.client.startBattleMode(req);
  }

  async endBattleMode(input: T.LanguageServer.EndBattleModeRequestInput) {
    const req = new (PB as any).EndBattleModeRequest(input as any);
    return await this.client.endBattleMode(req);
  }

  async setOrVerifyStaticConfig(input: T.LanguageServer.SetOrVerifyStaticConfigRequestInput) {
    const req = new (PB as any).SetOrVerifyStaticConfigRequest(input as any);
    return await this.client.setOrVerifyStaticConfig(req);
  }

  async forkConversation(input: T.LanguageServer.ForkConversationRequestInput) {
    const req = new (PB as any).ForkConversationRequest(input as any);
    return await this.client.forkConversation(req);
  }

  async cancelCascadeInvocation(input: T.LanguageServer.CancelCascadeInvocationRequestInput) {
    const req = new (PB as any).CancelCascadeInvocationRequest(input as any);
    return await this.client.cancelCascadeInvocation(req);
  }

  async forceStopCascadeTree(input: T.LanguageServer.ForceStopCascadeTreeRequestInput) {
    const req = new (PB as any).ForceStopCascadeTreeRequest(input as any);
    return await this.client.forceStopCascadeTree(req);
  }

  async cancelCascadeSteps(input: T.LanguageServer.CancelCascadeStepsRequestInput) {
    const req = new (PB as any).CancelCascadeStepsRequest(input as any);
    return await this.client.cancelCascadeSteps(req);
  }

  async sendStepsToBackground(input: T.LanguageServer.SendStepsToBackgroundRequestInput) {
    const req = new (PB as any).SendStepsToBackgroundRequest(input as any);
    return await this.client.sendStepsToBackground(req);
  }

  async skipBrowserSubagent(input: T.LanguageServer.SkipBrowserSubagentRequestInput) {
    const req = new (PB as any).SkipBrowserSubagentRequest(input as any);
    return await this.client.skipBrowserSubagent(req);
  }

  async getCascadeModelConfigData(input: T.LanguageServer.GetCascadeModelConfigDataRequestInput) {
    const req = new (PB as any).GetCascadeModelConfigDataRequest(input as any);
    return await this.client.getCascadeModelConfigData(req);
  }

  async sendUserCascadeMessage(input: T.LanguageServer.SendUserCascadeMessageRequestInput) {
    const req = new (PB as any).SendUserCascadeMessageRequest(input as any);
    return await this.client.sendUserCascadeMessage(req);
  }

  async signalExecutableIdle(input: T.LanguageServer.SignalExecutableIdleRequestInput) {
    const req = new (PB as any).SignalExecutableIdleRequest(input as any);
    return await this.client.signalExecutableIdle(req);
  }

  async sendAllQueuedMessages(input: T.LanguageServer.SendAllQueuedMessagesRequestInput) {
    const req = new (PB as any).SendAllQueuedMessagesRequest(input as any);
    return await this.client.sendAllQueuedMessages(req);
  }

  async deleteQueuedUserInputStep(input: T.LanguageServer.DeleteQueuedUserInputStepRequestInput) {
    const req = new (PB as any).DeleteQueuedUserInputStepRequest(input as any);
    return await this.client.deleteQueuedUserInputStep(req);
  }

  async revertToCascadeStep(input: T.LanguageServer.RevertToCascadeStepRequestInput) {
    const req = new (PB as any).RevertToCascadeStepRequest(input as any);
    return await this.client.revertToCascadeStep(req);
  }

  async getRevertPreview(input: T.LanguageServer.GetRevertPreviewRequestInput) {
    const req = new (PB as any).GetRevertPreviewRequest(input as any);
    return await this.client.getRevertPreview(req);
  }

  async recordUserStepSnapshot(input: T.LanguageServer.RecordUserStepSnapshotRequestInput) {
    const req = new (PB as any).RecordUserStepSnapshotRequest(input as any);
    return await this.client.recordUserStepSnapshot(req);
  }

  async getAllCascadeTrajectories(input: T.LanguageServer.GetAllCascadeTrajectoriesRequestInput) {
    const req = new (PB as any).GetAllCascadeTrajectoriesRequest(input as any);
    return await this.client.getAllCascadeTrajectories(req);
  }

  async handleCascadeUserInteraction(input: T.LanguageServer.HandleCascadeUserInteractionRequestInput) {
    const req = new (PB as any).HandleCascadeUserInteractionRequest(input as any);
    return await this.client.handleCascadeUserInteraction(req);
  }

  async acknowledgeCascadeCodeEdit(input: T.LanguageServer.AcknowledgeCascadeCodeEditRequestInput) {
    const req = new (PB as any).AcknowledgeCascadeCodeEditRequest(input as any);
    return await this.client.acknowledgeCascadeCodeEdit(req);
  }

  async acknowledgeCodeActionStep(input: T.LanguageServer.AcknowledgeCodeActionStepRequestInput) {
    const req = new (PB as any).AcknowledgeCodeActionStepRequest(input as any);
    return await this.client.acknowledgeCodeActionStep(req);
  }

  async getCodeValidationStates(input: T.LanguageServer.GetCodeValidationStatesRequestInput) {
    const req = new (PB as any).GetCodeValidationStatesRequest(input as any);
    return await this.client.getCodeValidationStates(req);
  }

  async deleteCascadeTrajectory(input: T.LanguageServer.DeleteCascadeTrajectoryRequestInput) {
    const req = new (PB as any).DeleteCascadeTrajectoryRequest(input as any);
    return await this.client.deleteCascadeTrajectory(req);
  }

  async initializeCascadePanelState(input: T.LanguageServer.InitializeCascadePanelStateRequestInput) {
    const req = new (PB as any).InitializeCascadePanelStateRequest(input as any);
    return await this.client.initializeCascadePanelState(req);
  }

  async requestAgentStatePageUpdate(input: T.JetskiCortex.AgentStatePageUpdateRequestInput) {
    const req = new (PB as any).AgentStatePageUpdateRequest(input as any);
    return await this.client.requestAgentStatePageUpdate(req);
  }

  async forceBackgroundResearchRefresh(input: T.LanguageServer.ForceBackgroundResearchRefreshRequestInput) {
    const req = new (PB as any).ForceBackgroundResearchRefreshRequest(input as any);
    return await this.client.forceBackgroundResearchRefresh(req);
  }

  async resolveOutstandingSteps(input: T.LanguageServer.ResolveOutstandingStepsRequestInput) {
    const req = new (PB as any).ResolveOutstandingStepsRequest(input as any);
    return await this.client.resolveOutstandingSteps(req);
  }

  async refreshMcpServers(input: T.LanguageServer.RefreshMcpServersRequestInput) {
    const req = new (PB as any).RefreshMcpServersRequest(input as any);
    return await this.client.refreshMcpServers(req);
  }

  async getMcpServerStates(input: T.LanguageServer.GetMcpServerStatesRequestInput) {
    const req = new (PB as any).GetMcpServerStatesRequest(input as any);
    return await this.client.getMcpServerStates(req);
  }

  async completeMcpOAuth(input: T.LanguageServer.CompleteMcpOAuthRequestInput) {
    const req = new (PB as any).CompleteMcpOAuthRequest(input as any);
    return await this.client.completeMcpOAuth(req);
  }

  async disconnectMcpOAuth(input: T.LanguageServer.DisconnectMcpOAuthRequestInput) {
    const req = new (PB as any).DisconnectMcpOAuthRequest(input as any);
    return await this.client.disconnectMcpOAuth(req);
  }

  async getModelResponse(input: T.LanguageServer.GetModelResponseRequestInput) {
    const req = new (PB as any).GetModelResponseRequest(input as any);
    return await this.client.getModelResponse(req);
  }

  async saveMediaAsArtifact(input: T.LanguageServer.SaveMediaAsArtifactRequestInput) {
    const req = new (PB as any).SaveMediaAsArtifactRequest(input as any);
    return await this.client.saveMediaAsArtifact(req);
  }

  async deleteMediaArtifact(input: T.LanguageServer.DeleteMediaArtifactRequestInput) {
    const req = new (PB as any).DeleteMediaArtifactRequest(input as any);
    return await this.client.deleteMediaArtifact(req);
  }

  async getWebDocsOptions(input: T.LanguageServer.GetWebDocsOptionsRequestInput) {
    const req = new (PB as any).GetWebDocsOptionsRequest(input as any);
    return await this.client.getWebDocsOptions(req);
  }

  async updateDevExperiments(input: T.LanguageServer.UpdateDevExperimentsRequestInput) {
    const req = new (PB as any).UpdateDevExperimentsRequest(input as any);
    return await this.client.updateDevExperiments(req);
  }

  async setBaseExperiments(input: T.LanguageServer.SetBaseExperimentsRequestInput) {
    const req = new (PB as any).SetBaseExperimentsRequest(input as any);
    return await this.client.setBaseExperiments(req);
  }

  async getUnleashData(input: T.LanguageServer.GetUnleashDataRequestInput) {
    const req = new (PB as any).GetUnleashDataRequest(input as any);
    return await this.client.getUnleashData(req);
  }

  async getModelStatuses(input: T.LanguageServer.GetModelStatusesRequestInput) {
    const req = new (PB as any).GetModelStatusesRequest(input as any);
    return await this.client.getModelStatuses(req);
  }

  async getAllWorkflows(input: T.LanguageServer.GetAllWorkflowsRequestInput) {
    const req = new (PB as any).GetAllWorkflowsRequest(input as any);
    return await this.client.getAllWorkflows(req);
  }

  async getAllCustomAgentConfigs(input: T.LanguageServer.GetAllCustomAgentConfigsRequestInput) {
    const req = new (PB as any).GetAllCustomAgentConfigsRequest(input as any);
    return await this.client.getAllCustomAgentConfigs(req);
  }

  async copyBuiltinWorkflowToWorkspace(input: T.LanguageServer.CopyBuiltinWorkflowToWorkspaceRequestInput) {
    const req = new (PB as any).CopyBuiltinWorkflowToWorkspaceRequest(input as any);
    return await this.client.copyBuiltinWorkflowToWorkspace(req);
  }

  async getAllRules(input: T.LanguageServer.GetAllRulesRequestInput) {
    const req = new (PB as any).GetAllRulesRequest(input as any);
    return await this.client.getAllRules(req);
  }

  async getAllSkills(input: T.LanguageServer.GetAllSkillsRequestInput) {
    const req = new (PB as any).GetAllSkillsRequest(input as any);
    return await this.client.getAllSkills(req);
  }

  async getSkillMarketplaceLink(input: T.LanguageServer.GetSkillMarketplaceLinkRequestInput) {
    const req = new (PB as any).GetSkillMarketplaceLinkRequest(input as any);
    return await this.client.getSkillMarketplaceLink(req);
  }

  async generateSkillInstallationCL(input: T.LanguageServer.GenerateSkillInstallationCLRequestInput) {
    const req = new (PB as any).GenerateSkillInstallationCLRequest(input as any);
    return await this.client.generateSkillInstallationCL(req);
  }

  async scanSkillsConfigFile(input: T.LanguageServer.ScanSkillsConfigFileRequestInput) {
    const req = new (PB as any).ScanSkillsConfigFileRequest(input as any);
    return await this.client.scanSkillsConfigFile(req);
  }

  async listMcpResources(input: T.LanguageServer.ListMcpResourcesRequestInput) {
    const req = new (PB as any).ListMcpResourcesRequest(input as any);
    return await this.client.listMcpResources(req);
  }

  async listMcpPrompts(input: T.LanguageServer.ListMcpPromptsRequestInput) {
    const req = new (PB as any).ListMcpPromptsRequest(input as any);
    return await this.client.listMcpPrompts(req);
  }

  async getMcpPrompt(input: T.LanguageServer.GetMcpPromptRequestInput) {
    const req = new (PB as any).GetMcpPromptRequest(input as any);
    return await this.client.getMcpPrompt(req);
  }

  async updateEnterpriseExperimentsFromUrl(input: T.LanguageServer.UpdateEnterpriseExperimentsFromUrlRequestInput) {
    const req = new (PB as any).UpdateEnterpriseExperimentsFromUrlRequest(input as any);
    return await this.client.updateEnterpriseExperimentsFromUrl(req);
  }

  async importFromCursor(input: T.LanguageServer.ImportFromCursorRequestInput) {
    const req = new (PB as any).ImportFromCursorRequest(input as any);
    return await this.client.importFromCursor(req);
  }

  async createCustomizationFile(input: T.LanguageServer.CreateCustomizationFileRequestInput) {
    const req = new (PB as any).CreateCustomizationFileRequest(input as any);
    return await this.client.createCustomizationFile(req);
  }

  async listCustomizationPathsByFile(input: T.LanguageServer.ListCustomizationPathsByFileRequestInput) {
    const req = new (PB as any).ListCustomizationPathsByFileRequest(input as any);
    return await this.client.listCustomizationPathsByFile(req);
  }

  async updateCustomizationPathsFile(input: T.LanguageServer.UpdateCustomizationPathsFileRequestInput) {
    const req = new (PB as any).UpdateCustomizationPathsFileRequest(input as any);
    return await this.client.updateCustomizationPathsFile(req);
  }

  async getTeamOrganizationalControls(input: T.LanguageServer.GetTeamOrganizationalControlsRequestInput) {
    const req = new (PB as any).GetTeamOrganizationalControlsRequest(input as any);
    return await this.client.getTeamOrganizationalControls(req);
  }

  async recordUserGrep(input: T.LanguageServer.RecordUserGrepRequestInput) {
    const req = new (PB as any).RecordUserGrepRequest(input as any);
    return await this.client.recordUserGrep(req);
  }

  async createTrajectoryShare(input: T.LanguageServer.CreateTrajectoryShareRequestInput) {
    const req = new (PB as any).CreateTrajectoryShareRequest(input as any);
    return await this.client.createTrajectoryShare(req);
  }

  async getCascadeTrajectory(input: T.LanguageServer.GetCascadeTrajectoryRequestInput) {
    const req = new (PB as any).GetCascadeTrajectoryRequest(input as any);
    return await this.client.getCascadeTrajectory(req);
  }

  async getArtifactSnapshots(input: T.LanguageServer.GetArtifactSnapshotsRequestInput) {
    const req = new (PB as any).GetArtifactSnapshotsRequest(input as any);
    return await this.client.getArtifactSnapshots(req);
  }

  async getUserTrajectory(input: T.LanguageServer.GetUserTrajectoryRequestInput) {
    const req = new (PB as any).GetUserTrajectoryRequest(input as any);
    return await this.client.getUserTrajectory(req);
  }

  async getCascadeTrajectorySteps(input: T.LanguageServer.GetCascadeTrajectoryStepsRequestInput) {
    const req = new (PB as any).GetCascadeTrajectoryStepsRequest(input as any);
    return await this.client.getCascadeTrajectorySteps(req);
  }

  async getCascadeTrajectoryGeneratorMetadata(input: T.LanguageServer.GetCascadeTrajectoryGeneratorMetadataRequestInput) {
    const req = new (PB as any).GetCascadeTrajectoryGeneratorMetadataRequest(input as any);
    return await this.client.getCascadeTrajectoryGeneratorMetadata(req);
  }

  async getPatchAndCodeChange(input: T.LanguageServer.GetPatchAndCodeChangeRequestInput) {
    const req = new (PB as any).GetPatchAndCodeChangeRequest(input as any);
    return await this.client.getPatchAndCodeChange(req);
  }

  async convertTrajectoryToMarkdown(input: T.LanguageServer.ConvertTrajectoryToMarkdownRequestInput) {
    const req = new (PB as any).ConvertTrajectoryToMarkdownRequest(input as any);
    return await this.client.convertTrajectoryToMarkdown(req);
  }

  async loadTrajectory(input: T.LanguageServer.LoadTrajectoryRequestInput) {
    const req = new (PB as any).LoadTrajectoryRequest(input as any);
    return await this.client.loadTrajectory(req);
  }

  async getAvailableCascadePlugins(input: T.LanguageServer.GetAvailableCascadePluginsRequestInput) {
    const req = new (PB as any).GetAvailableCascadePluginsRequest(input as any);
    return await this.client.getAvailableCascadePlugins(req);
  }

  async installCascadePlugin(input: T.LanguageServer.InstallCascadePluginRequestInput) {
    const req = new (PB as any).InstallCascadePluginRequest(input as any);
    return await this.client.installCascadePlugin(req);
  }

  async getCascadePluginById(input: T.LanguageServer.GetCascadePluginByIdRequestInput) {
    const req = new (PB as any).GetCascadePluginByIdRequest(input as any);
    return await this.client.getCascadePluginById(req);
  }

  async getAllPlugins(input: T.LanguageServer.GetAllPluginsRequestInput) {
    const req = new (PB as any).GetAllPluginsRequest(input as any);
    return await this.client.getAllPlugins(req);
  }

  async updateCustomization(input: T.LanguageServer.UpdateCustomizationRequestInput) {
    const req = new (PB as any).UpdateCustomizationRequest(input as any);
    return await this.client.updateCustomization(req);
  }

  async getAgentScripts(input: T.LanguageServer.GetAgentScriptsRequestInput) {
    const req = new (PB as any).GetAgentScriptsRequest(input as any);
    return await this.client.getAgentScripts(req);
  }

  async saveAgentScriptCommandSpec(input: T.LanguageServer.SaveAgentScriptCommandSpecRequestInput) {
    const req = new (PB as any).SaveAgentScriptCommandSpecRequest(input as any);
    return await this.client.saveAgentScriptCommandSpec(req);
  }

  async recordLints(input: T.LanguageServer.RecordLintsRequestInput) {
    const req = new (PB as any).RecordLintsRequest(input as any);
    return await this.client.recordLints(req);
  }

  async replayGroundTruthTrajectory(input: T.LanguageServer.ReplayGroundTruthTrajectoryRequestInput) {
    const req = new (PB as any).ReplayGroundTruthTrajectoryRequest(input as any);
    return await this.client.replayGroundTruthTrajectory(req);
  }

  async createReplayWorkspace(input: T.LanguageServer.CreateReplayWorkspaceRequestInput) {
    const req = new (PB as any).CreateReplayWorkspaceRequest(input as any);
    return await this.client.createReplayWorkspace(req);
  }

  async loadReplayConversation(input: T.LanguageServer.LoadReplayConversationRequestInput) {
    const req = new (PB as any).LoadReplayConversationRequest(input as any);
    return await this.client.loadReplayConversation(req);
  }

  async recordInteractiveCascadeFeedback(input: T.LanguageServer.RecordInteractiveCascadeFeedbackRequestInput) {
    const req = new (PB as any).RecordInteractiveCascadeFeedbackRequest(input as any);
    return await this.client.recordInteractiveCascadeFeedback(req);
  }

  async getCascadeNuxes(input: T.LanguageServer.GetCascadeNuxesRequestInput) {
    const req = new (PB as any).GetCascadeNuxesRequest(input as any);
    return await this.client.getCascadeNuxes(req);
  }

  async getTranscription(input: T.LanguageServer.GetTranscriptionRequestInput) {
    const req = new (PB as any).GetTranscriptionRequest(input as any);
    return await this.client.getTranscription(req);
  }

  async sendAudioChunk(input: T.LanguageServer.SendAudioChunkRequestInput) {
    const req = new (PB as any).SendAudioChunkRequest(input as any);
    return await this.client.sendAudioChunk(req);
  }

  async endAudioSession(input: T.LanguageServer.EndAudioSessionRequestInput) {
    const req = new (PB as any).EndAudioSessionRequest(input as any);
    return await this.client.endAudioSession(req);
  }

  async getStaticExperimentStatus(input: T.LanguageServer.GetStaticExperimentStatusRequestInput) {
    const req = new (PB as any).GetStaticExperimentStatusRequest(input as any);
    return await this.client.getStaticExperimentStatus(req);
  }

  async recordAnalyticsEvent(input: T.LanguageServer.RecordAnalyticsEventRequestInput) {
    const req = new (PB as any).RecordAnalyticsEventRequest(input as any);
    return await this.client.recordAnalyticsEvent(req);
  }

  async recordError(input: T.LanguageServer.RecordErrorRequestInput) {
    const req = new (PB as any).RecordErrorRequest(input as any);
    return await this.client.recordError(req);
  }

  async recordObservabilityData(input: T.LanguageServer.RecordObservabilityDataRequestInput) {
    const req = new (PB as any).RecordObservabilityDataRequest(input as any);
    return await this.client.recordObservabilityData(req);
  }

  async listPages(input: T.LanguageServer.ListPagesRequestInput) {
    const req = new (PB as any).ListPagesRequest(input as any);
    return await this.client.listPages(req);
  }

  async browserValidateCascadeOrCancelOverlay(input: T.LanguageServer.BrowserValidateCascadeOrCancelOverlayRequestInput) {
    const req = new (PB as any).BrowserValidateCascadeOrCancelOverlayRequest(input as any);
    return await this.client.browserValidateCascadeOrCancelOverlay(req);
  }

  async openUrl(input: T.LanguageServer.OpenUrlRequestInput) {
    const req = new (PB as any).OpenUrlRequest(input as any);
    return await this.client.openUrl(req);
  }

  async focusUserPage(input: T.LanguageServer.FocusUserPageRequestInput) {
    const req = new (PB as any).FocusUserPageRequest(input as any);
    return await this.client.focusUserPage(req);
  }

  async addToBrowserWhitelist(input: T.LanguageServer.AddToBrowserWhitelistRequestInput) {
    const req = new (PB as any).AddToBrowserWhitelistRequest(input as any);
    return await this.client.addToBrowserWhitelist(req);
  }

  async captureConsoleLogs(input: T.LanguageServer.CaptureConsoleLogsRequestInput) {
    const req = new (PB as any).CaptureConsoleLogsRequest(input as any);
    return await this.client.captureConsoleLogs(req);
  }

  async startScreenRecording(input: T.LanguageServer.StartScreenRecordingRequestInput) {
    const req = new (PB as any).StartScreenRecordingRequest(input as any);
    return await this.client.startScreenRecording(req);
  }

  async saveScreenRecording(input: T.LanguageServer.SaveScreenRecordingRequestInput) {
    const req = new (PB as any).SaveScreenRecordingRequest(input as any);
    return await this.client.saveScreenRecording(req);
  }

  async getBrowserWhitelistFilePath(input: T.LanguageServer.GetBrowserWhitelistFilePathRequestInput) {
    const req = new (PB as any).GetBrowserWhitelistFilePathRequest(input as any);
    return await this.client.getBrowserWhitelistFilePath(req);
  }

  async handleScreenRecording(input: T.LanguageServer.HandleScreenRecordingRequestInput) {
    const req = new (PB as any).HandleScreenRecordingRequest(input as any);
    return await this.client.handleScreenRecording(req);
  }

  async getAllBrowserWhitelistedUrls(input: T.LanguageServer.GetAllBrowserWhitelistedUrlsRequestInput) {
    const req = new (PB as any).GetAllBrowserWhitelistedUrlsRequest(input as any);
    return await this.client.getAllBrowserWhitelistedUrls(req);
  }

  async captureScreenshot(input: T.LanguageServer.CaptureScreenshotRequestInput) {
    const req = new (PB as any).CaptureScreenshotRequest(input as any);
    return await this.client.captureScreenshot(req);
  }

  async smartOpenBrowser(input: T.LanguageServer.SmartOpenBrowserRequestInput) {
    const req = new (PB as any).SmartOpenBrowserRequest(input as any);
    return await this.client.smartOpenBrowser(req);
  }

  async simulateSegFault(input: T.LanguageServer.SimulateSegFaultRequestInput) {
    const req = new (PB as any).SimulateSegFaultRequest(input as any);
    return await this.client.simulateSegFault(req);
  }

  async reconnectExtensionServer(input: T.LanguageServer.ReconnectExtensionServerRequestInput) {
    const req = new (PB as any).ReconnectExtensionServerRequest(input as any);
    return await this.client.reconnectExtensionServer(req);
  }

  async setCloudCodeURL(input: T.LanguageServer.SetCloudCodeURLRequestInput) {
    const req = new (PB as any).SetCloudCodeURLRequest(input as any);
    return await this.client.setCloudCodeURL(req);
  }

  async getTokenBase(input: T.LanguageServer.GetTokenBaseRequestInput) {
    const req = new (PB as any).GetTokenBaseRequest(input as any);
    return await this.client.getTokenBase(req);
  }

  async runCommand(input: T.LanguageServer.RunCommandRequestInput) {
    const req = new (PB as any).RunCommandRequest(input as any);
    return await this.client.runCommand(req);
  }

  async jetboxWriteState(input: T.LanguageServer.JetboxWriteStateRequestInput) {
    const req = new (PB as any).JetboxWriteStateRequest(input as any);
    return await this.client.jetboxWriteState(req);
  }

  async jetboxWriteSummary(input: T.LanguageServer.JetboxWriteSummaryRequestInput) {
    const req = new (PB as any).JetboxWriteSummaryRequest(input as any);
    return await this.client.jetboxWriteSummary(req);
  }

  async jetboxDeleteSummary(input: T.LanguageServer.JetboxDeleteSummaryRequestInput) {
    const req = new (PB as any).JetboxDeleteSummaryRequest(input as any);
    return await this.client.jetboxDeleteSummary(req);
  }

  async searchFiles(input: T.LanguageServer.SearchFilesRequestInput) {
    const req = new (PB as any).SearchFilesRequest(input as any);
    return await this.client.searchFiles(req);
  }

  async searchCode(input: T.LanguageServer.SearchCodeRequestInput) {
    const req = new (PB as any).SearchCodeRequest(input as any);
    return await this.client.searchCode(req);
  }

  async searchConversations(input: T.LanguageServer.SearchConversationsRequestInput) {
    const req = new (PB as any).SearchConversationsRequest(input as any);
    return await this.client.searchConversations(req);
  }

  async jetboxGetLatestVersion(input: T.LanguageServer.JetboxGetLatestVersionRequestInput) {
    const req = new (PB as any).JetboxGetLatestVersionRequest(input as any);
    return await this.client.jetboxGetLatestVersion(req);
  }

  async getAgentTeamMetadata(input: T.LanguageServer.GetAgentTeamMetadataRequestInput) {
    const req = new (PB as any).GetAgentTeamMetadataRequest(input as any);
    return await this.client.getAgentTeamMetadata(req);
  }

  async getCodeFrequencyForRepo(input: T.LanguageServer.GetCodeFrequencyForRepoRequestInput) {
    const req = new (PB as any).GetCodeFrequencyForRepoRequest(input as any);
    return await this.client.getCodeFrequencyForRepo(req);
  }

  async sendAgentMessage(input: T.LanguageServer.SendAgentMessageRequestInput) {
    const req = new (PB as any).SendAgentMessageRequest(input as any);
    return await this.client.sendAgentMessage(req);
  }

  async getLoadCodeAssist(input: T.LanguageServer.GetLoadCodeAssistRequestInput) {
    const req = new (PB as any).GetLoadCodeAssistRequest(input as any);
    return await this.client.getLoadCodeAssist(req);
  }

  async getAvailableModels(input: T.LanguageServer.GetAvailableModelsRequestInput) {
    const req = new (PB as any).GetAvailableModelsRequest(input as any);
    return await this.client.getAvailableModels(req);
  }

}