// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY
import { Transport, createPromiseClient } from "@connectrpc/connect";
import { T } from "./index.js";
import * as ServiceMod from "../gen/exa/language_server_pb/language_server_connect.js";
import * as PB from "../gen/exa/language_server_pb/language_server_pb.js";

export class LanguageServerFacade {
  private client;
  constructor(transport: Transport) {
    this.client = createPromiseClient((ServiceMod as any).LanguageServerService, transport);
  }

  async provideCompletionFeedback(input: T.LanguageServer.ProvideCompletionFeedbackRequest): Promise<T.LanguageServer.ProvideCompletionFeedbackResponse> {
    const req = new (PB as any).ProvideCompletionFeedbackRequest(input as any);
    const res = await this.client.provideCompletionFeedback(req);
    return (res as any) as T.LanguageServer.ProvideCompletionFeedbackResponse;
  }

  async heartbeat(input: T.LanguageServer.HeartbeatRequest): Promise<T.LanguageServer.HeartbeatResponse> {
    const req = new (PB as any).HeartbeatRequest(input as any);
    const res = await this.client.heartbeat(req);
    return (res as any) as T.LanguageServer.HeartbeatResponse;
  }

  async getStatus(input: T.LanguageServer.GetStatusRequest): Promise<T.LanguageServer.GetStatusResponse> {
    const req = new (PB as any).GetStatusRequest(input as any);
    const res = await this.client.getStatus(req);
    return (res as any) as T.LanguageServer.GetStatusResponse;
  }

  async getCommandModelConfigs(input: T.LanguageServer.GetCommandModelConfigsRequest): Promise<T.LanguageServer.GetCommandModelConfigsResponse> {
    const req = new (PB as any).GetCommandModelConfigsRequest(input as any);
    const res = await this.client.getCommandModelConfigs(req);
    return (res as any) as T.LanguageServer.GetCommandModelConfigsResponse;
  }

  async getCascadeModelConfigs(input: T.LanguageServer.GetCascadeModelConfigsRequest): Promise<T.LanguageServer.GetCascadeModelConfigsResponse> {
    const req = new (PB as any).GetCascadeModelConfigsRequest(input as any);
    const res = await this.client.getCascadeModelConfigs(req);
    return (res as any) as T.LanguageServer.GetCascadeModelConfigsResponse;
  }

  async getStandaloneDir(input: T.LanguageServer.GetStandaloneDirRequest): Promise<T.LanguageServer.GetStandaloneDirResponse> {
    const req = new (PB as any).GetStandaloneDirRequest(input as any);
    const res = await this.client.getStandaloneDir(req);
    return (res as any) as T.LanguageServer.GetStandaloneDirResponse;
  }

  async recordEvent(input: T.LanguageServer.RecordEventRequest): Promise<T.LanguageServer.RecordEventResponse> {
    const req = new (PB as any).RecordEventRequest(input as any);
    const res = await this.client.recordEvent(req);
    return (res as any) as T.LanguageServer.RecordEventResponse;
  }

  async recordSidecarEvent(input: T.LanguageServer.RecordSidecarEventRequest): Promise<T.LanguageServer.RecordSidecarEventResponse> {
    const req = new (PB as any).RecordSidecarEventRequest(input as any);
    const res = await this.client.recordSidecarEvent(req);
    return (res as any) as T.LanguageServer.RecordSidecarEventResponse;
  }

  async getSidecars(input: T.LanguageServer.GetSidecarsRequest): Promise<T.LanguageServer.GetSidecarsResponse> {
    const req = new (PB as any).GetSidecarsRequest(input as any);
    const res = await this.client.getSidecars(req);
    return (res as any) as T.LanguageServer.GetSidecarsResponse;
  }

  async getSidecarEvents(input: T.LanguageServer.GetSidecarEventsRequest): Promise<T.LanguageServer.GetSidecarEventsResponse> {
    const req = new (PB as any).GetSidecarEventsRequest(input as any);
    const res = await this.client.getSidecarEvents(req);
    return (res as any) as T.LanguageServer.GetSidecarEventsResponse;
  }

  async listSidecarLogFiles(input: T.LanguageServer.ListSidecarLogFilesRequest): Promise<T.LanguageServer.ListSidecarLogFilesResponse> {
    const req = new (PB as any).ListSidecarLogFilesRequest(input as any);
    const res = await this.client.listSidecarLogFiles(req);
    return (res as any) as T.LanguageServer.ListSidecarLogFilesResponse;
  }

  async manageSidecar(input: T.LanguageServer.ManageSidecarRequest): Promise<T.LanguageServer.ManageSidecarResponse> {
    const req = new (PB as any).ManageSidecarRequest(input as any);
    const res = await this.client.manageSidecar(req);
    return (res as any) as T.LanguageServer.ManageSidecarResponse;
  }

  async resolveSidecarConfig(input: T.LanguageServer.ResolveSidecarConfigRequest): Promise<T.LanguageServer.ResolveSidecarConfigResponse> {
    const req = new (PB as any).ResolveSidecarConfigRequest(input as any);
    const res = await this.client.resolveSidecarConfig(req);
    return (res as any) as T.LanguageServer.ResolveSidecarConfigResponse;
  }

  async registerGdmUser(input: T.LanguageServer.RegisterGdmUserRequest): Promise<T.LanguageServer.RegisterGdmUserResponse> {
    const req = new (PB as any).RegisterGdmUserRequest(input as any);
    const res = await this.client.registerGdmUser(req);
    return (res as any) as T.LanguageServer.RegisterGdmUserResponse;
  }

  async migrateApiKey(input: T.LanguageServer.MigrateApiKeyRequest): Promise<T.LanguageServer.MigrateApiKeyResponse> {
    const req = new (PB as any).MigrateApiKeyRequest(input as any);
    const res = await this.client.migrateApiKey(req);
    return (res as any) as T.LanguageServer.MigrateApiKeyResponse;
  }

  async wellSupportedLanguages(input: T.LanguageServer.WellSupportedLanguagesRequest): Promise<T.LanguageServer.WellSupportedLanguagesResponse> {
    const req = new (PB as any).WellSupportedLanguagesRequest(input as any);
    const res = await this.client.wellSupportedLanguages(req);
    return (res as any) as T.LanguageServer.WellSupportedLanguagesResponse;
  }

  async recordSearchDocOpen(input: T.LanguageServer.RecordSearchDocOpenRequest): Promise<T.LanguageServer.RecordSearchDocOpenResponse> {
    const req = new (PB as any).RecordSearchDocOpenRequest(input as any);
    const res = await this.client.recordSearchDocOpen(req);
    return (res as any) as T.LanguageServer.RecordSearchDocOpenResponse;
  }

  async recordSearchResultsView(input: T.LanguageServer.RecordSearchResultsViewRequest): Promise<T.LanguageServer.RecordSearchResultsViewResponse> {
    const req = new (PB as any).RecordSearchResultsViewRequest(input as any);
    const res = await this.client.recordSearchResultsView(req);
    return (res as any) as T.LanguageServer.RecordSearchResultsViewResponse;
  }

  async getMcpServerTemplates(input: T.LanguageServer.GetMcpServerTemplatesRequest): Promise<T.LanguageServer.GetMcpServerTemplatesResponse> {
    const req = new (PB as any).GetMcpServerTemplatesRequest(input as any);
    const res = await this.client.getMcpServerTemplates(req);
    return (res as any) as T.LanguageServer.GetMcpServerTemplatesResponse;
  }

  async addTrackedWorkspace(input: T.LanguageServer.AddTrackedWorkspaceRequest): Promise<T.LanguageServer.AddTrackedWorkspaceResponse> {
    const req = new (PB as any).AddTrackedWorkspaceRequest(input as any);
    const res = await this.client.addTrackedWorkspace(req);
    return (res as any) as T.LanguageServer.AddTrackedWorkspaceResponse;
  }

  async removeTrackedWorkspace(input: T.LanguageServer.RemoveTrackedWorkspaceRequest): Promise<T.LanguageServer.RemoveTrackedWorkspaceResponse> {
    const req = new (PB as any).RemoveTrackedWorkspaceRequest(input as any);
    const res = await this.client.removeTrackedWorkspace(req);
    return (res as any) as T.LanguageServer.RemoveTrackedWorkspaceResponse;
  }

  async smartFocusConversation(input: T.LanguageServer.SmartFocusConversationRequest): Promise<T.LanguageServer.SmartFocusConversationResponse> {
    const req = new (PB as any).SmartFocusConversationRequest(input as any);
    const res = await this.client.smartFocusConversation(req);
    return (res as any) as T.LanguageServer.SmartFocusConversationResponse;
  }

  async statUri(input: T.LanguageServer.StatUriRequest): Promise<T.LanguageServer.StatUriResponse> {
    const req = new (PB as any).StatUriRequest(input as any);
    const res = await this.client.statUri(req);
    return (res as any) as T.LanguageServer.StatUriResponse;
  }

  async readFile(input: T.LanguageServer.ReadFileRequest): Promise<T.LanguageServer.ReadFileResponse> {
    const req = new (PB as any).ReadFileRequest(input as any);
    const res = await this.client.readFile(req);
    return (res as any) as T.LanguageServer.ReadFileResponse;
  }

  async checkDevToolsActivePort(input: T.LanguageServer.CheckDevToolsActivePortRequest): Promise<T.LanguageServer.CheckDevToolsActivePortResponse> {
    const req = new (PB as any).CheckDevToolsActivePortRequest(input as any);
    const res = await this.client.checkDevToolsActivePort(req);
    return (res as any) as T.LanguageServer.CheckDevToolsActivePortResponse;
  }

  async writeFile(input: T.LanguageServer.WriteFileRequest): Promise<T.LanguageServer.WriteFileResponse> {
    const req = new (PB as any).WriteFileRequest(input as any);
    const res = await this.client.writeFile(req);
    return (res as any) as T.LanguageServer.WriteFileResponse;
  }

  async createDebugBundle(input: T.LanguageServer.CreateDebugBundleRequest): Promise<T.LanguageServer.CreateDebugBundleResponse> {
    const req = new (PB as any).CreateDebugBundleRequest(input as any);
    const res = await this.client.createDebugBundle(req);
    return (res as any) as T.LanguageServer.CreateDebugBundleResponse;
  }

  async uploadToDrive(input: T.LanguageServer.UploadToDriveRequest): Promise<T.LanguageServer.UploadToDriveResponse> {
    const req = new (PB as any).UploadToDriveRequest(input as any);
    const res = await this.client.uploadToDrive(req);
    return (res as any) as T.LanguageServer.UploadToDriveResponse;
  }

  async readDir(input: T.LanguageServer.ReadDirRequest): Promise<T.LanguageServer.ReadDirResponse> {
    const req = new (PB as any).ReadDirRequest(input as any);
    const res = await this.client.readDir(req);
    return (res as any) as T.LanguageServer.ReadDirResponse;
  }

  async deleteFileOrDirectory(input: T.LanguageServer.DeleteFileOrDirectoryRequest): Promise<T.LanguageServer.DeleteFileOrDirectoryResponse> {
    const req = new (PB as any).DeleteFileOrDirectoryRequest(input as any);
    const res = await this.client.deleteFileOrDirectory(req);
    return (res as any) as T.LanguageServer.DeleteFileOrDirectoryResponse;
  }

  async getKnowledgeItems(input: T.LanguageServer.GetKnowledgeItemsRequest): Promise<T.LanguageServer.GetKnowledgeItemsResponse> {
    const req = new (PB as any).GetKnowledgeItemsRequest(input as any);
    const res = await this.client.getKnowledgeItems(req);
    return (res as any) as T.LanguageServer.GetKnowledgeItemsResponse;
  }

  async setBrowserOpenConversation(input: T.LanguageServer.SetBrowserOpenConversationRequest): Promise<T.LanguageServer.SetBrowserOpenConversationResponse> {
    const req = new (PB as any).SetBrowserOpenConversationRequest(input as any);
    const res = await this.client.setBrowserOpenConversation(req);
    return (res as any) as T.LanguageServer.SetBrowserOpenConversationResponse;
  }

  async getBrowserOpenConversation(input: T.LanguageServer.GetBrowserOpenConversationRequest): Promise<T.LanguageServer.GetBrowserOpenConversationResponse> {
    const req = new (PB as any).GetBrowserOpenConversationRequest(input as any);
    const res = await this.client.getBrowserOpenConversation(req);
    return (res as any) as T.LanguageServer.GetBrowserOpenConversationResponse;
  }

  async refreshContextForIdeAction(input: T.LanguageServer.RefreshContextForIdeActionRequest): Promise<T.LanguageServer.RefreshContextForIdeActionResponse> {
    const req = new (PB as any).RefreshContextForIdeActionRequest(input as any);
    const res = await this.client.refreshContextForIdeAction(req);
    return (res as any) as T.LanguageServer.RefreshContextForIdeActionResponse;
  }

  async getMatchingContextScopeItems(input: T.LanguageServer.GetMatchingContextScopeItemsRequest): Promise<T.LanguageServer.GetMatchingContextScopeItemsResponse> {
    const req = new (PB as any).GetMatchingContextScopeItemsRequest(input as any);
    const res = await this.client.getMatchingContextScopeItems(req);
    return (res as any) as T.LanguageServer.GetMatchingContextScopeItemsResponse;
  }

  async recordChatFeedback(input: T.LanguageServer.RecordChatFeedbackRequest): Promise<T.LanguageServer.RecordChatFeedbackResponse> {
    const req = new (PB as any).RecordChatFeedbackRequest(input as any);
    const res = await this.client.recordChatFeedback(req);
    return (res as any) as T.LanguageServer.RecordChatFeedbackResponse;
  }

  async recordChatPanelSession(input: T.LanguageServer.RecordChatPanelSessionRequest): Promise<T.LanguageServer.RecordChatPanelSessionResponse> {
    const req = new (PB as any).RecordChatPanelSessionRequest(input as any);
    const res = await this.client.recordChatPanelSession(req);
    return (res as any) as T.LanguageServer.RecordChatPanelSessionResponse;
  }

  async shouldEnableUnleash(input: T.LanguageServer.ShouldEnableUnleashRequest): Promise<T.LanguageServer.ShouldEnableUnleashResponse> {
    const req = new (PB as any).ShouldEnableUnleashRequest(input as any);
    const res = await this.client.shouldEnableUnleash(req);
    return (res as any) as T.LanguageServer.ShouldEnableUnleashResponse;
  }

  async getWorkspaceEditState(input: T.LanguageServer.GetWorkspaceEditStateRequest): Promise<T.LanguageServer.GetWorkspaceEditStateResponse> {
    const req = new (PB as any).GetWorkspaceEditStateRequest(input as any);
    const res = await this.client.getWorkspaceEditState(req);
    return (res as any) as T.LanguageServer.GetWorkspaceEditStateResponse;
  }

  async getRepoInfos(input: T.LanguageServer.GetRepoInfosRequest): Promise<T.LanguageServer.GetRepoInfosResponse> {
    const req = new (PB as any).GetRepoInfosRequest(input as any);
    const res = await this.client.getRepoInfos(req);
    return (res as any) as T.LanguageServer.GetRepoInfosResponse;
  }

  async listGobRepos(input: T.LanguageServer.ListGobReposRequest): Promise<T.LanguageServer.ListGobReposResponse> {
    const req = new (PB as any).ListGobReposRequest(input as any);
    const res = await this.client.listGobRepos(req);
    return (res as any) as T.LanguageServer.ListGobReposResponse;
  }

  async getWorkspaceInfos(input: T.LanguageServer.GetWorkspaceInfosRequest): Promise<T.LanguageServer.GetWorkspaceInfosResponse> {
    const req = new (PB as any).GetWorkspaceInfosRequest(input as any);
    const res = await this.client.getWorkspaceInfos(req);
    return (res as any) as T.LanguageServer.GetWorkspaceInfosResponse;
  }

  async getLocalUserInfo(input: T.LanguageServer.GetLocalUserInfoRequest): Promise<T.LanguageServer.GetLocalUserInfoResponse> {
    const req = new (PB as any).GetLocalUserInfoRequest(input as any);
    const res = await this.client.getLocalUserInfo(req);
    return (res as any) as T.LanguageServer.GetLocalUserInfoResponse;
  }

  async resolveWorkspaceUrlPreview(input: T.LanguageServer.ResolveWorkspaceUrlPreviewRequest): Promise<T.LanguageServer.ResolveWorkspaceUrlPreviewResponse> {
    const req = new (PB as any).ResolveWorkspaceUrlPreviewRequest(input as any);
    const res = await this.client.resolveWorkspaceUrlPreview(req);
    return (res as any) as T.LanguageServer.ResolveWorkspaceUrlPreviewResponse;
  }

  async searchDriveFiles(input: T.LanguageServer.SearchDriveFilesRequest): Promise<T.LanguageServer.SearchDriveFilesResponse> {
    const req = new (PB as any).SearchDriveFilesRequest(input as any);
    const res = await this.client.searchDriveFiles(req);
    return (res as any) as T.LanguageServer.SearchDriveFilesResponse;
  }

  async createWorktree(input: T.LanguageServer.CreateWorktreeRequest): Promise<T.LanguageServer.CreateWorktreeResponse> {
    const req = new (PB as any).CreateWorktreeRequest(input as any);
    const res = await this.client.createWorktree(req);
    return (res as any) as T.LanguageServer.CreateWorktreeResponse;
  }

  async deleteWorktree(input: T.LanguageServer.DeleteWorktreeRequest): Promise<T.LanguageServer.DeleteWorktreeResponse> {
    const req = new (PB as any).DeleteWorktreeRequest(input as any);
    const res = await this.client.deleteWorktree(req);
    return (res as any) as T.LanguageServer.DeleteWorktreeResponse;
  }

  async checkoutWorktree(input: T.LanguageServer.CheckoutWorktreeRequest): Promise<T.LanguageServer.CheckoutWorktreeResponse> {
    const req = new (PB as any).CheckoutWorktreeRequest(input as any);
    const res = await this.client.checkoutWorktree(req);
    return (res as any) as T.LanguageServer.CheckoutWorktreeResponse;
  }

  async getWorktreeDiff(input: T.LanguageServer.GetWorktreeDiffRequest): Promise<T.LanguageServer.GetWorktreeDiffResponse> {
    const req = new (PB as any).GetWorktreeDiffRequest(input as any);
    const res = await this.client.getWorktreeDiff(req);
    return (res as any) as T.LanguageServer.GetWorktreeDiffResponse;
  }

  async getBattleWorktreeDiff(input: T.LanguageServer.GetBattleWorktreeDiffRequest): Promise<T.LanguageServer.GetBattleWorktreeDiffResponse> {
    const req = new (PB as any).GetBattleWorktreeDiffRequest(input as any);
    const res = await this.client.getBattleWorktreeDiff(req);
    return (res as any) as T.LanguageServer.GetBattleWorktreeDiffResponse;
  }

  async createCitcWorkspace(input: T.LanguageServer.CreateCitcWorkspaceRequest): Promise<T.LanguageServer.CreateCitcWorkspaceResponse> {
    const req = new (PB as any).CreateCitcWorkspaceRequest(input as any);
    const res = await this.client.createCitcWorkspace(req);
    return (res as any) as T.LanguageServer.CreateCitcWorkspaceResponse;
  }

  async setWorkingDirectories(input: T.LanguageServer.SetWorkingDirectoriesRequest): Promise<T.LanguageServer.SetWorkingDirectoriesResponse> {
    const req = new (PB as any).SetWorkingDirectoriesRequest(input as any);
    const res = await this.client.setWorkingDirectories(req);
    return (res as any) as T.LanguageServer.SetWorkingDirectoriesResponse;
  }

  async getWorkingDirectories(input: T.LanguageServer.GetWorkingDirectoriesRequest): Promise<T.LanguageServer.GetWorkingDirectoriesResponse> {
    const req = new (PB as any).GetWorkingDirectoriesRequest(input as any);
    const res = await this.client.getWorkingDirectories(req);
    return (res as any) as T.LanguageServer.GetWorkingDirectoriesResponse;
  }

  async getJJWorktrees(input: T.LanguageServer.GetJJWorktreesRequest): Promise<T.LanguageServer.GetJJWorktreesResponse> {
    const req = new (PB as any).GetJJWorktreesRequest(input as any);
    const res = await this.client.getJJWorktrees(req);
    return (res as any) as T.LanguageServer.GetJJWorktreesResponse;
  }

  async getRevisionArtifact(input: T.LanguageServer.GetRevisionArtifactRequest): Promise<T.LanguageServer.GetRevisionArtifactResponse> {
    const req = new (PB as any).GetRevisionArtifactRequest(input as any);
    const res = await this.client.getRevisionArtifact(req);
    return (res as any) as T.LanguageServer.GetRevisionArtifactResponse;
  }

  async getVersionControlState(input: T.LanguageServer.GetVersionControlStateRequest): Promise<T.LanguageServer.GetVersionControlStateResponse> {
    const req = new (PB as any).GetVersionControlStateRequest(input as any);
    const res = await this.client.getVersionControlState(req);
    return (res as any) as T.LanguageServer.GetVersionControlStateResponse;
  }

  async getVersionControlFileContent(input: T.LanguageServer.GetVersionControlFileContentRequest): Promise<T.LanguageServer.GetVersionControlFileContentResponse> {
    const req = new (PB as any).GetVersionControlFileContentRequest(input as any);
    const res = await this.client.getVersionControlFileContent(req);
    return (res as any) as T.LanguageServer.GetVersionControlFileContentResponse;
  }

  async getCommitDetails(input: T.LanguageServer.GetCommitDetailsRequest): Promise<T.LanguageServer.GetCommitDetailsResponse> {
    const req = new (PB as any).GetCommitDetailsRequest(input as any);
    const res = await this.client.getCommitDetails(req);
    return (res as any) as T.LanguageServer.GetCommitDetailsResponse;
  }

  async checkoutCommit(input: T.LanguageServer.CheckoutCommitRequest): Promise<T.LanguageServer.CheckoutCommitResponse> {
    const req = new (PB as any).CheckoutCommitRequest(input as any);
    const res = await this.client.checkoutCommit(req);
    return (res as any) as T.LanguageServer.CheckoutCommitResponse;
  }

  async discardFileChanges(input: T.LanguageServer.DiscardFileChangesRequest): Promise<T.LanguageServer.DiscardFileChangesResponse> {
    const req = new (PB as any).DiscardFileChangesRequest(input as any);
    const res = await this.client.discardFileChanges(req);
    return (res as any) as T.LanguageServer.DiscardFileChangesResponse;
  }

  async figSync(input: T.LanguageServer.FigSyncRequest): Promise<T.LanguageServer.FigSyncResponse> {
    const req = new (PB as any).FigSyncRequest(input as any);
    const res = await this.client.figSync(req);
    return (res as any) as T.LanguageServer.FigSyncResponse;
  }

  async figCommit(input: T.LanguageServer.FigCommitRequest): Promise<T.LanguageServer.FigCommitResponse> {
    const req = new (PB as any).FigCommitRequest(input as any);
    const res = await this.client.figCommit(req);
    return (res as any) as T.LanguageServer.FigCommitResponse;
  }

  async figAmend(input: T.LanguageServer.FigAmendRequest): Promise<T.LanguageServer.FigAmendResponse> {
    const req = new (PB as any).FigAmendRequest(input as any);
    const res = await this.client.figAmend(req);
    return (res as any) as T.LanguageServer.FigAmendResponse;
  }

  async figUpload(input: T.LanguageServer.FigUploadRequest): Promise<T.LanguageServer.FigUploadResponse> {
    const req = new (PB as any).FigUploadRequest(input as any);
    const res = await this.client.figUpload(req);
    return (res as any) as T.LanguageServer.FigUploadResponse;
  }

  async jjSync(input: T.LanguageServer.JjSyncRequest): Promise<T.LanguageServer.JjSyncResponse> {
    const req = new (PB as any).JjSyncRequest(input as any);
    const res = await this.client.jjSync(req);
    return (res as any) as T.LanguageServer.JjSyncResponse;
  }

  async jjCommit(input: T.LanguageServer.JjCommitRequest): Promise<T.LanguageServer.JjCommitResponse> {
    const req = new (PB as any).JjCommitRequest(input as any);
    const res = await this.client.jjCommit(req);
    return (res as any) as T.LanguageServer.JjCommitResponse;
  }

  async jjSquash(input: T.LanguageServer.JjSquashRequest): Promise<T.LanguageServer.JjSquashResponse> {
    const req = new (PB as any).JjSquashRequest(input as any);
    const res = await this.client.jjSquash(req);
    return (res as any) as T.LanguageServer.JjSquashResponse;
  }

  async jjUpload(input: T.LanguageServer.JjUploadRequest): Promise<T.LanguageServer.JjUploadResponse> {
    const req = new (PB as any).JjUploadRequest(input as any);
    const res = await this.client.jjUpload(req);
    return (res as any) as T.LanguageServer.JjUploadResponse;
  }

  async gitStage(input: T.LanguageServer.GitStageRequest): Promise<T.LanguageServer.GitStageResponse> {
    const req = new (PB as any).GitStageRequest(input as any);
    const res = await this.client.gitStage(req);
    return (res as any) as T.LanguageServer.GitStageResponse;
  }

  async gitUnstage(input: T.LanguageServer.GitUnstageRequest): Promise<T.LanguageServer.GitUnstageResponse> {
    const req = new (PB as any).GitUnstageRequest(input as any);
    const res = await this.client.gitUnstage(req);
    return (res as any) as T.LanguageServer.GitUnstageResponse;
  }

  async gitCommit(input: T.LanguageServer.GitCommitRequest): Promise<T.LanguageServer.GitCommitResponse> {
    const req = new (PB as any).GitCommitRequest(input as any);
    const res = await this.client.gitCommit(req);
    return (res as any) as T.LanguageServer.GitCommitResponse;
  }

  async gitDiscard(input: T.LanguageServer.GitDiscardRequest): Promise<T.LanguageServer.GitDiscardResponse> {
    const req = new (PB as any).GitDiscardRequest(input as any);
    const res = await this.client.gitDiscard(req);
    return (res as any) as T.LanguageServer.GitDiscardResponse;
  }

  async generateCommitMessage(input: T.LanguageServer.GenerateCommitMessageRequest): Promise<T.LanguageServer.GenerateCommitMessageResponse> {
    const req = new (PB as any).GenerateCommitMessageRequest(input as any);
    const res = await this.client.generateCommitMessage(req);
    return (res as any) as T.LanguageServer.GenerateCommitMessageResponse;
  }

  async recordCommitMessageSave(input: T.LanguageServer.RecordCommitMessageSaveRequest): Promise<T.LanguageServer.RecordCommitMessageSaveResponse> {
    const req = new (PB as any).RecordCommitMessageSaveRequest(input as any);
    const res = await this.client.recordCommitMessageSave(req);
    return (res as any) as T.LanguageServer.RecordCommitMessageSaveResponse;
  }

  async updatePRForWorktree(input: T.LanguageServer.UpdatePRForWorktreeRequest): Promise<T.LanguageServer.UpdatePRForWorktreeResponse> {
    const req = new (PB as any).UpdatePRForWorktreeRequest(input as any);
    const res = await this.client.updatePRForWorktree(req);
    return (res as any) as T.LanguageServer.UpdatePRForWorktreeResponse;
  }

  async sendActionToChatPanel(input: T.LanguageServer.SendActionToChatPanelRequest): Promise<T.LanguageServer.SendActionToChatPanelResponse> {
    const req = new (PB as any).SendActionToChatPanelRequest(input as any);
    const res = await this.client.sendActionToChatPanel(req);
    return (res as any) as T.LanguageServer.SendActionToChatPanelResponse;
  }

  async getUserSettings(input: T.LanguageServer.GetUserSettingsRequest): Promise<T.LanguageServer.GetUserSettingsResponse> {
    const req = new (PB as any).GetUserSettingsRequest(input as any);
    const res = await this.client.getUserSettings(req);
    return (res as any) as T.LanguageServer.GetUserSettingsResponse;
  }

  async setUserSettings(input: T.LanguageServer.SetUserSettingsRequest): Promise<T.LanguageServer.SetUserSettingsResponse> {
    const req = new (PB as any).SetUserSettingsRequest(input as any);
    const res = await this.client.setUserSettings(req);
    return (res as any) as T.LanguageServer.SetUserSettingsResponse;
  }

  async fetchUserInfo(input: T.LanguageServer.FetchUserInfoRequest): Promise<T.LanguageServer.FetchUserInfoResponse> {
    const req = new (PB as any).FetchUserInfoRequest(input as any);
    const res = await this.client.fetchUserInfo(req);
    return (res as any) as T.LanguageServer.FetchUserInfoResponse;
  }

  async setUserInfo(input: T.LanguageServer.SetUserInfoRequest): Promise<T.LanguageServer.SetUserInfoResponse> {
    const req = new (PB as any).SetUserInfoRequest(input as any);
    const res = await this.client.setUserInfo(req);
    return (res as any) as T.LanguageServer.SetUserInfoResponse;
  }

  async getDebugDiagnostics(input: T.LanguageServer.GetDebugDiagnosticsRequest): Promise<T.LanguageServer.GetDebugDiagnosticsResponse> {
    const req = new (PB as any).GetDebugDiagnosticsRequest(input as any);
    const res = await this.client.getDebugDiagnostics(req);
    return (res as any) as T.LanguageServer.GetDebugDiagnosticsResponse;
  }

  async dumpFlightRecorder(input: T.LanguageServer.DumpFlightRecorderRequest): Promise<T.LanguageServer.DumpFlightRecorderResponse> {
    const req = new (PB as any).DumpFlightRecorderRequest(input as any);
    const res = await this.client.dumpFlightRecorder(req);
    return (res as any) as T.LanguageServer.DumpFlightRecorderResponse;
  }

  async dumpPprof(input: T.LanguageServer.DumpPprofRequest): Promise<T.LanguageServer.DumpPprofResponse> {
    const req = new (PB as any).DumpPprofRequest(input as any);
    const res = await this.client.dumpPprof(req);
    return (res as any) as T.LanguageServer.DumpPprofResponse;
  }

  async getUserAnalyticsSummary(input: T.LanguageServer.GetUserAnalyticsSummaryRequest): Promise<T.LanguageServer.GetUserAnalyticsSummaryResponse> {
    const req = new (PB as any).GetUserAnalyticsSummaryRequest(input as any);
    const res = await this.client.getUserAnalyticsSummary(req);
    return (res as any) as T.LanguageServer.GetUserAnalyticsSummaryResponse;
  }

  async getUserStatus(input: T.LanguageServer.GetUserStatusRequest): Promise<T.LanguageServer.GetUserStatusResponse> {
    const req = new (PB as any).GetUserStatusRequest(input as any);
    const res = await this.client.getUserStatus(req);
    return (res as any) as T.LanguageServer.GetUserStatusResponse;
  }

  async getProfileData(input: T.LanguageServer.GetProfileDataRequest): Promise<T.LanguageServer.GetProfileDataResponse> {
    const req = new (PB as any).GetProfileDataRequest(input as any);
    const res = await this.client.getProfileData(req);
    return (res as any) as T.LanguageServer.GetProfileDataResponse;
  }

  async getChangelog(input: T.LanguageServer.GetChangelogRequest): Promise<T.LanguageServer.GetChangelogResponse> {
    const req = new (PB as any).GetChangelogRequest(input as any);
    const res = await this.client.getChangelog(req);
    return (res as any) as T.LanguageServer.GetChangelogResponse;
  }

  async setupUniversitySandbox(input: T.LanguageServer.SetupUniversitySandboxRequest): Promise<T.LanguageServer.SetupUniversitySandboxResponse> {
    const req = new (PB as any).SetupUniversitySandboxRequest(input as any);
    const res = await this.client.setupUniversitySandbox(req);
    return (res as any) as T.LanguageServer.SetupUniversitySandboxResponse;
  }

  async exit(input: T.LanguageServer.ExitRequest): Promise<T.LanguageServer.ExitResponse> {
    const req = new (PB as any).ExitRequest(input as any);
    const res = await this.client.exit(req);
    return (res as any) as T.LanguageServer.ExitResponse;
  }

  async restart(input: T.LanguageServer.RestartRequest): Promise<T.LanguageServer.RestartResponse> {
    const req = new (PB as any).RestartRequest(input as any);
    const res = await this.client.restart(req);
    return (res as any) as T.LanguageServer.RestartResponse;
  }

  async resetOnboarding(input: T.LanguageServer.ResetOnboardingRequest): Promise<T.LanguageServer.ResetOnboardingResponse> {
    const req = new (PB as any).ResetOnboardingRequest(input as any);
    const res = await this.client.resetOnboarding(req);
    return (res as any) as T.LanguageServer.ResetOnboardingResponse;
  }

  async skipOnboarding(input: T.LanguageServer.SkipOnboardingRequest): Promise<T.LanguageServer.SkipOnboardingResponse> {
    const req = new (PB as any).SkipOnboardingRequest(input as any);
    const res = await this.client.skipOnboarding(req);
    return (res as any) as T.LanguageServer.SkipOnboardingResponse;
  }

  async getTermsOfService(input: T.LanguageServer.GetTermsOfServiceRequest): Promise<T.LanguageServer.GetTermsOfServiceResponse> {
    const req = new (PB as any).GetTermsOfServiceRequest(input as any);
    const res = await this.client.getTermsOfService(req);
    return (res as any) as T.LanguageServer.GetTermsOfServiceResponse;
  }

  async acceptTermsOfService(input: T.LanguageServer.AcceptTermsOfServiceRequest): Promise<T.LanguageServer.AcceptTermsOfServiceResponse> {
    const req = new (PB as any).AcceptTermsOfServiceRequest(input as any);
    const res = await this.client.acceptTermsOfService(req);
    return (res as any) as T.LanguageServer.AcceptTermsOfServiceResponse;
  }

  async listLicenses(input: T.LanguageServer.ListLicensesRequest): Promise<T.LanguageServer.ListLicensesResponse> {
    const req = new (PB as any).ListLicensesRequest(input as any);
    const res = await this.client.listLicenses(req);
    return (res as any) as T.LanguageServer.ListLicensesResponse;
  }

  async selectLicense(input: T.LanguageServer.SelectLicenseRequest): Promise<T.LanguageServer.SelectLicenseResponse> {
    const req = new (PB as any).SelectLicenseRequest(input as any);
    const res = await this.client.selectLicense(req);
    return (res as any) as T.LanguageServer.SelectLicenseResponse;
  }

  async selfAssignLicense(input: T.LanguageServer.SelfAssignLicenseRequest): Promise<T.LanguageServer.SelfAssignLicenseResponse> {
    const req = new (PB as any).SelfAssignLicenseRequest(input as any);
    const res = await this.client.selfAssignLicense(req);
    return (res as any) as T.LanguageServer.SelfAssignLicenseResponse;
  }

  async getUserTrajectoryDebug(input: T.LanguageServer.GetUserTrajectoryDebugRequest): Promise<T.LanguageServer.GetUserTrajectoryDebugResponse> {
    const req = new (PB as any).GetUserTrajectoryDebugRequest(input as any);
    const res = await this.client.getUserTrajectoryDebug(req);
    return (res as any) as T.LanguageServer.GetUserTrajectoryDebugResponse;
  }

  async getUserTrajectoryDescriptions(input: T.LanguageServer.GetUserTrajectoryDescriptionsRequest): Promise<T.LanguageServer.GetUserTrajectoryDescriptionsResponse> {
    const req = new (PB as any).GetUserTrajectoryDescriptionsRequest(input as any);
    const res = await this.client.getUserTrajectoryDescriptions(req);
    return (res as any) as T.LanguageServer.GetUserTrajectoryDescriptionsResponse;
  }

  async getCascadeMemories(input: T.LanguageServer.GetCascadeMemoriesRequest): Promise<T.LanguageServer.GetCascadeMemoriesResponse> {
    const req = new (PB as any).GetCascadeMemoriesRequest(input as any);
    const res = await this.client.getCascadeMemories(req);
    return (res as any) as T.LanguageServer.GetCascadeMemoriesResponse;
  }

  async deleteCascadeMemory(input: T.LanguageServer.DeleteCascadeMemoryRequest): Promise<T.LanguageServer.DeleteCascadeMemoryResponse> {
    const req = new (PB as any).DeleteCascadeMemoryRequest(input as any);
    const res = await this.client.deleteCascadeMemory(req);
    return (res as any) as T.LanguageServer.DeleteCascadeMemoryResponse;
  }

  async updateCascadeMemory(input: T.LanguageServer.UpdateCascadeMemoryRequest): Promise<T.LanguageServer.UpdateCascadeMemoryResponse> {
    const req = new (PB as any).UpdateCascadeMemoryRequest(input as any);
    const res = await this.client.updateCascadeMemory(req);
    return (res as any) as T.LanguageServer.UpdateCascadeMemoryResponse;
  }

  async getUserMemories(input: T.LanguageServer.GetUserMemoriesRequest): Promise<T.LanguageServer.GetUserMemoriesResponse> {
    const req = new (PB as any).GetUserMemoriesRequest(input as any);
    const res = await this.client.getUserMemories(req);
    return (res as any) as T.LanguageServer.GetUserMemoriesResponse;
  }

  async updateConversationAnnotations(input: T.LanguageServer.UpdateConversationAnnotationsRequest): Promise<T.LanguageServer.UpdateConversationAnnotationsResponse> {
    const req = new (PB as any).UpdateConversationAnnotationsRequest(input as any);
    const res = await this.client.updateConversationAnnotations(req);
    return (res as any) as T.LanguageServer.UpdateConversationAnnotationsResponse;
  }

  async startCascade(input: T.LanguageServer.StartCascadeRequest): Promise<T.LanguageServer.StartCascadeResponse> {
    const req = new (PB as any).StartCascadeRequest(input as any);
    const res = await this.client.startCascade(req);
    return (res as any) as T.LanguageServer.StartCascadeResponse;
  }

  async loadSharedTrajectory(input: T.LanguageServer.LoadSharedTrajectoryRequest): Promise<T.LanguageServer.LoadSharedTrajectoryResponse> {
    const req = new (PB as any).LoadSharedTrajectoryRequest(input as any);
    const res = await this.client.loadSharedTrajectory(req);
    return (res as any) as T.LanguageServer.LoadSharedTrajectoryResponse;
  }

  async getSlashCommands(input: T.LanguageServer.GetSlashCommandsRequest): Promise<T.LanguageServer.GetSlashCommandsResponse> {
    const req = new (PB as any).GetSlashCommandsRequest(input as any);
    const res = await this.client.getSlashCommands(req);
    return (res as any) as T.LanguageServer.GetSlashCommandsResponse;
  }

  async startBattleMode(input: T.LanguageServer.StartBattleModeRequest): Promise<T.LanguageServer.StartBattleModeResponse> {
    const req = new (PB as any).StartBattleModeRequest(input as any);
    const res = await this.client.startBattleMode(req);
    return (res as any) as T.LanguageServer.StartBattleModeResponse;
  }

  async endBattleMode(input: T.LanguageServer.EndBattleModeRequest): Promise<T.LanguageServer.EndBattleModeResponse> {
    const req = new (PB as any).EndBattleModeRequest(input as any);
    const res = await this.client.endBattleMode(req);
    return (res as any) as T.LanguageServer.EndBattleModeResponse;
  }

  async eliminateBattleModeArm(input: T.LanguageServer.EliminateBattleModeArmRequest): Promise<T.LanguageServer.EliminateBattleModeArmResponse> {
    const req = new (PB as any).EliminateBattleModeArmRequest(input as any);
    const res = await this.client.eliminateBattleModeArm(req);
    return (res as any) as T.LanguageServer.EliminateBattleModeArmResponse;
  }

  async setOrVerifyStaticConfig(input: T.LanguageServer.SetOrVerifyStaticConfigRequest): Promise<T.LanguageServer.SetOrVerifyStaticConfigResponse> {
    const req = new (PB as any).SetOrVerifyStaticConfigRequest(input as any);
    const res = await this.client.setOrVerifyStaticConfig(req);
    return (res as any) as T.LanguageServer.SetOrVerifyStaticConfigResponse;
  }

  async forkConversation(input: T.LanguageServer.ForkConversationRequest): Promise<T.LanguageServer.ForkConversationResponse> {
    const req = new (PB as any).ForkConversationRequest(input as any);
    const res = await this.client.forkConversation(req);
    return (res as any) as T.LanguageServer.ForkConversationResponse;
  }

  async cancelCascadeInvocation(input: T.LanguageServer.CancelCascadeInvocationRequest): Promise<T.LanguageServer.CancelCascadeInvocationResponse> {
    const req = new (PB as any).CancelCascadeInvocationRequest(input as any);
    const res = await this.client.cancelCascadeInvocation(req);
    return (res as any) as T.LanguageServer.CancelCascadeInvocationResponse;
  }

  async forceStopCascadeTree(input: T.LanguageServer.ForceStopCascadeTreeRequest): Promise<T.LanguageServer.ForceStopCascadeTreeResponse> {
    const req = new (PB as any).ForceStopCascadeTreeRequest(input as any);
    const res = await this.client.forceStopCascadeTree(req);
    return (res as any) as T.LanguageServer.ForceStopCascadeTreeResponse;
  }

  async cancelCascadeSteps(input: T.LanguageServer.CancelCascadeStepsRequest): Promise<T.LanguageServer.CancelCascadeStepsResponse> {
    const req = new (PB as any).CancelCascadeStepsRequest(input as any);
    const res = await this.client.cancelCascadeSteps(req);
    return (res as any) as T.LanguageServer.CancelCascadeStepsResponse;
  }

  async sendStepsToBackground(input: T.LanguageServer.SendStepsToBackgroundRequest): Promise<T.LanguageServer.SendStepsToBackgroundResponse> {
    const req = new (PB as any).SendStepsToBackgroundRequest(input as any);
    const res = await this.client.sendStepsToBackground(req);
    return (res as any) as T.LanguageServer.SendStepsToBackgroundResponse;
  }

  async skipBrowserSubagent(input: T.LanguageServer.SkipBrowserSubagentRequest): Promise<T.LanguageServer.SkipBrowserSubagentResponse> {
    const req = new (PB as any).SkipBrowserSubagentRequest(input as any);
    const res = await this.client.skipBrowserSubagent(req);
    return (res as any) as T.LanguageServer.SkipBrowserSubagentResponse;
  }

  async getCascadeModelConfigData(input: T.LanguageServer.GetCascadeModelConfigDataRequest): Promise<T.LanguageServer.CascadeModelConfigData> {
    const req = new (PB as any).GetCascadeModelConfigDataRequest(input as any);
    const res = await this.client.getCascadeModelConfigData(req);
    return (res as any) as T.LanguageServer.CascadeModelConfigData;
  }

  async sendUserCascadeMessage(input: T.LanguageServer.SendUserCascadeMessageRequest): Promise<T.LanguageServer.SendUserCascadeMessageResponse> {
    const req = new (PB as any).SendUserCascadeMessageRequest(input as any);
    const res = await this.client.sendUserCascadeMessage(req);
    return (res as any) as T.LanguageServer.SendUserCascadeMessageResponse;
  }

  async detectBattleModeAutoTrigger(input: T.LanguageServer.DetectBattleModeAutoTriggerRequest): Promise<T.LanguageServer.DetectBattleModeAutoTriggerResponse> {
    const req = new (PB as any).DetectBattleModeAutoTriggerRequest(input as any);
    const res = await this.client.detectBattleModeAutoTrigger(req);
    return (res as any) as T.LanguageServer.DetectBattleModeAutoTriggerResponse;
  }

  async signalExecutableIdle(input: T.LanguageServer.SignalExecutableIdleRequest): Promise<T.LanguageServer.SignalExecutableIdleResponse> {
    const req = new (PB as any).SignalExecutableIdleRequest(input as any);
    const res = await this.client.signalExecutableIdle(req);
    return (res as any) as T.LanguageServer.SignalExecutableIdleResponse;
  }

  async waitForConversationFullyIdle(input: T.LanguageServer.WaitForConversationFullyIdleRequest): Promise<T.LanguageServer.WaitForConversationFullyIdleResponse> {
    const req = new (PB as any).WaitForConversationFullyIdleRequest(input as any);
    const res = await this.client.waitForConversationFullyIdle(req);
    return (res as any) as T.LanguageServer.WaitForConversationFullyIdleResponse;
  }

  async sendAllQueuedMessages(input: T.LanguageServer.SendAllQueuedMessagesRequest): Promise<T.LanguageServer.SendAllQueuedMessagesResponse> {
    const req = new (PB as any).SendAllQueuedMessagesRequest(input as any);
    const res = await this.client.sendAllQueuedMessages(req);
    return (res as any) as T.LanguageServer.SendAllQueuedMessagesResponse;
  }

  async deleteQueuedUserInputStep(input: T.LanguageServer.DeleteQueuedUserInputStepRequest): Promise<T.LanguageServer.DeleteQueuedUserInputStepResponse> {
    const req = new (PB as any).DeleteQueuedUserInputStepRequest(input as any);
    const res = await this.client.deleteQueuedUserInputStep(req);
    return (res as any) as T.LanguageServer.DeleteQueuedUserInputStepResponse;
  }

  async revertToCascadeStep(input: T.LanguageServer.RevertToCascadeStepRequest): Promise<T.LanguageServer.RevertToCascadeStepResponse> {
    const req = new (PB as any).RevertToCascadeStepRequest(input as any);
    const res = await this.client.revertToCascadeStep(req);
    return (res as any) as T.LanguageServer.RevertToCascadeStepResponse;
  }

  async getRevertPreview(input: T.LanguageServer.GetRevertPreviewRequest): Promise<T.LanguageServer.GetRevertPreviewResponse> {
    const req = new (PB as any).GetRevertPreviewRequest(input as any);
    const res = await this.client.getRevertPreview(req);
    return (res as any) as T.LanguageServer.GetRevertPreviewResponse;
  }

  async recordUserStepSnapshot(input: T.LanguageServer.RecordUserStepSnapshotRequest): Promise<T.LanguageServer.RecordUserStepSnapshotResponse> {
    const req = new (PB as any).RecordUserStepSnapshotRequest(input as any);
    const res = await this.client.recordUserStepSnapshot(req);
    return (res as any) as T.LanguageServer.RecordUserStepSnapshotResponse;
  }

  async getAllCascadeTrajectories(input: T.LanguageServer.GetAllCascadeTrajectoriesRequest): Promise<T.LanguageServer.GetAllCascadeTrajectoriesResponse> {
    const req = new (PB as any).GetAllCascadeTrajectoriesRequest(input as any);
    const res = await this.client.getAllCascadeTrajectories(req);
    return (res as any) as T.LanguageServer.GetAllCascadeTrajectoriesResponse;
  }

  async handleCascadeUserInteraction(input: T.LanguageServer.HandleCascadeUserInteractionRequest): Promise<T.LanguageServer.HandleCascadeUserInteractionResponse> {
    const req = new (PB as any).HandleCascadeUserInteractionRequest(input as any);
    const res = await this.client.handleCascadeUserInteraction(req);
    return (res as any) as T.LanguageServer.HandleCascadeUserInteractionResponse;
  }

  async acknowledgeCascadeCodeEdit(input: T.LanguageServer.AcknowledgeCascadeCodeEditRequest): Promise<T.LanguageServer.AcknowledgeCascadeCodeEditResponse> {
    const req = new (PB as any).AcknowledgeCascadeCodeEditRequest(input as any);
    const res = await this.client.acknowledgeCascadeCodeEdit(req);
    return (res as any) as T.LanguageServer.AcknowledgeCascadeCodeEditResponse;
  }

  async acknowledgeCodeActionStep(input: T.LanguageServer.AcknowledgeCodeActionStepRequest): Promise<T.LanguageServer.AcknowledgeCodeActionStepResponse> {
    const req = new (PB as any).AcknowledgeCodeActionStepRequest(input as any);
    const res = await this.client.acknowledgeCodeActionStep(req);
    return (res as any) as T.LanguageServer.AcknowledgeCodeActionStepResponse;
  }

  async getCodeValidationStates(input: T.LanguageServer.GetCodeValidationStatesRequest): Promise<T.LanguageServer.GetCodeValidationStatesResponse> {
    const req = new (PB as any).GetCodeValidationStatesRequest(input as any);
    const res = await this.client.getCodeValidationStates(req);
    return (res as any) as T.LanguageServer.GetCodeValidationStatesResponse;
  }

  async deleteCascadeTrajectory(input: T.LanguageServer.DeleteCascadeTrajectoryRequest): Promise<T.LanguageServer.DeleteCascadeTrajectoryResponse> {
    const req = new (PB as any).DeleteCascadeTrajectoryRequest(input as any);
    const res = await this.client.deleteCascadeTrajectory(req);
    return (res as any) as T.LanguageServer.DeleteCascadeTrajectoryResponse;
  }

  async getConversationMetadata(input: T.LanguageServer.GetConversationMetadataRequest): Promise<T.LanguageServer.GetConversationMetadataResponse> {
    const req = new (PB as any).GetConversationMetadataRequest(input as any);
    const res = await this.client.getConversationMetadata(req);
    return (res as any) as T.LanguageServer.GetConversationMetadataResponse;
  }

  async getTurnDiff(input: T.LanguageServer.GetTurnDiffRequest): Promise<T.LanguageServer.GetTurnDiffResponse> {
    const req = new (PB as any).GetTurnDiffRequest(input as any);
    const res = await this.client.getTurnDiff(req);
    return (res as any) as T.LanguageServer.GetTurnDiffResponse;
  }

  async getCodeActionDiff(input: T.LanguageServer.GetCodeActionDiffRequest): Promise<T.LanguageServer.GetCodeActionDiffResponse> {
    const req = new (PB as any).GetCodeActionDiffRequest(input as any);
    const res = await this.client.getCodeActionDiff(req);
    return (res as any) as T.LanguageServer.GetCodeActionDiffResponse;
  }

  async initializeCascadePanelState(input: T.LanguageServer.InitializeCascadePanelStateRequest): Promise<T.LanguageServer.InitializeCascadePanelStateResponse> {
    const req = new (PB as any).InitializeCascadePanelStateRequest(input as any);
    const res = await this.client.initializeCascadePanelState(req);
    return (res as any) as T.LanguageServer.InitializeCascadePanelStateResponse;
  }

  async requestAgentStatePageUpdate(input: T.LanguageServer.AgentStatePageUpdateRequest): Promise<T.LanguageServer.AgentStatePageUpdateResponse> {
    const req = new (PB as any).AgentStatePageUpdateRequest(input as any);
    const res = await this.client.requestAgentStatePageUpdate(req);
    return (res as any) as T.LanguageServer.AgentStatePageUpdateResponse;
  }

  async forceBackgroundResearchRefresh(input: T.LanguageServer.ForceBackgroundResearchRefreshRequest): Promise<T.LanguageServer.ForceBackgroundResearchRefreshResponse> {
    const req = new (PB as any).ForceBackgroundResearchRefreshRequest(input as any);
    const res = await this.client.forceBackgroundResearchRefresh(req);
    return (res as any) as T.LanguageServer.ForceBackgroundResearchRefreshResponse;
  }

  async resolveOutstandingSteps(input: T.LanguageServer.ResolveOutstandingStepsRequest): Promise<T.LanguageServer.ResolveOutstandingStepsResponse> {
    const req = new (PB as any).ResolveOutstandingStepsRequest(input as any);
    const res = await this.client.resolveOutstandingSteps(req);
    return (res as any) as T.LanguageServer.ResolveOutstandingStepsResponse;
  }

  async refreshMcpServers(input: T.LanguageServer.RefreshMcpServersRequest): Promise<T.LanguageServer.RefreshMcpServersResponse> {
    const req = new (PB as any).RefreshMcpServersRequest(input as any);
    const res = await this.client.refreshMcpServers(req);
    return (res as any) as T.LanguageServer.RefreshMcpServersResponse;
  }

  async toggleMcpServer(input: T.LanguageServer.ToggleMcpServerRequest): Promise<T.LanguageServer.ToggleMcpServerResponse> {
    const req = new (PB as any).ToggleMcpServerRequest(input as any);
    const res = await this.client.toggleMcpServer(req);
    return (res as any) as T.LanguageServer.ToggleMcpServerResponse;
  }

  async getMcpServerStates(input: T.LanguageServer.GetMcpServerStatesRequest): Promise<T.LanguageServer.GetMcpServerStatesResponse> {
    const req = new (PB as any).GetMcpServerStatesRequest(input as any);
    const res = await this.client.getMcpServerStates(req);
    return (res as any) as T.LanguageServer.GetMcpServerStatesResponse;
  }

  async completeMcpOAuth(input: T.LanguageServer.CompleteMcpOAuthRequest): Promise<T.LanguageServer.CompleteMcpOAuthResponse> {
    const req = new (PB as any).CompleteMcpOAuthRequest(input as any);
    const res = await this.client.completeMcpOAuth(req);
    return (res as any) as T.LanguageServer.CompleteMcpOAuthResponse;
  }

  async disconnectMcpOAuth(input: T.LanguageServer.DisconnectMcpOAuthRequest): Promise<T.LanguageServer.DisconnectMcpOAuthResponse> {
    const req = new (PB as any).DisconnectMcpOAuthRequest(input as any);
    const res = await this.client.disconnectMcpOAuth(req);
    return (res as any) as T.LanguageServer.DisconnectMcpOAuthResponse;
  }

  async createTerminal(input: T.LanguageServer.CreateTerminalRequest): Promise<T.LanguageServer.CreateTerminalResponse> {
    const req = new (PB as any).CreateTerminalRequest(input as any);
    const res = await this.client.createTerminal(req);
    return (res as any) as T.LanguageServer.CreateTerminalResponse;
  }

  async sendTerminalInput(input: T.LanguageServer.SendTerminalInputRequest): Promise<T.LanguageServer.SendTerminalInputResponse> {
    const req = new (PB as any).SendTerminalInputRequest(input as any);
    const res = await this.client.sendTerminalInput(req);
    return (res as any) as T.LanguageServer.SendTerminalInputResponse;
  }

  async closeTerminal(input: T.LanguageServer.CloseTerminalRequest): Promise<T.LanguageServer.CloseTerminalResponse> {
    const req = new (PB as any).CloseTerminalRequest(input as any);
    const res = await this.client.closeTerminal(req);
    return (res as any) as T.LanguageServer.CloseTerminalResponse;
  }

  async listTerminals(input: T.LanguageServer.ListTerminalsRequest): Promise<T.LanguageServer.ListTerminalsResponse> {
    const req = new (PB as any).ListTerminalsRequest(input as any);
    const res = await this.client.listTerminals(req);
    return (res as any) as T.LanguageServer.ListTerminalsResponse;
  }

  async getModelResponse(input: T.LanguageServer.GetModelResponseRequest): Promise<T.LanguageServer.GetModelResponseResponse> {
    const req = new (PB as any).GetModelResponseRequest(input as any);
    const res = await this.client.getModelResponse(req);
    return (res as any) as T.LanguageServer.GetModelResponseResponse;
  }

  async saveMediaAsArtifact(input: T.LanguageServer.SaveMediaAsArtifactRequest): Promise<T.LanguageServer.SaveMediaAsArtifactResponse> {
    const req = new (PB as any).SaveMediaAsArtifactRequest(input as any);
    const res = await this.client.saveMediaAsArtifact(req);
    return (res as any) as T.LanguageServer.SaveMediaAsArtifactResponse;
  }

  async deleteMediaArtifact(input: T.LanguageServer.DeleteMediaArtifactRequest): Promise<T.LanguageServer.DeleteMediaArtifactResponse> {
    const req = new (PB as any).DeleteMediaArtifactRequest(input as any);
    const res = await this.client.deleteMediaArtifact(req);
    return (res as any) as T.LanguageServer.DeleteMediaArtifactResponse;
  }

  async getWebDocsOptions(input: T.LanguageServer.GetWebDocsOptionsRequest): Promise<T.LanguageServer.GetWebDocsOptionsResponse> {
    const req = new (PB as any).GetWebDocsOptionsRequest(input as any);
    const res = await this.client.getWebDocsOptions(req);
    return (res as any) as T.LanguageServer.GetWebDocsOptionsResponse;
  }

  async updateDevExperiments(input: T.LanguageServer.UpdateDevExperimentsRequest): Promise<T.LanguageServer.UpdateDevExperimentsResponse> {
    const req = new (PB as any).UpdateDevExperimentsRequest(input as any);
    const res = await this.client.updateDevExperiments(req);
    return (res as any) as T.LanguageServer.UpdateDevExperimentsResponse;
  }

  async setBaseExperiments(input: T.LanguageServer.SetBaseExperimentsRequest): Promise<T.LanguageServer.SetBaseExperimentsResponse> {
    const req = new (PB as any).SetBaseExperimentsRequest(input as any);
    const res = await this.client.setBaseExperiments(req);
    return (res as any) as T.LanguageServer.SetBaseExperimentsResponse;
  }

  async getUnleashData(input: T.LanguageServer.GetUnleashDataRequest): Promise<T.LanguageServer.GetUnleashDataResponse> {
    const req = new (PB as any).GetUnleashDataRequest(input as any);
    const res = await this.client.getUnleashData(req);
    return (res as any) as T.LanguageServer.GetUnleashDataResponse;
  }

  async getMendelFlags(input: T.LanguageServer.GetMendelFlagsRequest): Promise<T.LanguageServer.GetMendelFlagsResponse> {
    const req = new (PB as any).GetMendelFlagsRequest(input as any);
    const res = await this.client.getMendelFlags(req);
    return (res as any) as T.LanguageServer.GetMendelFlagsResponse;
  }

  async isProjectsEnabledInternally(input: T.LanguageServer.IsProjectsEnabledInternallyRequest): Promise<T.LanguageServer.IsProjectsEnabledInternallyResponse> {
    const req = new (PB as any).IsProjectsEnabledInternallyRequest(input as any);
    const res = await this.client.isProjectsEnabledInternally(req);
    return (res as any) as T.LanguageServer.IsProjectsEnabledInternallyResponse;
  }

  async getModelStatuses(input: T.LanguageServer.GetModelStatusesRequest): Promise<T.LanguageServer.GetModelStatusesResponse> {
    const req = new (PB as any).GetModelStatusesRequest(input as any);
    const res = await this.client.getModelStatuses(req);
    return (res as any) as T.LanguageServer.GetModelStatusesResponse;
  }

  async getAllWorkflows(input: T.LanguageServer.GetAllWorkflowsRequest): Promise<T.LanguageServer.GetAllWorkflowsResponse> {
    const req = new (PB as any).GetAllWorkflowsRequest(input as any);
    const res = await this.client.getAllWorkflows(req);
    return (res as any) as T.LanguageServer.GetAllWorkflowsResponse;
  }

  async getAllCustomAgentConfigs(input: T.LanguageServer.GetAllCustomAgentConfigsRequest): Promise<T.LanguageServer.GetAllCustomAgentConfigsResponse> {
    const req = new (PB as any).GetAllCustomAgentConfigsRequest(input as any);
    const res = await this.client.getAllCustomAgentConfigs(req);
    return (res as any) as T.LanguageServer.GetAllCustomAgentConfigsResponse;
  }

  async copyBuiltinWorkflowToWorkspace(input: T.LanguageServer.CopyBuiltinWorkflowToWorkspaceRequest): Promise<T.LanguageServer.CopyBuiltinWorkflowToWorkspaceResponse> {
    const req = new (PB as any).CopyBuiltinWorkflowToWorkspaceRequest(input as any);
    const res = await this.client.copyBuiltinWorkflowToWorkspace(req);
    return (res as any) as T.LanguageServer.CopyBuiltinWorkflowToWorkspaceResponse;
  }

  async getAllRules(input: T.LanguageServer.GetAllRulesRequest): Promise<T.LanguageServer.GetAllRulesResponse> {
    const req = new (PB as any).GetAllRulesRequest(input as any);
    const res = await this.client.getAllRules(req);
    return (res as any) as T.LanguageServer.GetAllRulesResponse;
  }

  async getAllSkills(input: T.LanguageServer.GetAllSkillsRequest): Promise<T.LanguageServer.GetAllSkillsResponse> {
    const req = new (PB as any).GetAllSkillsRequest(input as any);
    const res = await this.client.getAllSkills(req);
    return (res as any) as T.LanguageServer.GetAllSkillsResponse;
  }

  async getSkillMarketplaceLink(input: T.LanguageServer.GetSkillMarketplaceLinkRequest): Promise<T.LanguageServer.GetSkillMarketplaceLinkResponse> {
    const req = new (PB as any).GetSkillMarketplaceLinkRequest(input as any);
    const res = await this.client.getSkillMarketplaceLink(req);
    return (res as any) as T.LanguageServer.GetSkillMarketplaceLinkResponse;
  }

  async generateSkillInstallationCL(input: T.LanguageServer.GenerateSkillInstallationCLRequest): Promise<T.LanguageServer.GenerateSkillInstallationCLResponse> {
    const req = new (PB as any).GenerateSkillInstallationCLRequest(input as any);
    const res = await this.client.generateSkillInstallationCL(req);
    return (res as any) as T.LanguageServer.GenerateSkillInstallationCLResponse;
  }

  async searchMarketplaceCustomizations(input: T.LanguageServer.SearchMarketplaceCustomizationsRequest): Promise<T.LanguageServer.SearchMarketplaceCustomizationsResponse> {
    const req = new (PB as any).SearchMarketplaceCustomizationsRequest(input as any);
    const res = await this.client.searchMarketplaceCustomizations(req);
    return (res as any) as T.LanguageServer.SearchMarketplaceCustomizationsResponse;
  }

  async scanSkillsConfigFile(input: T.LanguageServer.ScanSkillsConfigFileRequest): Promise<T.LanguageServer.ScanSkillsConfigFileResponse> {
    const req = new (PB as any).ScanSkillsConfigFileRequest(input as any);
    const res = await this.client.scanSkillsConfigFile(req);
    return (res as any) as T.LanguageServer.ScanSkillsConfigFileResponse;
  }

  async listMcpResources(input: T.LanguageServer.ListMcpResourcesRequest): Promise<T.LanguageServer.ListMcpResourcesResponse> {
    const req = new (PB as any).ListMcpResourcesRequest(input as any);
    const res = await this.client.listMcpResources(req);
    return (res as any) as T.LanguageServer.ListMcpResourcesResponse;
  }

  async listMcpPrompts(input: T.LanguageServer.ListMcpPromptsRequest): Promise<T.LanguageServer.ListMcpPromptsResponse> {
    const req = new (PB as any).ListMcpPromptsRequest(input as any);
    const res = await this.client.listMcpPrompts(req);
    return (res as any) as T.LanguageServer.ListMcpPromptsResponse;
  }

  async getMcpPrompt(input: T.LanguageServer.GetMcpPromptRequest): Promise<T.LanguageServer.GetMcpPromptResponse> {
    const req = new (PB as any).GetMcpPromptRequest(input as any);
    const res = await this.client.getMcpPrompt(req);
    return (res as any) as T.LanguageServer.GetMcpPromptResponse;
  }

  async updateEnterpriseExperimentsFromUrl(input: T.LanguageServer.UpdateEnterpriseExperimentsFromUrlRequest): Promise<T.LanguageServer.UpdateEnterpriseExperimentsFromUrlResponse> {
    const req = new (PB as any).UpdateEnterpriseExperimentsFromUrlRequest(input as any);
    const res = await this.client.updateEnterpriseExperimentsFromUrl(req);
    return (res as any) as T.LanguageServer.UpdateEnterpriseExperimentsFromUrlResponse;
  }

  async importFromCursor(input: T.LanguageServer.ImportFromCursorRequest): Promise<T.LanguageServer.ImportFromCursorResponse> {
    const req = new (PB as any).ImportFromCursorRequest(input as any);
    const res = await this.client.importFromCursor(req);
    return (res as any) as T.LanguageServer.ImportFromCursorResponse;
  }

  async createCustomizationFile(input: T.LanguageServer.CreateCustomizationFileRequest): Promise<T.LanguageServer.CreateCustomizationFileResponse> {
    const req = new (PB as any).CreateCustomizationFileRequest(input as any);
    const res = await this.client.createCustomizationFile(req);
    return (res as any) as T.LanguageServer.CreateCustomizationFileResponse;
  }

  async listCustomizationPathsByFile(input: T.LanguageServer.ListCustomizationPathsByFileRequest): Promise<T.LanguageServer.ListCustomizationPathsByFileResponse> {
    const req = new (PB as any).ListCustomizationPathsByFileRequest(input as any);
    const res = await this.client.listCustomizationPathsByFile(req);
    return (res as any) as T.LanguageServer.ListCustomizationPathsByFileResponse;
  }

  async updateCustomizationPathsFile(input: T.LanguageServer.UpdateCustomizationPathsFileRequest): Promise<T.LanguageServer.UpdateCustomizationPathsFileResponse> {
    const req = new (PB as any).UpdateCustomizationPathsFileRequest(input as any);
    const res = await this.client.updateCustomizationPathsFile(req);
    return (res as any) as T.LanguageServer.UpdateCustomizationPathsFileResponse;
  }

  async getTeamOrganizationalControls(input: T.LanguageServer.GetTeamOrganizationalControlsRequest): Promise<T.LanguageServer.GetTeamOrganizationalControlsResponse> {
    const req = new (PB as any).GetTeamOrganizationalControlsRequest(input as any);
    const res = await this.client.getTeamOrganizationalControls(req);
    return (res as any) as T.LanguageServer.GetTeamOrganizationalControlsResponse;
  }

  async recordUserGrep(input: T.LanguageServer.RecordUserGrepRequest): Promise<T.LanguageServer.RecordUserGrepResponse> {
    const req = new (PB as any).RecordUserGrepRequest(input as any);
    const res = await this.client.recordUserGrep(req);
    return (res as any) as T.LanguageServer.RecordUserGrepResponse;
  }

  async createTrajectoryShare(input: T.LanguageServer.CreateTrajectoryShareRequest): Promise<T.LanguageServer.CreateTrajectoryShareResponse> {
    const req = new (PB as any).CreateTrajectoryShareRequest(input as any);
    const res = await this.client.createTrajectoryShare(req);
    return (res as any) as T.LanguageServer.CreateTrajectoryShareResponse;
  }

  async getCascadeTrajectory(input: T.LanguageServer.GetCascadeTrajectoryRequest): Promise<T.LanguageServer.GetCascadeTrajectoryResponse> {
    const req = new (PB as any).GetCascadeTrajectoryRequest(input as any);
    const res = await this.client.getCascadeTrajectory(req);
    return (res as any) as T.LanguageServer.GetCascadeTrajectoryResponse;
  }

  async getArtifactSnapshots(input: T.LanguageServer.GetArtifactSnapshotsRequest): Promise<T.LanguageServer.GetArtifactSnapshotsResponse> {
    const req = new (PB as any).GetArtifactSnapshotsRequest(input as any);
    const res = await this.client.getArtifactSnapshots(req);
    return (res as any) as T.LanguageServer.GetArtifactSnapshotsResponse;
  }

  async getUserTrajectory(input: T.LanguageServer.GetUserTrajectoryRequest): Promise<T.LanguageServer.GetUserTrajectoryResponse> {
    const req = new (PB as any).GetUserTrajectoryRequest(input as any);
    const res = await this.client.getUserTrajectory(req);
    return (res as any) as T.LanguageServer.GetUserTrajectoryResponse;
  }

  async getCascadeTrajectorySteps(input: T.LanguageServer.GetCascadeTrajectoryStepsRequest): Promise<T.LanguageServer.GetCascadeTrajectoryStepsResponse> {
    const req = new (PB as any).GetCascadeTrajectoryStepsRequest(input as any);
    const res = await this.client.getCascadeTrajectorySteps(req);
    return (res as any) as T.LanguageServer.GetCascadeTrajectoryStepsResponse;
  }

  async getCascadeTrajectoryGeneratorMetadata(input: T.LanguageServer.GetCascadeTrajectoryGeneratorMetadataRequest): Promise<T.LanguageServer.GetCascadeTrajectoryGeneratorMetadataResponse> {
    const req = new (PB as any).GetCascadeTrajectoryGeneratorMetadataRequest(input as any);
    const res = await this.client.getCascadeTrajectoryGeneratorMetadata(req);
    return (res as any) as T.LanguageServer.GetCascadeTrajectoryGeneratorMetadataResponse;
  }

  async getCascadeTrajectoryExecutorMetadatas(input: T.LanguageServer.GetCascadeTrajectoryExecutorMetadatasRequest): Promise<T.LanguageServer.GetCascadeTrajectoryExecutorMetadatasResponse> {
    const req = new (PB as any).GetCascadeTrajectoryExecutorMetadatasRequest(input as any);
    const res = await this.client.getCascadeTrajectoryExecutorMetadatas(req);
    return (res as any) as T.LanguageServer.GetCascadeTrajectoryExecutorMetadatasResponse;
  }

  async getPatchAndCodeChange(input: T.LanguageServer.GetPatchAndCodeChangeRequest): Promise<T.LanguageServer.GetPatchAndCodeChangeResponse> {
    const req = new (PB as any).GetPatchAndCodeChangeRequest(input as any);
    const res = await this.client.getPatchAndCodeChange(req);
    return (res as any) as T.LanguageServer.GetPatchAndCodeChangeResponse;
  }

  async convertTrajectoryToMarkdown(input: T.LanguageServer.ConvertTrajectoryToMarkdownRequest): Promise<T.LanguageServer.ConvertTrajectoryToMarkdownResponse> {
    const req = new (PB as any).ConvertTrajectoryToMarkdownRequest(input as any);
    const res = await this.client.convertTrajectoryToMarkdown(req);
    return (res as any) as T.LanguageServer.ConvertTrajectoryToMarkdownResponse;
  }

  async loadTrajectory(input: T.LanguageServer.LoadTrajectoryRequest): Promise<T.LanguageServer.LoadTrajectoryResponse> {
    const req = new (PB as any).LoadTrajectoryRequest(input as any);
    const res = await this.client.loadTrajectory(req);
    return (res as any) as T.LanguageServer.LoadTrajectoryResponse;
  }

  async importProjectFromUrl(input: T.LanguageServer.ImportProjectFromUrlRequest): Promise<T.LanguageServer.ImportProjectFromUrlResponse> {
    const req = new (PB as any).ImportProjectFromUrlRequest(input as any);
    const res = await this.client.importProjectFromUrl(req);
    return (res as any) as T.LanguageServer.ImportProjectFromUrlResponse;
  }

  async getAvailableCascadePlugins(input: T.LanguageServer.GetAvailableCascadePluginsRequest): Promise<T.LanguageServer.GetAvailableCascadePluginsResponse> {
    const req = new (PB as any).GetAvailableCascadePluginsRequest(input as any);
    const res = await this.client.getAvailableCascadePlugins(req);
    return (res as any) as T.LanguageServer.GetAvailableCascadePluginsResponse;
  }

  async installCascadePlugin(input: T.LanguageServer.InstallCascadePluginRequest): Promise<T.LanguageServer.InstallCascadePluginResponse> {
    const req = new (PB as any).InstallCascadePluginRequest(input as any);
    const res = await this.client.installCascadePlugin(req);
    return (res as any) as T.LanguageServer.InstallCascadePluginResponse;
  }

  async getCascadePluginById(input: T.LanguageServer.GetCascadePluginByIdRequest): Promise<T.LanguageServer.GetCascadePluginByIdResponse> {
    const req = new (PB as any).GetCascadePluginByIdRequest(input as any);
    const res = await this.client.getCascadePluginById(req);
    return (res as any) as T.LanguageServer.GetCascadePluginByIdResponse;
  }

  async getAllPlugins(input: T.LanguageServer.GetAllPluginsRequest): Promise<T.LanguageServer.GetAllPluginsResponse> {
    const req = new (PB as any).GetAllPluginsRequest(input as any);
    const res = await this.client.getAllPlugins(req);
    return (res as any) as T.LanguageServer.GetAllPluginsResponse;
  }

  async getBuildWithGooglePlugins(input: T.LanguageServer.GetBuildWithGooglePluginsRequest): Promise<T.LanguageServer.GetBuildWithGooglePluginsResponse> {
    const req = new (PB as any).GetBuildWithGooglePluginsRequest(input as any);
    const res = await this.client.getBuildWithGooglePlugins(req);
    return (res as any) as T.LanguageServer.GetBuildWithGooglePluginsResponse;
  }

  async downloadBuildWithGooglePlugin(input: T.LanguageServer.DownloadBuildWithGooglePluginRequest): Promise<T.LanguageServer.DownloadBuildWithGooglePluginResponse> {
    const req = new (PB as any).DownloadBuildWithGooglePluginRequest(input as any);
    const res = await this.client.downloadBuildWithGooglePlugin(req);
    return (res as any) as T.LanguageServer.DownloadBuildWithGooglePluginResponse;
  }

  async deletePlugin(input: T.LanguageServer.DeletePluginRequest): Promise<T.LanguageServer.DeletePluginResponse> {
    const req = new (PB as any).DeletePluginRequest(input as any);
    const res = await this.client.deletePlugin(req);
    return (res as any) as T.LanguageServer.DeletePluginResponse;
  }

  async updateCustomization(input: T.LanguageServer.UpdateCustomizationRequest): Promise<T.LanguageServer.UpdateCustomizationResponse> {
    const req = new (PB as any).UpdateCustomizationRequest(input as any);
    const res = await this.client.updateCustomization(req);
    return (res as any) as T.LanguageServer.UpdateCustomizationResponse;
  }

  async getAgentScripts(input: T.LanguageServer.GetAgentScriptsRequest): Promise<T.LanguageServer.GetAgentScriptsResponse> {
    const req = new (PB as any).GetAgentScriptsRequest(input as any);
    const res = await this.client.getAgentScripts(req);
    return (res as any) as T.LanguageServer.GetAgentScriptsResponse;
  }

  async listProfiles(input: T.LanguageServer.ListProfilesRequest): Promise<T.LanguageServer.ListProfilesResponse> {
    const req = new (PB as any).ListProfilesRequest(input as any);
    const res = await this.client.listProfiles(req);
    return (res as any) as T.LanguageServer.ListProfilesResponse;
  }

  async saveAgentScriptCommandSpec(input: T.LanguageServer.SaveAgentScriptCommandSpecRequest): Promise<T.LanguageServer.SaveAgentScriptCommandSpecResponse> {
    const req = new (PB as any).SaveAgentScriptCommandSpecRequest(input as any);
    const res = await this.client.saveAgentScriptCommandSpec(req);
    return (res as any) as T.LanguageServer.SaveAgentScriptCommandSpecResponse;
  }

  async recordLints(input: T.LanguageServer.RecordLintsRequest): Promise<T.LanguageServer.RecordLintsResponse> {
    const req = new (PB as any).RecordLintsRequest(input as any);
    const res = await this.client.recordLints(req);
    return (res as any) as T.LanguageServer.RecordLintsResponse;
  }

  async replayGroundTruthTrajectory(input: T.LanguageServer.ReplayGroundTruthTrajectoryRequest): Promise<T.LanguageServer.ReplayGroundTruthTrajectoryResponse> {
    const req = new (PB as any).ReplayGroundTruthTrajectoryRequest(input as any);
    const res = await this.client.replayGroundTruthTrajectory(req);
    return (res as any) as T.LanguageServer.ReplayGroundTruthTrajectoryResponse;
  }

  async loadReplayConversation(input: T.LanguageServer.LoadReplayConversationRequest): Promise<T.LanguageServer.LoadReplayConversationResponse> {
    const req = new (PB as any).LoadReplayConversationRequest(input as any);
    const res = await this.client.loadReplayConversation(req);
    return (res as any) as T.LanguageServer.LoadReplayConversationResponse;
  }

  async recordInteractiveCascadeFeedback(input: T.LanguageServer.RecordInteractiveCascadeFeedbackRequest): Promise<T.LanguageServer.RecordInteractiveCascadeFeedbackResponse> {
    const req = new (PB as any).RecordInteractiveCascadeFeedbackRequest(input as any);
    const res = await this.client.recordInteractiveCascadeFeedback(req);
    return (res as any) as T.LanguageServer.RecordInteractiveCascadeFeedbackResponse;
  }

  async getCascadeNuxes(input: T.LanguageServer.GetCascadeNuxesRequest): Promise<T.LanguageServer.GetCascadeNuxesResponse> {
    const req = new (PB as any).GetCascadeNuxesRequest(input as any);
    const res = await this.client.getCascadeNuxes(req);
    return (res as any) as T.LanguageServer.GetCascadeNuxesResponse;
  }

  async registerInteraction(input: T.LanguageServer.RegisterInteractionRequest): Promise<T.LanguageServer.RegisterInteractionResponse> {
    const req = new (PB as any).RegisterInteractionRequest(input as any);
    const res = await this.client.registerInteraction(req);
    return (res as any) as T.LanguageServer.RegisterInteractionResponse;
  }

  async getTranscription(input: T.LanguageServer.GetTranscriptionRequest): Promise<T.LanguageServer.GetTranscriptionResponse> {
    const req = new (PB as any).GetTranscriptionRequest(input as any);
    const res = await this.client.getTranscription(req);
    return (res as any) as T.LanguageServer.GetTranscriptionResponse;
  }

  async sendAudioChunk(input: T.LanguageServer.SendAudioChunkRequest): Promise<T.LanguageServer.SendAudioChunkResponse> {
    const req = new (PB as any).SendAudioChunkRequest(input as any);
    const res = await this.client.sendAudioChunk(req);
    return (res as any) as T.LanguageServer.SendAudioChunkResponse;
  }

  async endAudioSession(input: T.LanguageServer.EndAudioSessionRequest): Promise<T.LanguageServer.EndAudioSessionResponse> {
    const req = new (PB as any).EndAudioSessionRequest(input as any);
    const res = await this.client.endAudioSession(req);
    return (res as any) as T.LanguageServer.EndAudioSessionResponse;
  }

  async getInputCompletion(input: T.LanguageServer.GetInputCompletionRequest): Promise<T.LanguageServer.GetInputCompletionResponse> {
    const req = new (PB as any).GetInputCompletionRequest(input as any);
    const res = await this.client.getInputCompletion(req);
    return (res as any) as T.LanguageServer.GetInputCompletionResponse;
  }

  async sendInputCompletionFeedback(input: T.LanguageServer.SendInputCompletionFeedbackRequest): Promise<T.LanguageServer.SendInputCompletionFeedbackResponse> {
    const req = new (PB as any).SendInputCompletionFeedbackRequest(input as any);
    const res = await this.client.sendInputCompletionFeedback(req);
    return (res as any) as T.LanguageServer.SendInputCompletionFeedbackResponse;
  }

  async getStaticExperimentStatus(input: T.LanguageServer.GetStaticExperimentStatusRequest): Promise<T.LanguageServer.GetStaticExperimentStatusResponse> {
    const req = new (PB as any).GetStaticExperimentStatusRequest(input as any);
    const res = await this.client.getStaticExperimentStatus(req);
    return (res as any) as T.LanguageServer.GetStaticExperimentStatusResponse;
  }

  async recordAnalyticsEvent(input: T.LanguageServer.RecordAnalyticsEventRequest): Promise<T.LanguageServer.RecordAnalyticsEventResponse> {
    const req = new (PB as any).RecordAnalyticsEventRequest(input as any);
    const res = await this.client.recordAnalyticsEvent(req);
    return (res as any) as T.LanguageServer.RecordAnalyticsEventResponse;
  }

  async recordError(input: T.LanguageServer.RecordErrorRequest): Promise<T.LanguageServer.RecordErrorResponse> {
    const req = new (PB as any).RecordErrorRequest(input as any);
    const res = await this.client.recordError(req);
    return (res as any) as T.LanguageServer.RecordErrorResponse;
  }

  async recordObservabilityData(input: T.LanguageServer.RecordObservabilityDataRequest): Promise<T.LanguageServer.RecordObservabilityDataResponse> {
    const req = new (PB as any).RecordObservabilityDataRequest(input as any);
    const res = await this.client.recordObservabilityData(req);
    return (res as any) as T.LanguageServer.RecordObservabilityDataResponse;
  }

  async listPages(input: T.LanguageServer.ListPagesRequest): Promise<T.LanguageServer.ListPagesResponse> {
    const req = new (PB as any).ListPagesRequest(input as any);
    const res = await this.client.listPages(req);
    return (res as any) as T.LanguageServer.ListPagesResponse;
  }

  async browserValidateCascadeOrCancelOverlay(input: T.LanguageServer.BrowserValidateCascadeOrCancelOverlayRequest): Promise<T.LanguageServer.BrowserValidateCascadeOrCancelOverlayResponse> {
    const req = new (PB as any).BrowserValidateCascadeOrCancelOverlayRequest(input as any);
    const res = await this.client.browserValidateCascadeOrCancelOverlay(req);
    return (res as any) as T.LanguageServer.BrowserValidateCascadeOrCancelOverlayResponse;
  }

  async openUrl(input: T.LanguageServer.OpenUrlRequest): Promise<T.LanguageServer.OpenUrlResponse> {
    const req = new (PB as any).OpenUrlRequest(input as any);
    const res = await this.client.openUrl(req);
    return (res as any) as T.LanguageServer.OpenUrlResponse;
  }

  async focusUserPage(input: T.LanguageServer.FocusUserPageRequest): Promise<T.LanguageServer.FocusUserPageResponse> {
    const req = new (PB as any).FocusUserPageRequest(input as any);
    const res = await this.client.focusUserPage(req);
    return (res as any) as T.LanguageServer.FocusUserPageResponse;
  }

  async addToBrowserWhitelist(input: T.LanguageServer.AddToBrowserWhitelistRequest): Promise<T.LanguageServer.AddToBrowserWhitelistResponse> {
    const req = new (PB as any).AddToBrowserWhitelistRequest(input as any);
    const res = await this.client.addToBrowserWhitelist(req);
    return (res as any) as T.LanguageServer.AddToBrowserWhitelistResponse;
  }

  async captureConsoleLogs(input: T.LanguageServer.CaptureConsoleLogsRequest): Promise<T.LanguageServer.CaptureConsoleLogsResponse> {
    const req = new (PB as any).CaptureConsoleLogsRequest(input as any);
    const res = await this.client.captureConsoleLogs(req);
    return (res as any) as T.LanguageServer.CaptureConsoleLogsResponse;
  }

  async startScreenRecording(input: T.LanguageServer.StartScreenRecordingRequest): Promise<T.LanguageServer.StartScreenRecordingResponse> {
    const req = new (PB as any).StartScreenRecordingRequest(input as any);
    const res = await this.client.startScreenRecording(req);
    return (res as any) as T.LanguageServer.StartScreenRecordingResponse;
  }

  async saveScreenRecording(input: T.LanguageServer.SaveScreenRecordingRequest): Promise<T.LanguageServer.SaveScreenRecordingResponse> {
    const req = new (PB as any).SaveScreenRecordingRequest(input as any);
    const res = await this.client.saveScreenRecording(req);
    return (res as any) as T.LanguageServer.SaveScreenRecordingResponse;
  }

  async getBrowserWhitelistFilePath(input: T.LanguageServer.GetBrowserWhitelistFilePathRequest): Promise<T.LanguageServer.GetBrowserWhitelistFilePathResponse> {
    const req = new (PB as any).GetBrowserWhitelistFilePathRequest(input as any);
    const res = await this.client.getBrowserWhitelistFilePath(req);
    return (res as any) as T.LanguageServer.GetBrowserWhitelistFilePathResponse;
  }

  async handleScreenRecording(input: T.LanguageServer.HandleScreenRecordingRequest): Promise<T.LanguageServer.HandleScreenRecordingResponse> {
    const req = new (PB as any).HandleScreenRecordingRequest(input as any);
    const res = await this.client.handleScreenRecording(req);
    return (res as any) as T.LanguageServer.HandleScreenRecordingResponse;
  }

  async getAllBrowserWhitelistedUrls(input: T.LanguageServer.GetAllBrowserWhitelistedUrlsRequest): Promise<T.LanguageServer.GetAllBrowserWhitelistedUrlsResponse> {
    const req = new (PB as any).GetAllBrowserWhitelistedUrlsRequest(input as any);
    const res = await this.client.getAllBrowserWhitelistedUrls(req);
    return (res as any) as T.LanguageServer.GetAllBrowserWhitelistedUrlsResponse;
  }

  async captureScreenshot(input: T.LanguageServer.CaptureScreenshotRequest): Promise<T.LanguageServer.CaptureScreenshotResponse> {
    const req = new (PB as any).CaptureScreenshotRequest(input as any);
    const res = await this.client.captureScreenshot(req);
    return (res as any) as T.LanguageServer.CaptureScreenshotResponse;
  }

  async smartOpenBrowser(input: T.LanguageServer.SmartOpenBrowserRequest): Promise<T.LanguageServer.SmartOpenBrowserResponse> {
    const req = new (PB as any).SmartOpenBrowserRequest(input as any);
    const res = await this.client.smartOpenBrowser(req);
    return (res as any) as T.LanguageServer.SmartOpenBrowserResponse;
  }

  async simulateSegFault(input: T.LanguageServer.SimulateSegFaultRequest): Promise<T.LanguageServer.SimulateSegFaultResponse> {
    const req = new (PB as any).SimulateSegFaultRequest(input as any);
    const res = await this.client.simulateSegFault(req);
    return (res as any) as T.LanguageServer.SimulateSegFaultResponse;
  }

  async reconnectExtensionServer(input: T.LanguageServer.ReconnectExtensionServerRequest): Promise<T.LanguageServer.ReconnectExtensionServerResponse> {
    const req = new (PB as any).ReconnectExtensionServerRequest(input as any);
    const res = await this.client.reconnectExtensionServer(req);
    return (res as any) as T.LanguageServer.ReconnectExtensionServerResponse;
  }

  async setCloudCodeURL(input: T.LanguageServer.SetCloudCodeURLRequest): Promise<T.LanguageServer.SetCloudCodeURLResponse> {
    const req = new (PB as any).SetCloudCodeURLRequest(input as any);
    const res = await this.client.setCloudCodeURL(req);
    return (res as any) as T.LanguageServer.SetCloudCodeURLResponse;
  }

  async getTokenBase(input: T.LanguageServer.GetTokenBaseRequest): Promise<T.LanguageServer.GetTokenBaseResponse> {
    const req = new (PB as any).GetTokenBaseRequest(input as any);
    const res = await this.client.getTokenBase(req);
    return (res as any) as T.LanguageServer.GetTokenBaseResponse;
  }

  async runCommand(input: T.LanguageServer.RunCommandRequest): Promise<T.LanguageServer.RunCommandResponse> {
    const req = new (PB as any).RunCommandRequest(input as any);
    const res = await this.client.runCommand(req);
    return (res as any) as T.LanguageServer.RunCommandResponse;
  }

  async validateTerminalSetupScript(input: T.LanguageServer.ValidateTerminalSetupScriptRequest): Promise<T.LanguageServer.ValidateTerminalSetupScriptResponse> {
    const req = new (PB as any).ValidateTerminalSetupScriptRequest(input as any);
    const res = await this.client.validateTerminalSetupScript(req);
    return (res as any) as T.LanguageServer.ValidateTerminalSetupScriptResponse;
  }

  async jetboxWriteState(input: T.LanguageServer.JetboxWriteStateRequest): Promise<T.LanguageServer.JetboxWriteStateResponse> {
    const req = new (PB as any).JetboxWriteStateRequest(input as any);
    const res = await this.client.jetboxWriteState(req);
    return (res as any) as T.LanguageServer.JetboxWriteStateResponse;
  }

  async jetboxWriteSummary(input: T.LanguageServer.JetboxWriteSummaryRequest): Promise<T.LanguageServer.JetboxWriteSummaryResponse> {
    const req = new (PB as any).JetboxWriteSummaryRequest(input as any);
    const res = await this.client.jetboxWriteSummary(req);
    return (res as any) as T.LanguageServer.JetboxWriteSummaryResponse;
  }

  async jetboxDeleteSummary(input: T.LanguageServer.JetboxDeleteSummaryRequest): Promise<T.LanguageServer.JetboxDeleteSummaryResponse> {
    const req = new (PB as any).JetboxDeleteSummaryRequest(input as any);
    const res = await this.client.jetboxDeleteSummary(req);
    return (res as any) as T.LanguageServer.JetboxDeleteSummaryResponse;
  }

  async searchFiles(input: T.LanguageServer.SearchFilesRequest): Promise<T.LanguageServer.SearchFilesResponse> {
    const req = new (PB as any).SearchFilesRequest(input as any);
    const res = await this.client.searchFiles(req);
    return (res as any) as T.LanguageServer.SearchFilesResponse;
  }

  async searchCode(input: T.LanguageServer.SearchCodeRequest): Promise<T.LanguageServer.SearchCodeResponse> {
    const req = new (PB as any).SearchCodeRequest(input as any);
    const res = await this.client.searchCode(req);
    return (res as any) as T.LanguageServer.SearchCodeResponse;
  }

  async searchConversations(input: T.LanguageServer.SearchConversationsRequest): Promise<T.LanguageServer.SearchConversationsResponse> {
    const req = new (PB as any).SearchConversationsRequest(input as any);
    const res = await this.client.searchConversations(req);
    return (res as any) as T.LanguageServer.SearchConversationsResponse;
  }

  async jetboxGetLatestVersion(input: T.LanguageServer.JetboxGetLatestVersionRequest): Promise<T.LanguageServer.JetboxGetLatestVersionResponse> {
    const req = new (PB as any).JetboxGetLatestVersionRequest(input as any);
    const res = await this.client.jetboxGetLatestVersion(req);
    return (res as any) as T.LanguageServer.JetboxGetLatestVersionResponse;
  }

  async getAgentTeamMetadata(input: T.LanguageServer.GetAgentTeamMetadataRequest): Promise<T.LanguageServer.GetAgentTeamMetadataResponse> {
    const req = new (PB as any).GetAgentTeamMetadataRequest(input as any);
    const res = await this.client.getAgentTeamMetadata(req);
    return (res as any) as T.LanguageServer.GetAgentTeamMetadataResponse;
  }

  async getCodeFrequencyForRepo(input: T.LanguageServer.GetCodeFrequencyForRepoRequest): Promise<T.LanguageServer.GetCodeFrequencyForRepoResponse> {
    const req = new (PB as any).GetCodeFrequencyForRepoRequest(input as any);
    const res = await this.client.getCodeFrequencyForRepo(req);
    return (res as any) as T.LanguageServer.GetCodeFrequencyForRepoResponse;
  }

  async sendAgentMessage(input: T.LanguageServer.SendAgentMessageRequest): Promise<T.LanguageServer.SendAgentMessageResponse> {
    const req = new (PB as any).SendAgentMessageRequest(input as any);
    const res = await this.client.sendAgentMessage(req);
    return (res as any) as T.LanguageServer.SendAgentMessageResponse;
  }

  async deleteAgentMessage(input: T.LanguageServer.DeleteAgentMessageRequest): Promise<T.LanguageServer.DeleteAgentMessageResponse> {
    const req = new (PB as any).DeleteAgentMessageRequest(input as any);
    const res = await this.client.deleteAgentMessage(req);
    return (res as any) as T.LanguageServer.DeleteAgentMessageResponse;
  }

  async getLoadCodeAssist(input: T.LanguageServer.GetLoadCodeAssistRequest): Promise<T.LanguageServer.GetLoadCodeAssistResponse> {
    const req = new (PB as any).GetLoadCodeAssistRequest(input as any);
    const res = await this.client.getLoadCodeAssist(req);
    return (res as any) as T.LanguageServer.GetLoadCodeAssistResponse;
  }

  async getAvailableModels(input: T.LanguageServer.GetAvailableModelsRequest): Promise<T.LanguageServer.GetAvailableModelsResponse> {
    const req = new (PB as any).GetAvailableModelsRequest(input as any);
    const res = await this.client.getAvailableModels(req);
    return (res as any) as T.LanguageServer.GetAvailableModelsResponse;
  }

  async retrieveUserQuotaSummary(input: T.LanguageServer.RetrieveUserQuotaSummaryRequest): Promise<T.LanguageServer.RetrieveUserQuotaSummaryResponse> {
    const req = new (PB as any).RetrieveUserQuotaSummaryRequest(input as any);
    const res = await this.client.retrieveUserQuotaSummary(req);
    return (res as any) as T.LanguageServer.RetrieveUserQuotaSummaryResponse;
  }

  async createProject(input: T.LanguageServer.CreateProjectRequest): Promise<T.LanguageServer.CreateProjectResponse> {
    const req = new (PB as any).CreateProjectRequest(input as any);
    const res = await this.client.createProject(req);
    return (res as any) as T.LanguageServer.CreateProjectResponse;
  }

  async createMagicProject(input: T.LanguageServer.CreateMagicProjectRequest): Promise<T.LanguageServer.CreateMagicProjectResponse> {
    const req = new (PB as any).CreateMagicProjectRequest(input as any);
    const res = await this.client.createMagicProject(req);
    return (res as any) as T.LanguageServer.CreateMagicProjectResponse;
  }

  async updateProject(input: T.LanguageServer.UpdateProjectRequest): Promise<T.LanguageServer.UpdateProjectResponse> {
    const req = new (PB as any).UpdateProjectRequest(input as any);
    const res = await this.client.updateProject(req);
    return (res as any) as T.LanguageServer.UpdateProjectResponse;
  }

  async deleteProject(input: T.LanguageServer.DeleteProjectRequest): Promise<T.LanguageServer.DeleteProjectResponse> {
    const req = new (PB as any).DeleteProjectRequest(input as any);
    const res = await this.client.deleteProject(req);
    return (res as any) as T.LanguageServer.DeleteProjectResponse;
  }

  async disassembleProject(input: T.LanguageServer.DisassembleProjectRequest): Promise<T.LanguageServer.DisassembleProjectResponse> {
    const req = new (PB as any).DisassembleProjectRequest(input as any);
    const res = await this.client.disassembleProject(req);
    return (res as any) as T.LanguageServer.DisassembleProjectResponse;
  }

  async backupGeminiDir(input: T.LanguageServer.BackupGeminiDirRequest): Promise<T.LanguageServer.BackupGeminiDirResponse> {
    const req = new (PB as any).BackupGeminiDirRequest(input as any);
    const res = await this.client.backupGeminiDir(req);
    return (res as any) as T.LanguageServer.BackupGeminiDirResponse;
  }

  async generateEnvironmentName(input: T.LanguageServer.GenerateEnvironmentNameRequest): Promise<T.LanguageServer.GenerateEnvironmentNameResponse> {
    const req = new (PB as any).GenerateEnvironmentNameRequest(input as any);
    const res = await this.client.generateEnvironmentName(req);
    return (res as any) as T.LanguageServer.GenerateEnvironmentNameResponse;
  }

  async addEnvironmentToProject(input: T.LanguageServer.AddEnvironmentToProjectRequest): Promise<T.LanguageServer.AddEnvironmentToProjectResponse> {
    const req = new (PB as any).AddEnvironmentToProjectRequest(input as any);
    const res = await this.client.addEnvironmentToProject(req);
    return (res as any) as T.LanguageServer.AddEnvironmentToProjectResponse;
  }

  async resolveFolder(input: T.LanguageServer.ResolveFolderRequest): Promise<T.LanguageServer.ResolveFolderResponse> {
    const req = new (PB as any).ResolveFolderRequest(input as any);
    const res = await this.client.resolveFolder(req);
    return (res as any) as T.LanguageServer.ResolveFolderResponse;
  }

  async readProject(input: T.LanguageServer.ReadProjectRequest): Promise<T.LanguageServer.ReadProjectResponse> {
    const req = new (PB as any).ReadProjectRequest(input as any);
    const res = await this.client.readProject(req);
    return (res as any) as T.LanguageServer.ReadProjectResponse;
  }

  async getDefaultProjectDir(input: T.LanguageServer.GetDefaultProjectDirRequest): Promise<T.LanguageServer.GetDefaultProjectDirResponse> {
    const req = new (PB as any).GetDefaultProjectDirRequest(input as any);
    const res = await this.client.getDefaultProjectDir(req);
    return (res as any) as T.LanguageServer.GetDefaultProjectDirResponse;
  }

  async getAuthStatus(input: T.LanguageServer.GetAuthStatusRequest): Promise<T.LanguageServer.GetAuthStatusResponse> {
    const req = new (PB as any).GetAuthStatusRequest(input as any);
    const res = await this.client.getAuthStatus(req);
    return (res as any) as T.LanguageServer.GetAuthStatusResponse;
  }

  async loginWithBrowser(input: T.LanguageServer.LoginWithBrowserRequest): Promise<T.LanguageServer.LoginWithBrowserResponse> {
    const req = new (PB as any).LoginWithBrowserRequest(input as any);
    const res = await this.client.loginWithBrowser(req);
    return (res as any) as T.LanguageServer.LoginWithBrowserResponse;
  }

  async login(input: T.LanguageServer.LoginRequest): Promise<T.LanguageServer.LoginResponse> {
    const req = new (PB as any).LoginRequest(input as any);
    const res = await this.client.login(req);
    return (res as any) as T.LanguageServer.LoginResponse;
  }

  async authLogout(input: T.LanguageServer.AuthLogoutRequest): Promise<T.LanguageServer.AuthLogoutResponse> {
    const req = new (PB as any).AuthLogoutRequest(input as any);
    const res = await this.client.authLogout(req);
    return (res as any) as T.LanguageServer.AuthLogoutResponse;
  }

  async hasAuthToken(input: T.LanguageServer.HasAuthTokenRequest): Promise<T.LanguageServer.HasAuthTokenResponse> {
    const req = new (PB as any).HasAuthTokenRequest(input as any);
    const res = await this.client.hasAuthToken(req);
    return (res as any) as T.LanguageServer.HasAuthTokenResponse;
  }

  async validateProject(input: T.LanguageServer.ValidateProjectRequest): Promise<T.LanguageServer.ValidateProjectResponse> {
    const req = new (PB as any).ValidateProjectRequest(input as any);
    const res = await this.client.validateProject(req);
    return (res as any) as T.LanguageServer.ValidateProjectResponse;
  }

  async getGrantedScopes(input: T.LanguageServer.GetGrantedScopesRequest): Promise<T.LanguageServer.GetGrantedScopesResponse> {
    const req = new (PB as any).GetGrantedScopesRequest(input as any);
    const res = await this.client.getGrantedScopes(req);
    return (res as any) as T.LanguageServer.GetGrantedScopesResponse;
  }

  async createScratchProjectFolder(input: T.LanguageServer.CreateScratchProjectFolderRequest): Promise<T.LanguageServer.CreateScratchProjectFolderResponse> {
    const req = new (PB as any).CreateScratchProjectFolderRequest(input as any);
    const res = await this.client.createScratchProjectFolder(req);
    return (res as any) as T.LanguageServer.CreateScratchProjectFolderResponse;
  }

  async getServerConfiguration(input: T.LanguageServer.GetServerConfigurationRequest): Promise<T.LanguageServer.GetServerConfigurationResponse> {
    const req = new (PB as any).GetServerConfigurationRequest(input as any);
    const res = await this.client.getServerConfiguration(req);
    return (res as any) as T.LanguageServer.GetServerConfigurationResponse;
  }

  async getCapabilities(input: T.LanguageServer.GetCapabilitiesRequest): Promise<T.LanguageServer.GetCapabilitiesResponse> {
    const req = new (PB as any).GetCapabilitiesRequest(input as any);
    const res = await this.client.getCapabilities(req);
    return (res as any) as T.LanguageServer.GetCapabilitiesResponse;
  }

  async fetchAdminControls(input: T.LanguageServer.FetchAdminControlsRequest): Promise<T.LanguageServer.FetchAdminControlsResponse> {
    const req = new (PB as any).FetchAdminControlsRequest(input as any);
    const res = await this.client.fetchAdminControls(req);
    return (res as any) as T.LanguageServer.FetchAdminControlsResponse;
  }

}