// @generated by scripts/generate_facade.ts
// DO NOT EDIT MANUALLY

import { BrowserStateSnapshotInput, CciWithSubrangeInput, CodeContextItemInput, DocumentInput, DocumentOutlineInput, GuidelineInput, TerminalShellCommandInput } from "../codeium_common_pb/codeium_common_pb.js";

export interface CciWithSubrangeWithRetrievalMetadataInput {
  cciWithSubrange?: CciWithSubrangeInput;
}

export interface ContextModuleResultInput {
  retrievedCciWithSubranges?: CciWithSubrangeWithRetrievalMetadataInput[];
  activeDocument?: DocumentInput;
  activeDocumentOutline?: DocumentOutlineInput;
  localNodeState?: LocalNodeStateInput;
  guideline?: GuidelineInput;
  openDocuments?: DocumentInput[];
  runningTerminalCommands?: TerminalShellCommandInput[];
  browserStateSnapshot?: BrowserStateSnapshotInput;
}

export interface LocalNodeStateInput {
  currentNode?: CodeContextItemInput;
  closestAboveNode?: CodeContextItemInput;
  closestBelowNode?: CodeContextItemInput;
}
